[
{:short-english "ah!", :hanyu "啊", :pinyin "a1", :usage-count 2},
{:known true, :hanyu "爱", :pinyin "ai4", :usage-count 2},
{:hanyu "爱人", :pinyin "ai4 ren5", :usage-count 1},
{:hanyu "安", :pinyin "an1", :usage-count 1},
{:hanyu "安", :pinyin "An1", :usage-count 1},
{:hanyu "安徽", :pinyin "An1 hui1", :usage-count 1},
{:hanyu "安静", :pinyin "an1 jing4", :usage-count 1},
{:hanyu "安眠药", :pinyin "an1 mian2 yao4", :usage-count 1},
{:hanyu "昂", :pinyin "ang2", :usage-count 1},
{:hanyu "昂贵", :pinyin "ang2 gui4", :usage-count 1},
{:hanyu "八", :pinyin "ba1", :usage-count 1},
{:hanyu "巴士", :pinyin "ba1 shi4", :usage-count 1},
{:hanyu "把", :pinyin "ba3", :usage-count 1},
{:hanyu "爸爸", :pinyin "ba4 ba5", :usage-count 1},
{:short-english "(suggestion)", :hanyu "吧", :pinyin "ba5", :usage-count 1},
{:hanyu "白", :pinyin "bai2", :usage-count 1},
{:hanyu "白", :pinyin "Bai2", :usage-count 1},
{:hanyu "白酒", :pinyin "bai2 jiu3", :usage-count 1},
{:hanyu "百", :pinyin "bai3", :usage-count 2},
{:hanyu "百", :pinyin "Bai3", :usage-count 1},
{:hanyu "百度", :pinyin "Bai3 du4", :usage-count 1},
{:hanyu "百货公司", :pinyin "bai3 huo4 gong1 si1", :usage-count 1},
{:hanyu "搬", :pinyin "ban1", :usage-count 1},
{:hanyu "般", :pinyin "ban1", :usage-count 1},
{:hanyu "搬家", :pinyin "ban1 jia1", :usage-count 1},
{:hanyu "版", :pinyin "ban3", :usage-count 1},
{:hanyu "半", :pinyin "ban4", :usage-count 1},
{:hanyu "办公室", :pinyin "ban4 gong1 shi4", :usage-count 1},
{:hanyu "半夜", :pinyin "ban4 ye4", :usage-count 1},
{:hanyu "帮", :pinyin "bang1", :usage-count 1},
{:hanyu "帮助", :pinyin "bang1 zhu4", :usage-count 6},
{:hanyu "包", :pinyin "bao1", :usage-count 1},
{:hanyu "包", :pinyin "Bao1", :usage-count 1},
{:hanyu "宝贝", :pinyin "bao3 bei4", :usage-count 1},
{:hanyu "保持", :pinyin "bao3 chi2", :usage-count 1},
{:hanyu "保密", :pinyin "bao3 mi4", :usage-count 1},
{:hanyu "保暖", :pinyin "bao3 nuan3", :usage-count 1},
{:hanyu "保守", :pinyin "bao3 shou3", :usage-count 1},
{:hanyu "保佑", :pinyin "bao3 you4", :usage-count 1},
{:hanyu "抱歉", :pinyin "bao4 qian4", :usage-count 1},
{:hanyu "北", :pinyin "bei3", :usage-count 1},
{:known true, :hanyu "北京", :pinyin "Bei3 jing1", :usage-count 2},
{:hanyu "被", :pinyin "bei4", :usage-count 1},
{:hanyu "本", :pinyin "ben3", :usage-count 1},
{:short-english "(compare)", :hanyu "比", :pinyin "bi3", :usage-count 9},
{:hanyu "比", :pinyin "Bi3", :usage-count 1},
{:hanyu "笔记本", :pinyin "bi3 ji4 ben3", :usage-count 1},
{:hanyu "比较", :pinyin "bi3 jiao4", :usage-count 1},
{:hanyu "比如", :pinyin "bi3 ru2", :usage-count 1},
{:hanyu "比萨", :pinyin "bi3 sa4", :usage-count 1},
{:hanyu "比萨", :pinyin "Bi3 sa4", :usage-count 1},
{:hanyu "比喻", :pinyin "bi3 yu4", :usage-count 1},
{:hanyu "必", :pinyin "bi4", :usage-count 1},
{:hanyu "壁球", :pinyin "bi4 qiu2", :usage-count 1},
{:hanyu "必须", :pinyin "bi4 xu1", :usage-count 1},
{:hanyu "毕业", :pinyin "bi4 ye4", :usage-count 1},
{:hanyu "闭着", :pinyin "bi4 zhe5", :usage-count 1},
{:hanyu "边", :pinyin "bian1", :usage-count 1},
{:hanyu "变化", :pinyin "bian4 hua4", :usage-count 1},
{:hanyu "表单", :pinyin "biao3 dan1", :usage-count 1},
{:short-english "do not", :hanyu "别", :pinyin "bie2", :usage-count 3},
{:hanyu "别", :pinyin "Bie2", :usage-count 1},
{:hanyu "别墅", :pinyin "bie2 shu4", :usage-count 1},
{:hanyu "宾馆", :pinyin "bin1 guan3", :usage-count 1},
{:hanyu "并", :pinyin "bing4", :usage-count 1},
{:hanyu "博客", :pinyin "bo2 ke4", :usage-count 1},
{:known true, :hanyu "不", :pinyin "bu4", :usage-count 23},
{:hanyu "布", :pinyin "bu4", :usage-count 1},
{:hanyu "不便", :pinyin "bu4 bian4", :usage-count 1},
{:hanyu "不错", :pinyin "bu4 cuo4", :usage-count 1},
{:known true, :hanyu "不好", :pinyin "bu4 hao3", :usage-count 1},
{:hanyu "不久", :pinyin "bu4 jiu3", :usage-count 3},
{:hanyu "不可思议", :pinyin "bu4 ke3 si1 yi4", :usage-count 1},
{:hanyu "不能", :pinyin "bu4 neng2", :usage-count 1},
{:hanyu "不如", :pinyin "bu4 ru2", :usage-count 1},
{:known true, :short-english "no", :hanyu "不是", :pinyin "bu4 shi4", :usage-count 1},
{:hanyu "不下", :pinyin "bu4 xia4", :usage-count 1},
{:hanyu "不像话", :pinyin "bu4 xiang4 hua4", :usage-count 1},
{:hanyu "不行", :pinyin "bu4 xing2", :usage-count 1},
{:hanyu "不幸", :pinyin "bu4 xing4", :usage-count 1},
{:hanyu "猜", :pinyin "cai1", :usage-count 1},
{:hanyu "才能", :pinyin "cai2 neng2", :usage-count 1},
{:hanyu "采取", :pinyin "cai3 qu3", :usage-count 1},
{:hanyu "菜", :pinyin "cai4", :usage-count 1},
{:hanyu "菜单", :pinyin "cai4 dan1", :usage-count 1},
{:hanyu "参观", :pinyin "can1 guan1", :usage-count 1},
{:hanyu "参加", :pinyin "can1 jia1", :usage-count 1},
{:hanyu "查看", :pinyin "cha2 kan4", :usage-count 1},
{:hanyu "查找", :pinyin "cha2 zhao3", :usage-count 1},
{:hanyu "差", :pinyin "cha4", :usage-count 1},
{:hanyu "差点", :pinyin "cha4 dian3", :usage-count 1},
{:hanyu "长", :pinyin "chang2", :usage-count 1},
{:hanyu "常常", :pinyin "chang2 chang2", :usage-count 1},
{:hanyu "长城", :pinyin "Chang2 cheng2", :usage-count 1},
{:hanyu "尝试", :pinyin "chang2 shi4", :usage-count 2},
{:hanyu "长途", :pinyin "chang2 tu2", :usage-count 1},
{:hanyu "倡议", :pinyin "chang4 yi4", :usage-count 1},
{:hanyu "嘲笑", :pinyin "chao2 xiao4", :usage-count 1},
{:hanyu "炒", :pinyin "chao3", :usage-count 1},
{:hanyu "吵嘴", :pinyin "chao3 zui3", :usage-count 2},
{:hanyu "车", :pinyin "che1", :usage-count 1},
{:hanyu "车", :pinyin "Che1", :usage-count 1},
{:hanyu "沉默", :pinyin "chen2 mo4", :usage-count 1},
{:hanyu "城", :pinyin "cheng2", :usage-count 1},
{:hanyu "成功", :pinyin "cheng2 gong1", :usage-count 1},
{:hanyu "成功", :pinyin "Cheng2 gong1", :usage-count 1},
{:hanyu "承诺", :pinyin "cheng2 nuo4", :usage-count 1},
{:hanyu "成熟", :pinyin "cheng2 shu2", :usage-count 1},
{:hanyu "吃", :pinyin "chi1", :usage-count 1},
{:hanyu "吃饭", :pinyin "chi1 fan4", :usage-count 1},
{:hanyu "迟到", :pinyin "chi2 dao4", :usage-count 1},
{:hanyu "齿", :pinyin "chi3", :usage-count 1},
{:hanyu "重庆", :pinyin "Chong2 qing4", :usage-count 1},
{:hanyu "宠", :pinyin "chong3", :usage-count 1},
{:hanyu "宠儿", :pinyin "chong3 er2", :short-english "pet", :known true, :usage-count 2},
{:hanyu "宠物", :pinyin "chong3 wu4", :usage-count 1},
{:hanyu "出", :pinyin "chu1", :usage-count 1},
{:hanyu "出去", :pinyin "chu1 qu4", :usage-count 1},
{:hanyu "出生", :pinyin "chu1 sheng1", :usage-count 1},
{:hanyu "出外", :pinyin "chu1 wai4", :usage-count 1},
{:hanyu "出现", :pinyin "chu1 xian4", :usage-count 1},
{:hanyu "出行", :pinyin "chu1 xing2", :usage-count 1},
{:hanyu "出租", :pinyin "chu1 zu1", :usage-count 1},
{:hanyu "出租汽车", :pinyin "chu1 zu1 qi4 che1", :usage-count 1},
{:hanyu "除了", :pinyin "chu2 le5", :usage-count 1},
{:hanyu "处", :pinyin "chu3", :usage-count 1},
{:hanyu "穿", :pinyin "chuan1", :usage-count 1},
{:hanyu "传说", :pinyin "chuan2 shuo1", :usage-count 1},
{:hanyu "床", :pinyin "chuang2", :usage-count 1},
{:hanyu "春节", :pinyin "Chun1 jie2", :usage-count 1},
{:hanyu "春天", :pinyin "chun1 tian1", :usage-count 1},
{:hanyu "春运", :pinyin "chun1 yun4", :usage-count 1},
{:hanyu "词", :pinyin "ci2", :usage-count 1},
{:hanyu "词语", :pinyin "ci2 yu3", :usage-count 1},
{:hanyu "此", :pinyin "ci3", :usage-count 1},
{:hanyu "从", :pinyin "cong2", :usage-count 1},
{:hanyu "从", :pinyin "Cong2", :usage-count 1},
{:hanyu "从不", :pinyin "cong2 bu4", :usage-count 1},
{:hanyu "脆弱", :pinyin "cui4 ruo4", :usage-count 1},
{:hanyu "错", :pinyin "cuo4", :usage-count 1},
{:hanyu "错", :pinyin "Cuo4", :usage-count 1},
{:hanyu "错误", :pinyin "cuo4 wu4", :usage-count 1},
{:hanyu "打", :pinyin "da3", :usage-count 1},
{:hanyu "打工", :pinyin "da3 gong1", :usage-count 1},
{:hanyu "打开", :pinyin "da3 kai1", :usage-count 1},
{:hanyu "大", :pinyin "da4", :usage-count 1},
{:hanyu "大巴", :pinyin "da4 ba1", :usage-count 1},
{:hanyu "大概", :pinyin "da4 gai4", :usage-count 1},
{:hanyu "大家", :pinyin "da4 jia1", :usage-count 1},
{:hanyu "大门", :pinyin "da4 men2", :usage-count 1},
{:hanyu "大脑", :pinyin "da4 nao3", :usage-count 1},
{:hanyu "大厦", :pinyin "da4 sha4", :usage-count 1},
{:hanyu "大使馆", :pinyin "da4 shi3 guan3", :usage-count 3},
{:hanyu "大蒜", :pinyin "da4 suan4", :usage-count 1},
{:hanyu "大小", :pinyin "da4 xiao3", :usage-count 1},
{:hanyu "大学", :pinyin "da4 xue2", :usage-count 1},
{:hanyu "大学", :pinyin "Da4 xue2", :usage-count 1},
{:hanyu "大约", :pinyin "da4 yue1", :usage-count 1},
{:hanyu "带", :pinyin "dai4", :usage-count 1},
{:hanyu "单", :pinyin "dan1", :usage-count 1},
{:hanyu "单独", :pinyin "dan1 du2", :usage-count 1},
{:hanyu "单人", :pinyin "dan1 ren2", :usage-count 1},
{:hanyu "担心", :pinyin "dan1 xin1", :usage-count 1},
{:hanyu "但", :pinyin "dan4", :usage-count 1},
{:hanyu "蛋", :pinyin "dan4", :usage-count 1},
{:hanyu "蛋糕", :pinyin "dan4 gao1", :usage-count 1},
{:known true, :hanyu "但是", :pinyin "dan4 shi4", :usage-count 4},
{:hanyu "当", :pinyin "dang1", :usage-count 1},
{:hanyu "当然", :pinyin "dang1 ran2", :usage-count 1},
{:hanyu "当时", :pinyin "dang1 shi2", :usage-count 1},
{:short-english "to", :hanyu "到", :pinyin "dao4", :usage-count 4},
{:hanyu "到处", :pinyin "dao4 chu4", :usage-count 1},
{:hanyu "到达", :pinyin "dao4 da2", :usage-count 1},
{:hanyu "到来", :pinyin "dao4 lai2", :usage-count 1},
{:hanyu "得到", :pinyin "de2 dao4", :usage-count 1},
{:hanyu "地", :pinyin "de5", :usage-count 1},
{:short-english "(verb specifier)", :hanyu "得", :pinyin "de5", :usage-count 8},
{:known true, :hanyu "的", :pinyin "de5", :usage-count 37},
{:hanyu "灯", :pinyin "deng1", :usage-count 1},
{:hanyu "登陆", :pinyin "deng1 lu4", :usage-count 1},
{:short-english "wait for", :hanyu "等", :pinyin "deng3", :usage-count 2},
{:hanyu "等等", :pinyin "deng3 deng3", :usage-count 1},
{:hanyu "等于", :pinyin "deng3 yu2", :usage-count 1},
{:hanyu "低头", :pinyin "di1 tou2", :usage-count 1},
{:hanyu "第", :pinyin "di4", :usage-count 1},
{:hanyu "地道", :pinyin "di4 dao5", :usage-count 1},
{:hanyu "第二", :pinyin "di4 er4", :usage-count 1},
{:hanyu "地方", :pinyin "di4 fang1", :usage-count 1},
{:hanyu "地铁", :pinyin "di4 tie3", :usage-count 1},
{:hanyu "地图", :pinyin "di4 tu2", :usage-count 1},
{:hanyu "第一次", :pinyin "di4 yi1 ci4", :usage-count 1},
{:hanyu "地址", :pinyin "di4 zhi3", :usage-count 1},
{:hanyu "典", :pinyin "dian3", :usage-count 1},
{:hanyu "点", :pinyin "dian3", :usage-count 1},
{:hanyu "店", :pinyin "dian4", :usage-count 1},
{:hanyu "电话", :pinyin "dian4 hua4", :usage-count 1},
{:hanyu "电脑", :pinyin "dian4 nao3", :usage-count 1},
{:hanyu "电脑业者", :pinyin "dian4 nao3 ye4 zhe3", :usage-count 1},
{:hanyu "电影", :pinyin "dian4 ying3", :usage-count 1},
{:hanyu "电邮", :pinyin "dian4 you2", :usage-count 11},
{:hanyu "电子", :pinyin "dian4 zi3", :usage-count 1},
{:hanyu "电子邮件", :pinyin "dian4 zi3 you2 jian4", :usage-count 1},
{:hanyu "调查", :pinyin "diao4 cha2", :usage-count 1},
{:hanyu "冬季", :pinyin "dong1 ji4", :usage-count 1},
{:hanyu "冬天", :pinyin "dong1 tian1", :usage-count 1},
{:hanyu "东西", :pinyin "dong1 xi5", :usage-count 1},
{:hanyu "懂", :pinyin "dong3", :usage-count 1},
{:hanyu "动物", :pinyin "dong4 wu4", :usage-count 1},
{:hanyu "都", :pinyin "dou1", :usage-count 1},
{:hanyu "独自", :pinyin "du2 zi4", :usage-count 1},
{:hanyu "度", :pinyin "du4", :usage-count 1},
{:hanyu "肚子", :pinyin "du4 zi5", :usage-count 1},
{:hanyu "短", :pinyin "duan3", :usage-count 1},
{:hanyu "短信", :pinyin "duan3 xin4", :usage-count 1},
{:hanyu "短暂", :pinyin "duan3 zan4", :usage-count 1},
{:hanyu "对", :pinyin "dui4", :usage-count 2},
{:hanyu "兑换", :pinyin "dui4 huan4", :usage-count 1},
{:hanyu "顿", :pinyin "dun4", :usage-count 1},
{:hanyu "多", :pinyin "duo1", :short-english "many", :known true, :usage-count 9},
{:hanyu "多久", :pinyin "duo1 jiu3", :usage-count 1},
{:hanyu "多么", :pinyin "duo1 me5", :usage-count 1},
{:hanyu "多少", :pinyin "duo1 shao3", :usage-count 1},
{:known true, :short-english "how much", :hanyu "多少", :pinyin "duo1 shao5", :usage-count 2},
{:hanyu "多余", :pinyin "duo1 yu2", :usage-count 1},
{:hanyu "恶心", :pinyin "e3 xin1", :usage-count 1},
{:hanyu "饿", :pinyin "e4", :usage-count 1},
{:hanyu "恩", :pinyin "en1", :usage-count 1},
{:hanyu "而且", :pinyin "er2 qie3", :usage-count 1},
{:hanyu "儿子", :pinyin "er2 zi5", :usage-count 1},
{:known true, :hanyu "二", :pinyin "er4", :usage-count 1},
{:hanyu "发", :pinyin "fa1", :usage-count 6},
{:hanyu "发车", :pinyin "fa1 che1", :usage-count 1},
{:hanyu "发给", :pinyin "fa1 gei3", :usage-count 1},
{:hanyu "发生", :pinyin "fa1 sheng1", :usage-count 1},
{:hanyu "发送", :pinyin "fa1 song4", :usage-count 1},
{:hanyu "翻译", :pinyin "fan1 yi4", :usage-count 1},
{:hanyu "烦恼", :pinyin "fan2 nao3", :usage-count 1},
{:hanyu "烦人", :pinyin "fan2 ren2", :usage-count 1},
{:hanyu "饭", :pinyin "fan4", :usage-count 1},
{:hanyu "饭菜", :pinyin "fan4 cai4", :usage-count 1},
{:hanyu "饭店", :pinyin "fan4 dian4", :usage-count 1},
{:hanyu "饭馆", :pinyin "fan4 guan3", :usage-count 1},
{:hanyu "方便", :pinyin "fang1 bian4", :usage-count 1},
{:hanyu "房", :pinyin "fang2", :usage-count 1},
{:hanyu "房", :pinyin "Fang2", :usage-count 1},
{:hanyu "房间", :pinyin "fang2 jian1", :usage-count 1},
{:hanyu "房子", :pinyin "fang2 zi5", :usage-count 1},
{:hanyu "放", :pinyin "fang4", :usage-count 1},
{:hanyu "放假", :pinyin "fang4 jia4", :usage-count 1},
{:hanyu "放松", :pinyin "fang4 song1", :usage-count 1},
{:hanyu "非常", :pinyin "fei1 chang2", :usage-count 1},
{:known true, :hanyu "飞机", :pinyin "fei1 ji1", :usage-count 1},
{:known true, :hanyu "飞机场", :pinyin "fei1 ji1 chang3", :usage-count 1},
{:hanyu "飞机票", :pinyin "fei1 ji1 piao4", :usage-count 1},
{:hanyu "肥", :pinyin "fei2", :usage-count 1},
{:hanyu "分", :pinyin "fen1", :usage-count 1},
{:known true, :short-english "Finland", :hanyu "芬兰", :pinyin "Fen1 lan2", :usage-count 24},
{:hanyu "芬兰语", :pinyin "Fen1 lan2 yu3", :usage-count 1},
{:hanyu "分钟", :pinyin "fen1 zhong1", :usage-count 1},
{:hanyu "愤怒", :pinyin "fen4 nu4", :usage-count 1},
{:hanyu "封", :pinyin "feng1", :usage-count 1},
{:hanyu "封", :pinyin "Feng1", :usage-count 1},
{:hanyu "风景", :pinyin "feng1 jing3", :usage-count 1},
{:hanyu "服务员", :pinyin "fu2 wu4 yuan2", :usage-count 1},
{:hanyu "付", :pinyin "fu4", :usage-count 1},
{:hanyu "付", :pinyin "Fu4", :usage-count 1},
{:hanyu "副本", :pinyin "fu4 ben3", :usage-count 1},
{:hanyu "附近", :pinyin "fu4 jin4", :usage-count 1},
{:hanyu "父母", :pinyin "fu4 mu3", :usage-count 1},
{:hanyu "付钱", :pinyin "fu4 qian2", :usage-count 1},
{:hanyu "父亲", :pinyin "fu4 qin1", :usage-count 1},
{:hanyu "富裕", :pinyin "fu4 yu4", :usage-count 1},
{:hanyu "富裕", :pinyin "Fu4 yu4", :usage-count 1},
{:hanyu "复杂", :pinyin "fu4 za2", :usage-count 1},
{:hanyu "该", :pinyin "gai1", :usage-count 1},
{:hanyu "改变", :pinyin "gai3 bian4", :usage-count 1},
{:hanyu "敢", :pinyin "gan3", :usage-count 1},
{:hanyu "赶", :pinyin "gan3", :usage-count 1},
{:hanyu "感到", :pinyin "gan3 dao4", :usage-count 1},
{:hanyu "感觉", :pinyin "gan3 jue2", :usage-count 1},
{:hanyu "感冒", :pinyin "gan3 mao4", :usage-count 1},
{:hanyu "感情", :pinyin "gan3 qing2", :usage-count 1},
{:hanyu "感谢", :pinyin "gan3 xie4", :usage-count 1},
{:hanyu "刚", :pinyin "gang1", :usage-count 1},
{:hanyu "高", :pinyin "gao1", :usage-count 1},
{:hanyu "高", :pinyin "Gao1", :usage-count 1},
{:hanyu "高速", :pinyin "gao1 su4", :usage-count 1},
{:hanyu "高兴", :pinyin "gao1 xing4", :usage-count 1},
{:hanyu "告诉", :pinyin "gao4 su5", :usage-count 7},
{:hanyu "歌", :pinyin "ge1", :usage-count 1},
{:hanyu "歌词", :pinyin "ge1 ci2", :usage-count 1},
{:hanyu "格", :pinyin "ge2", :usage-count 1},
{:hanyu "个", :pinyin "ge4", :usage-count 1},
{:known true, :hanyu "给", :pinyin "gei3", :usage-count 7},
{:hanyu "跟", :pinyin "gen1", :usage-count 1},
{:hanyu "更", :pinyin "geng4", :usage-count 4},
{:hanyu "公共", :pinyin "gong1 gong4", :usage-count 1},
{:hanyu "公共汽车", :pinyin "gong1 gong4 qi4 che1", :usage-count 1},
{:hanyu "工具", :pinyin "gong1 ju4", :usage-count 1},
{:hanyu "公路", :pinyin "gong1 lu4", :usage-count 1},
{:hanyu "工艺美术", :pinyin "gong1 yi4 mei3 shu4", :usage-count 1},
{:hanyu "公园", :pinyin "gong1 yuan2", :usage-count 1},
{:hanyu "工作", :pinyin "gong1 zuo4", :usage-count 2},
{:known true, :hanyu "狗", :pinyin "gou3", :usage-count 1},
{:hanyu "狗粮", :pinyin "gou3 liang2", :usage-count 1},
{:hanyu "购", :pinyin "gou4", :usage-count 1},
{:hanyu "构成", :pinyin "gou4 cheng2", :usage-count 1},
{:hanyu "购买", :pinyin "gou4 mai3", :usage-count 1},
{:hanyu "孤儿院", :pinyin "gu1 er2 yuan4", :usage-count 1},
{:hanyu "固定", :pinyin "gu4 ding4", :usage-count 1},
{:hanyu "顾客", :pinyin "gu4 ke4", :usage-count 1},
{:hanyu "故事", :pinyin "gu4 shi4", :usage-count 1},
{:hanyu "拐", :pinyin "guai3", :usage-count 1},
{:hanyu "关", :pinyin "guan1", :usage-count 1},
{:hanyu "关", :pinyin "Guan1", :usage-count 1},
{:hanyu "关闭", :pinyin "guan1 bi4", :usage-count 1},
{:hanyu "关心", :pinyin "guan1 xin1", :usage-count 1},
{:hanyu "关于", :pinyin "guan1 yu2", :usage-count 1},
{:hanyu "馆", :pinyin "guan3", :usage-count 4},
{:hanyu "鬼", :pinyin "gui3", :usage-count 1},
{:hanyu "贵", :pinyin "gui4", :usage-count 2},
{:hanyu "国", :pinyin "guo2", :usage-count 1},
{:hanyu "国", :pinyin "Guo2", :usage-count 1},
{:hanyu "国际", :pinyin "guo2 ji4", :usage-count 1},
{:hanyu "国家", :pinyin "guo2 jia1", :usage-count 1},
{:hanyu "果", :pinyin "guo3", :usage-count 1},
{:hanyu "果汁", :pinyin "guo3 zhi1", :usage-count 1},
{:short-english "(experienced)", :hanyu "过", :pinyin "guo4", :usage-count 3},
{:hanyu "过", :pinyin "Guo4", :usage-count 1},
{:hanyu "过度", :pinyin "guo4 du4", :usage-count 1},
{:hanyu "过年", :pinyin "guo4 nian2", :usage-count 1},
{:hanyu "哈", :pinyin "ha1", :usage-count 1},
{:hanyu "哈", :pinyin "Ha1", :usage-count 1},
{:hanyu "哈哈", :pinyin "ha1 ha1", :usage-count 1},
{:hanyu "嗨", :pinyin "hai1", :usage-count 1},
{:hanyu "孩", :pinyin "hai2", :usage-count 1},
{:hanyu "还", :pinyin "hai2", :usage-count 3},
{:hanyu "还是", :pinyin "hai2 shi5", :usage-count 4},
{:hanyu "还有", :pinyin "hai2 you3", :usage-count 1},
{:hanyu "孩子", :pinyin "hai2 zi5", :usage-count 1},
{:hanyu "孩子们", :pinyin "hai2 zi5 men5", :usage-count 5},
{:hanyu "海", :pinyin "hai3", :usage-count 1},
{:hanyu "海", :pinyin "Hai3", :usage-count 1},
{:hanyu "害怕", :pinyin "hai4 pa4", :usage-count 1},
{:hanyu "害羞", :pinyin "hai4 xiu1", :usage-count 1},
{:hanyu "寒冷", :pinyin "han2 leng3", :usage-count 1},
{:hanyu "汉语", :pinyin "Han4 yu3", :usage-count 2},
{:known true, :short-english "good", :hanyu "好", :pinyin "hao3", :usage-count 14},
{:hanyu "好好", :pinyin "hao3 hao3", :usage-count 1},
{:hanyu "好看", :pinyin "hao3 kan4", :usage-count 1},
{:hanyu "号", :pinyin "hao4", :usage-count 1},
{:hanyu "号码", :pinyin "hao4 ma3", :usage-count 1},
{:hanyu "喝", :pinyin "he1", :usage-count 1},
{:hanyu "呵呵", :pinyin "he1 he1", :usage-count 1},
{:hanyu "喝酒", :pinyin "he1 jiu3", :usage-count 1},
{:hanyu "和", :pinyin "he2", :usage-count 6},
{:hanyu "河", :pinyin "he2", :usage-count 1},
{:hanyu "和", :pinyin "He2", :usage-count 1},
{:hanyu "合理", :pinyin "he2 li3", :usage-count 1},
{:hanyu "河南", :pinyin "He2 nan2", :usage-count 1},
{:hanyu "河水", :pinyin "he2 shui3", :usage-count 1},
{:hanyu "合影", :pinyin "he2 ying3", :usage-count 1},
{:short-english "Helsinki", :hanyu "赫尔辛基", :pinyin "He4 er3 xin1 ji1", :usage-count 1},
{:hanyu "黑", :pinyin "hei1", :usage-count 1},
{:hanyu "黑", :pinyin "Hei1", :usage-count 1},
{:known true, :short-english "very", :hanyu "很", :pinyin "hen3", :usage-count 21},
{:hanyu "恨", :pinyin "hen4", :usage-count 1},
{:hanyu "宏", :pinyin "hong2", :usage-count 1},
{:hanyu "红", :pinyin "hong2", :usage-count 1},
{:hanyu "红", :pinyin "Hong2", :usage-count 1},
{:hanyu "红旗", :pinyin "hong2 qi2", :usage-count 1},
{:hanyu "红旗", :pinyin "Hong2 qi2", :usage-count 1},
{:hanyu "红色", :pinyin "hong2 se4", :usage-count 1},
{:hanyu "喉咙", :pinyin "hou2 long2", :usage-count 1},
{:hanyu "后", :pinyin "hou4", :usage-count 1},
{:hanyu "后", :pinyin "Hou4", :usage-count 1},
{:hanyu "后来", :pinyin "hou4 lai2", :usage-count 2},
{:hanyu "后面", :pinyin "hou4 mian5", :usage-count 1},
{:hanyu "后天", :pinyin "hou4 tian1", :usage-count 1},
{:hanyu "胡子", :pinyin "hu2 zi5", :usage-count 1},
{:hanyu "互", :pinyin "hu4", :usage-count 1},
{:hanyu "护", :pinyin "hu4", :usage-count 1},
{:hanyu "护照", :pinyin "hu4 zhao4", :usage-count 1},
{:hanyu "花", :pinyin "hua1", :usage-count 1},
{:hanyu "花", :pinyin "Hua1", :usage-count 1},
{:hanyu "花园", :pinyin "hua1 yuan2", :usage-count 1},
{:hanyu "滑雪", :pinyin "hua2 xue3", :usage-count 1},
{:hanyu "画", :pinyin "hua4", :usage-count 1},
{:hanyu "话", :pinyin "hua4", :usage-count 1},
{:hanyu "画面", :pinyin "hua4 mian4", :usage-count 1},
{:hanyu "化妆", :pinyin "hua4 zhuang1", :usage-count 1},
{:hanyu "坏", :pinyin "huai4", :usage-count 1},
{:hanyu "坏人", :pinyin "huai4 ren2", :usage-count 1},
{:hanyu "坏事", :pinyin "huai4 shi4", :usage-count 1},
{:hanyu "欢迎", :pinyin "huan1 ying2", :usage-count 3},
{:hanyu "环城", :pinyin "huan2 cheng2", :usage-count 1},
{:hanyu "还给", :pinyin "huan2 gei3", :usage-count 1},
{:hanyu "环境", :pinyin "huan2 jing4", :usage-count 1},
{:hanyu "缓慢", :pinyin "huan3 man4", :usage-count 1},
{:hanyu "换", :pinyin "huan4", :usage-count 3},
{:hanyu "灰", :pinyin "hui1", :usage-count 1},
{:hanyu "灰色", :pinyin "hui1 se4", :usage-count 1},
{:hanyu "回", :pinyin "hui2", :usage-count 1},
{:hanyu "回答", :pinyin "hui2 da2", :usage-count 3},
{:hanyu "回复", :pinyin "hui2 fu4", :usage-count 1},
{:hanyu "回家", :pinyin "hui2 jia1", :usage-count 1},
{:hanyu "会", :pinyin "hui4", :usage-count 2},
{:hanyu "绘画", :pinyin "hui4 hua4", :usage-count 1},
{:hanyu "活动", :pinyin "huo2 dong4", :usage-count 1},
{:hanyu "火车", :pinyin "huo3 che1", :usage-count 1},
{:hanyu "火车站", :pinyin "huo3 che1 zhan4", :usage-count 1},
{:hanyu "或许", :pinyin "huo4 xu3", :usage-count 1},
{:hanyu "或者", :pinyin "huo4 zhe3", :usage-count 1},
{:hanyu "机", :pinyin "ji1", :usage-count 1},
{:hanyu "机", :pinyin "Ji1", :usage-count 1},
{:hanyu "机场", :pinyin "ji1 chang3", :usage-count 1},
{:hanyu "鸡蛋", :pinyin "ji1 dan4", :usage-count 1},
{:hanyu "鸡肉", :pinyin "ji1 rou4", :usage-count 1},
{:hanyu "即", :pinyin "ji2", :usage-count 1},
{:hanyu "极", :pinyin "ji2", :usage-count 1},
{:hanyu "即将", :pinyin "ji2 jiang1", :usage-count 1},
{:hanyu "即使", :pinyin "ji2 shi3", :usage-count 1},
{:hanyu "几", :pinyin "ji3", :usage-count 1},
{:hanyu "几天", :pinyin "ji3 tian1", :usage-count 1},
{:hanyu "寄", :pinyin "ji4", :usage-count 1},
{:hanyu "记得", :pinyin "ji4 de5", :usage-count 1},
{:hanyu "计划", :pinyin "ji4 hua4", :usage-count 5},
{:hanyu "季节", :pinyin "ji4 jie2", :usage-count 1},
{:hanyu "计算", :pinyin "ji4 suan4", :usage-count 1},
{:hanyu "计算机", :pinyin "ji4 suan4 ji1", :usage-count 1},
{:hanyu "继续", :pinyin "ji4 xu4", :usage-count 1},
{:hanyu "家", :pinyin "jia1", :usage-count 1},
{:hanyu "家", :pinyin "Jia1", :usage-count 1},
{:hanyu "嘉定", :pinyin "Jia1 ding4", :usage-count 1},
{:hanyu "家人", :pinyin "jia1 ren2", :usage-count 1},
{:hanyu "家庭", :pinyin "jia1 ting2", :usage-count 1},
{:hanyu "价格", :pinyin "jia4 ge2", :usage-count 1},
{:hanyu "间", :pinyin "jian1", :usage-count 1},
{:hanyu "坚持", :pinyin "jian1 chi2", :usage-count 1},
{:hanyu "监狱", :pinyin "jian1 yu4", :usage-count 1},
{:hanyu "兼职", :pinyin "jian1 zhi2", :usage-count 1},
{:hanyu "检查", :pinyin "jian3 cha2", :usage-count 1},
{:hanyu "减肥", :pinyin "jian3 fei2", :usage-count 1},
{:hanyu "减少", :pinyin "jian3 shao3", :usage-count 1},
{:hanyu "见", :pinyin "jian4", :usage-count 1},
{:hanyu "见面", :pinyin "jian4 mian4", :usage-count 1},
{:hanyu "将", :pinyin "jiang1", :usage-count 1},
{:hanyu "江北", :pinyin "Jiang1 bei3", :usage-count 1},
{:hanyu "降", :pinyin "jiang4", :usage-count 1},
{:hanyu "交叉", :pinyin "jiao1 cha1", :usage-count 1},
{:hanyu "交叉口", :pinyin "jiao1 cha1 kou3", :usage-count 1},
{:hanyu "交流", :pinyin "jiao1 liu2", :usage-count 1},
{:hanyu "郊区", :pinyin "jiao1 qu1", :usage-count 1},
{:hanyu "叫", :pinyin "jiao4", :usage-count 1},
{:hanyu "教", :pinyin "jiao4", :usage-count 1},
{:hanyu "教", :pinyin "Jiao4", :usage-count 1},
{:hanyu "教室", :pinyin "jiao4 shi4", :usage-count 1},
{:hanyu "教育", :pinyin "jiao4 yu4", :usage-count 1},
{:hanyu "接", :pinyin "jie1", :usage-count 2},
{:hanyu "接受", :pinyin "jie1 shou4", :short-english "receive", :known false, :usage-count 1},
{:hanyu "节", :pinyin "jie2", :usage-count 1},
{:hanyu "结果", :pinyin "jie2 guo3", :usage-count 1},
{:hanyu "结婚", :pinyin "jie2 hun1", :usage-count 1},
{:hanyu "结束", :pinyin "jie2 shu4", :usage-count 1},
{:hanyu "解答", :pinyin "jie3 da2", :usage-count 1},
{:hanyu "解决", :pinyin "jie3 jue2", :usage-count 1},
{:hanyu "介绍", :pinyin "jie4 shao4", :usage-count 1},
{:hanyu "今", :pinyin "jin1", :usage-count 1},
{:hanyu "金", :pinyin "jin1", :usage-count 1},
{:hanyu "金", :pinyin "Jin1", :usage-count 1},
{:hanyu "今年", :pinyin "jin1 nian2", :usage-count 1},
{:hanyu "金钱", :pinyin "jin1 qian2", :usage-count 1},
{:known true, :hanyu "今天", :pinyin "jin1 tian1", :usage-count 3},
{:hanyu "仅仅", :pinyin "jin3 jin3", :usage-count 1},
{:hanyu "尽量", :pinyin "jin3 liang4", :usage-count 1},
{:hanyu "紧张", :pinyin "jin3 zhang1", :usage-count 1},
{:hanyu "劲", :pinyin "jin4", :usage-count 1},
{:hanyu "近", :pinyin "jin4", :usage-count 1},
{:hanyu "进", :pinyin "jin4", :usage-count 2},
{:hanyu "进步", :pinyin "jin4 bu4", :usage-count 1},
{:hanyu "进城", :pinyin "jin4 cheng2", :usage-count 1},
{:hanyu "进去", :pinyin "jin4 qu4", :usage-count 1},
{:hanyu "进入", :pinyin "jin4 ru4", :usage-count 1},
{:hanyu "经常", :pinyin "jing1 chang2", :usage-count 1},
{:hanyu "惊讶", :pinyin "jing1 ya4", :usage-count 1},
{:hanyu "久", :pinyin "jiu3", :usage-count 1},
{:hanyu "九", :pinyin "jiu3", :usage-count 1},
{:hanyu "酒", :pinyin "jiu3", :usage-count 1},
{:hanyu "酒吧", :pinyin "jiu3 ba1", :usage-count 2},
{:hanyu "酒店", :pinyin "jiu3 dian4", :usage-count 1},
{:hanyu "就", :pinyin "jiu4", :usage-count 1},
{:hanyu "就是", :pinyin "jiu4 shi4", :usage-count 1},
{:hanyu "距离", :pinyin "ju4 li2", :usage-count 1},
{:hanyu "觉", :pinyin "jue2", :usage-count 1},
{:hanyu "觉得", :pinyin "jue2 de5", :usage-count 1},
{:hanyu "军队", :pinyin "jun1 dui4", :usage-count 1},
{:known true, :hanyu "咖啡", :pinyin "ka1 fei1", :usage-count 1},
{:hanyu "卡", :pinyin "ka3", :usage-count 1},
{:hanyu "开", :pinyin "kai1", :usage-count 1},
{:hanyu "开车", :pinyin "kai1 che1", :usage-count 1},
{:hanyu "开会", :pinyin "kai1 hui4", :usage-count 1},
{:hanyu "开口", :pinyin "kai1 kou3", :usage-count 1},
{:hanyu "开始", :pinyin "kai1 shi3", :usage-count 1},
{:hanyu "开心", :pinyin "kai1 xin1", :usage-count 2},
{:hanyu "开学", :pinyin "kai1 xue2", :usage-count 1},
{:known true, :short-english "to see", :hanyu "看", :pinyin "kan4", :usage-count 4},
{:hanyu "看见", :pinyin "kan4 jian4", :usage-count 1},
{:hanyu "看看", :pinyin "kan4 kan5", :usage-count 1},
{:hanyu "看起来", :pinyin "kan4 qi3 lai2", :usage-count 1},
{:hanyu "考试", :pinyin "kao3 shi4", :usage-count 1},
{:hanyu "科卿", :pinyin "Ke1 qing1", :usage-count 1},
{:hanyu "可", :pinyin "ke3", :usage-count 1},
{:hanyu "可爱", :pinyin "ke3 ai4", :usage-count 1},
{:hanyu "可悲", :pinyin "ke3 bei1", :usage-count 1},
{:hanyu "可怜", :pinyin "ke3 lian2", :usage-count 1},
{:hanyu "可能", :pinyin "ke3 neng2", :usage-count 1},
{:hanyu "可是", :pinyin "ke3 shi4", :usage-count 1},
{:hanyu "可以", :pinyin "ke3 yi3", :usage-count 4},
{:hanyu "课", :pinyin "ke4", :usage-count 1},
{:hanyu "客气", :pinyin "ke4 qi5", :usage-count 2},
{:hanyu "课堂", :pinyin "ke4 tang2", :usage-count 1},
{:hanyu "课题", :pinyin "ke4 ti2", :usage-count 1},
{:hanyu "肯定", :pinyin "ken3 ding4", :usage-count 1},
{:hanyu "空间", :pinyin "kong1 jian1", :usage-count 1},
{:hanyu "空调", :pinyin "kong1 tiao2", :usage-count 1},
{:hanyu "空", :pinyin "kong4", :usage-count 1},
{:hanyu "空闲", :pinyin "kong4 xian2", :usage-count 1},
{:hanyu "口", :pinyin "kou3", :usage-count 1},
{:hanyu "哭", :pinyin "ku1", :usage-count 1},
{:short-english "piece", :hanyu "块", :pinyin "kuai4", :usage-count 1},
{:hanyu "快", :pinyin "kuai4", :usage-count 1},
{:hanyu "快点", :pinyin "kuai4 dian3", :usage-count 1},
{:hanyu "快捷", :pinyin "kuai4 jie2", :usage-count 1},
{:hanyu "快乐", :pinyin "kuai4 le4", :usage-count 1},
{:hanyu "矿泉水", :pinyin "kuang4 quan2 shui3", :usage-count 1},
{:hanyu "困", :pinyin "kun4", :usage-count 1},
{:hanyu "困难", :pinyin "kun4 nan5", :usage-count 2},
{:hanyu "拉面", :pinyin "la1 mian4", :usage-count 1},
{:known true, :short-english "to come", :hanyu "来", :pinyin "lai2", :usage-count 12},
{:hanyu "来临", :pinyin "lai2 lin2", :usage-count 1},
{:hanyu "狼", :pinyin "lang2", :usage-count 1},
{:hanyu "老", :pinyin "lao3", :usage-count 1},
{:hanyu "老人", :pinyin "lao3 ren2", :usage-count 1},
{:hanyu "老师", :pinyin "lao3 shi1", :usage-count 3},
{:hanyu "乐", :pinyin "le4", :usage-count 1},
{:hanyu "乐", :pinyin "Le4", :usage-count 1},
{:known true, :short-english "(past)", :hanyu "了", :pinyin "le5", :usage-count 13},
{:hanyu "累", :pinyin "lei4", :usage-count 1},
{:hanyu "类似", :pinyin "lei4 si4", :usage-count 1},
{:hanyu "冷", :pinyin "leng3", :usage-count 3},
{:hanyu "冷", :pinyin "Leng3", :usage-count 1},
{:hanyu "离", :pinyin "li2", :usage-count 1},
{:hanyu "离", :pinyin "Li2", :usage-count 1},
{:hanyu "离婚", :pinyin "li2 hun1", :usage-count 1},
{:hanyu "离开", :pinyin "li2 kai1", :usage-count 1},
{:hanyu "里", :pinyin "li3", :usage-count 2},
{:hanyu "理解", :pinyin "li3 jie3", :usage-count 1},
{:hanyu "礼貌", :pinyin "li3 mao4", :usage-count 1},
{:hanyu "里面", :pinyin "li3 mian4", :usage-count 1},
{:hanyu "礼物", :pinyin "li3 wu4", :usage-count 1},
{:hanyu "理由", :pinyin "li3 you2", :usage-count 1},
{:hanyu "力", :pinyin "li4", :usage-count 1},
{:hanyu "力", :pinyin "Li4", :usage-count 1},
{:hanyu "丽丽", :pinyin "Li4 li4", :usage-count 1},
{:hanyu "例如", :pinyin "li4 ru2", :usage-count 1},
{:hanyu "连接", :pinyin "lian2 jie1", :usage-count 1},
{:hanyu "连锁", :pinyin "lian2 suo3", :usage-count 1},
{:hanyu "联网", :pinyin "lian2 wang3", :usage-count 1},
{:hanyu "联系", :pinyin "lian2 xi4", :usage-count 1},
{:hanyu "帘子", :pinyin "lian2 zi5", :usage-count 1},
{:hanyu "脸", :pinyin "lian3", :usage-count 1},
{:hanyu "练习", :pinyin "lian4 xi2", :usage-count 1},
{:hanyu "凉", :pinyin "liang2", :usage-count 1},
{:hanyu "凉", :pinyin "Liang2", :usage-count 1},
{:hanyu "两", :pinyin "liang3", :usage-count 1},
{:hanyu "辆", :pinyin "liang4", :usage-count 1},
{:hanyu "量", :pinyin "liang4", :usage-count 1},
{:hanyu "聊", :pinyin "liao2", :usage-count 1},
{:hanyu "聊天", :pinyin "liao2 tian1", :usage-count 5},
{:hanyu "了解", :pinyin "liao3 jie3", :usage-count 1},
{:hanyu "林", :pinyin "lin2", :usage-count 1},
{:hanyu "林", :pinyin "Lin2", :usage-count 1},
{:hanyu "淋浴", :pinyin "lin2 yu4", :usage-count 1},
{:hanyu "领养", :pinyin "ling3 yang3", :usage-count 1},
{:hanyu "另外", :pinyin "ling4 wai4", :usage-count 1},
{:hanyu "留", :pinyin "liu2", :usage-count 1},
{:hanyu "刘", :pinyin "Liu2", :usage-count 1},
{:hanyu "流感", :pinyin "liu2 gan3", :usage-count 1},
{:hanyu "流行", :pinyin "liu2 xing2", :usage-count 1},
{:hanyu "留言", :pinyin "liu2 yan2", :usage-count 1},
{:hanyu "六", :pinyin "liu4", :usage-count 1},
{:hanyu "龙", :pinyin "long2", :usage-count 1},
{:hanyu "龙", :pinyin "Long2", :usage-count 1},
{:hanyu "楼", :pinyin "lou2", :usage-count 1},
{:hanyu "旅游", :pinyin "lu:3 you2", :usage-count 1},
{:hanyu "路", :pinyin "lu4", :usage-count 1},
{:hanyu "露", :pinyin "lu4", :usage-count 1},
{:hanyu "路", :pinyin "Lu4", :usage-count 1},
{:hanyu "露", :pinyin "Lu4", :usage-count 1},
{:hanyu "路费", :pinyin "lu4 fei4", :usage-count 1},
{:hanyu "路线", :pinyin "lu4 xian4", :usage-count 1},
{:hanyu "罗伯特", :pinyin "Luo2 bo2 te4", :usage-count 1},
{:hanyu "落魄", :pinyin "luo4 po4", :usage-count 1},
{:hanyu "妈妈", :pinyin "ma1 ma5", :usage-count 4},
{:hanyu "麻烦", :pinyin "ma2 fan5", :usage-count 1},
{:hanyu "马路", :pinyin "ma3 lu4", :usage-count 1},
{:hanyu "马上", :pinyin "ma3 shang4", :usage-count 1},
{:hanyu "骂人", :pinyin "ma4 ren2", :usage-count 1},
{:hanyu "么", :pinyin "ma5", :usage-count 1},
{:short-english "(?)", :hanyu "吗", :pinyin "ma5", :usage-count 15},
{:hanyu "买", :pinyin "mai3", :usage-count 2},
{:hanyu "买卖", :pinyin "mai3 mai4", :usage-count 1},
{:hanyu "卖", :pinyin "mai4", :usage-count 1},
{:hanyu "麦克", :pinyin "mai4 ke4", :usage-count 1},
{:hanyu "麦克", :pinyin "Mai4 ke4", :usage-count 1},
{:hanyu "慢", :pinyin "man4", :usage-count 1},
{:hanyu "忙", :pinyin "mang2", :usage-count 5},
{:hanyu "忙碌", :pinyin "mang2 lu4", :usage-count 1},
{:hanyu "猫", :pinyin "mao1", :usage-count 1},
{:hanyu "冒险", :pinyin "mao4 xian3", :usage-count 1},
{:short-english "(negative)", :hanyu "没", :pinyin "mei2", :usage-count 1},
{:hanyu "没办法", :pinyin "mei2 ban4 fa3", :usage-count 2},
{:hanyu "没错", :pinyin "mei2 cuo4", :usage-count 1},
{:hanyu "没事", :pinyin "mei2 shi4", :usage-count 1},
{:hanyu "没问题", :pinyin "mei2 wen4 ti2", :usage-count 1},
{:hanyu "没有", :pinyin "mei2 you3", :usage-count 3},
{:hanyu "每", :pinyin "mei3", :usage-count 1},
{:hanyu "美", :pinyin "mei3", :usage-count 1},
{:hanyu "美", :pinyin "Mei3", :usage-count 1},
{:hanyu "美国", :pinyin "Mei3 guo2", :usage-count 1},
{:hanyu "美好", :pinyin "mei3 hao3", :usage-count 1},
{:hanyu "美丽", :pinyin "mei3 li4", :usage-count 1},
{:hanyu "每天", :pinyin "mei3 tian1", :usage-count 1},
{:hanyu "妹妹", :pinyin "mei4 mei5", :usage-count 1},
{:hanyu "门", :pinyin "men2", :usage-count 1},
{:hanyu "门", :pinyin "Men2", :usage-count 1},
{:hanyu "门口", :pinyin "men2 kou3", :usage-count 1},
{:hanyu "们", :pinyin "men5", :usage-count 1},
{:hanyu "迷人", :pinyin "mi2 ren2", :usage-count 1},
{:hanyu "秘密", :pinyin "mi4 mi4", :usage-count 1},
{:hanyu "免费", :pinyin "mian3 fei4", :usage-count 1},
{:hanyu "描述", :pinyin "miao2 shu4", :usage-count 1},
{:hanyu "庙", :pinyin "miao4", :usage-count 1},
{:hanyu "明", :pinyin "ming2", :usage-count 1},
{:hanyu "明", :pinyin "Ming2", :usage-count 1},
{:short-english "understand", :hanyu "明白", :pinyin "ming2 bai5", :known true, :usage-count 10},
{:hanyu "明年", :pinyin "ming2 nian2", :usage-count 1},
{:hanyu "明天", :pinyin "ming2 tian1", :usage-count 1},
{:hanyu "磨", :pinyin "mo2", :usage-count 1},
{:hanyu "末", :pinyin "mo4", :usage-count 1},
{:hanyu "木", :pinyin "mu4", :usage-count 1},
{:hanyu "木", :pinyin "Mu4", :usage-count 1},
{:hanyu "拿", :pinyin "na2", :usage-count 1},
{:hanyu "哪", :pinyin "na3", :usage-count 1},
{:hanyu "哪个", :pinyin "na3 ge5", :usage-count 1},
{:hanyu "哪里", :pinyin "na3 li3", :usage-count 1},
{:hanyu "那", :pinyin "na4", :usage-count 1},
{:hanyu "那里", :pinyin "na4 li5", :usage-count 1},
{:hanyu "那么", :pinyin "na4 me5", :usage-count 2},
{:hanyu "南", :pinyin "nan2", :usage-count 1},
{:hanyu "难", :pinyin "nan2", :usage-count 1},
{:hanyu "南", :pinyin "Nan2", :usage-count 1},
{:hanyu "难道", :pinyin "nan2 dao4", :usage-count 1},
{:hanyu "难过", :pinyin "nan2 guo4", :usage-count 3},
{:hanyu "男孩", :pinyin "nan2 hai2", :usage-count 1},
{:hanyu "男朋友", :pinyin "nan2 peng2 you5", :usage-count 1},
{:hanyu "男人", :pinyin "nan2 ren2", :usage-count 1},
{:hanyu "难受", :pinyin "nan2 shou4", :usage-count 1},
{:hanyu "南阳", :pinyin "Nan2 yang2", :usage-count 1},
{:hanyu "男友", :pinyin "nan2 you3", :usage-count 1},
{:short-english "(emphasize)", :hanyu "呢", :pinyin "ne5", :usage-count 2},
{:hanyu "内", :pinyin "nei4", :usage-count 1},
{:hanyu "内心", :pinyin "nei4 xin1", :usage-count 1},
{:short-english "be able", :hanyu "能", :pinyin "neng2", :usage-count 5},
{:hanyu "能", :pinyin "Neng2", :usage-count 1},
{:known true, :hanyu "你", :pinyin "ni3", :usage-count 94},
{:hanyu "你等", :pinyin "ni3 deng3", :usage-count 1},
{:hanyu "你好", :pinyin "ni3 hao3", :usage-count 5},
{:hanyu "你们", :pinyin "ni3 men5", :usage-count 1},
{:hanyu "年", :pinyin "nian2", :usage-count 1},
{:hanyu "年", :pinyin "Nian2", :usage-count 1},
{:hanyu "念", :pinyin "nian4", :usage-count 1},
{:hanyu "鸟", :pinyin "niao3", :usage-count 1},
{:hanyu "您", :pinyin "nin2", :usage-count 1},
{:hanyu "牛", :pinyin "niu2", :usage-count 1},
{:hanyu "牛", :pinyin "Niu2", :usage-count 1},
{:hanyu "牛奶", :pinyin "niu2 nai3", :usage-count 1},
{:hanyu "牛肉", :pinyin "niu2 rou4", :usage-count 1},
{:hanyu "浓", :pinyin "nong2", :usage-count 1},
{:hanyu "农村", :pinyin "nong2 cun1", :usage-count 1},
{:hanyu "浓度", :pinyin "nong2 du4", :usage-count 1},
{:hanyu "弄", :pinyin "nong4", :usage-count 1},
{:hanyu "女朋友", :pinyin "nu:3 peng2 you5", :usage-count 2},
{:hanyu "女友", :pinyin "nu:3 you3", :usage-count 1},
{:hanyu "努力", :pinyin "nu3 li4", :usage-count 8},
{:hanyu "暖暖", :pinyin "Nuan3 nuan3", :usage-count 1},
{:hanyu "诺基亚", :pinyin "Nuo4 ji1 ya4", :usage-count 1},
{:hanyu "哦", :pinyin "o2", :usage-count 1},
{:hanyu "欧元", :pinyin "Ou1 yuan2", :usage-count 2},
{:short-english "afraid", :hanyu "怕", :pinyin "pa4", :usage-count 2},
{:hanyu "怕", :pinyin "Pa4", :usage-count 1},
{:hanyu "拍", :pinyin "pai1", :usage-count 1},
{:hanyu "拍摄", :pinyin "pai1 she4", :usage-count 1},
{:hanyu "旁边", :pinyin "pang2 bian1", :usage-count 1},
{:hanyu "胖", :pinyin "pang4", :usage-count 1},
{:hanyu "陪", :pinyin "pei2", :usage-count 1},
{:known true, :short-english "friend", :hanyu "朋友", :pinyin "peng2 you5", :usage-count 2},
{:hanyu "疲惫", :pinyin "pi2 bei4", :usage-count 1},
{:hanyu "啤酒", :pinyin "pi2 jiu3", :usage-count 1},
{:hanyu "便宜", :pinyin "pian2 yi5", :usage-count 1},
{:hanyu "票", :pinyin "piao4", :usage-count 1},
{:hanyu "漂亮", :pinyin "piao4 liang5", :usage-count 2},
{:hanyu "平板", :pinyin "ping2 ban3", :usage-count 1},
{:hanyu "苹果", :pinyin "ping2 guo3", :usage-count 1},
{:hanyu "平原", :pinyin "ping2 yuan2", :usage-count 1},
{:hanyu "七", :pinyin "qi1", :usage-count 1},
{:hanyu "妻子", :pinyin "qi1 zi5", :usage-count 1},
{:hanyu "其实", :pinyin "qi2 shi2", :usage-count 1},
{:hanyu "其它", :pinyin "qi2 ta1", :usage-count 1},
{:hanyu "起", :pinyin "qi3", :usage-count 1},
{:hanyu "汽", :pinyin "qi4", :usage-count 1},
{:hanyu "汽车", :pinyin "qi4 che1", :usage-count 1},
{:hanyu "汽水", :pinyin "qi4 shui3", :usage-count 1},
{:hanyu "千", :pinyin "qian1", :usage-count 1},
{:hanyu "签证", :pinyin "qian1 zheng4", :usage-count 2},
{:hanyu "前", :pinyin "qian2", :usage-count 1},
{:hanyu "钱", :pinyin "qian2", :usage-count 3},
{:hanyu "钱", :pinyin "Qian2", :usage-count 1},
{:hanyu "前边", :pinyin "qian2 bian5", :usage-count 1},
{:hanyu "强健", :pinyin "qiang2 jian4", :usage-count 1},
{:hanyu "抢劫", :pinyin "qiang3 jie2", :usage-count 1},
{:hanyu "巧克力", :pinyin "qiao3 ke4 li4", :usage-count 1},
{:hanyu "亲吻", :pinyin "qin1 wen3", :usage-count 1},
{:hanyu "请", :pinyin "qing3", :usage-count 6},
{:hanyu "请问", :pinyin "qing3 wen4", :usage-count 1},
{:hanyu "庆", :pinyin "qing4", :usage-count 1},
{:hanyu "庆典", :pinyin "qing4 dian3", :usage-count 1},
{:hanyu "秋天", :pinyin "qiu1 tian1", :usage-count 1},
{:hanyu "区", :pinyin "qu1", :usage-count 1},
{:known true, :short-english "go", :hanyu "去", :pinyin "qu4", :usage-count 12},
{:hanyu "确定", :pinyin "que4 ding4", :usage-count 1},
{:hanyu "然后", :pinyin "ran2 hou4", :usage-count 1},
{:hanyu "让", :pinyin "rang4", :usage-count 1},
{:hanyu "热", :pinyin "re4", :usage-count 1},
{:hanyu "人", :pinyin "ren2", :usage-count 1},
{:hanyu "人民", :pinyin "ren2 min2", :usage-count 1},
{:hanyu "人民币", :pinyin "ren2 min2 bi4", :usage-count 1},
{:hanyu "人生", :pinyin "ren2 sheng1", :usage-count 1},
{:hanyu "人士", :pinyin "ren2 shi4", :usage-count 1},
{:hanyu "忍耐", :pinyin "ren3 nai4", :usage-count 1},
{:hanyu "任何", :pinyin "ren4 he2", :usage-count 1},
{:hanyu "认为", :pinyin "ren4 wei2", :usage-count 2},
{:hanyu "认真", :pinyin "ren4 zhen1", :usage-count 1},
{:hanyu "日", :pinyin "ri4", :usage-count 1},
{:hanyu "日本", :pinyin "Ri4 ben3", :usage-count 1},
{:hanyu "容易", :pinyin "rong2 yi4", :usage-count 1},
{:hanyu "肉", :pinyin "rou4", :usage-count 1},
{:hanyu "如", :pinyin "ru2", :usage-count 1},
{:hanyu "如果", :pinyin "ru2 guo3", :usage-count 3},
{:hanyu "如何", :pinyin "ru2 he2", :usage-count 1},
{:hanyu "入睡", :pinyin "ru4 shui4", :usage-count 1},
{:hanyu "软件", :pinyin "ruan3 jian4", :usage-count 2},
{:hanyu "软件开发人员", :pinyin "ruan3 jian4 kai1 fa1 ren2 yuan2", :usage-count 1},
{:hanyu "撒谎", :pinyin "sa1 huang3", :usage-count 1},
{:known true, :short-english "three", :hanyu "三", :pinyin "san1", :usage-count 3},
{:hanyu "毵", :pinyin "san1", :usage-count 1},
{:hanyu "三", :pinyin "San1", :usage-count 1},
{:hanyu "桑拿", :pinyin "sang1 na2", :usage-count 1},
{:hanyu "色", :pinyin "se4", :usage-count 1},
{:hanyu "傻", :pinyin "sha3", :usage-count 1},
{:hanyu "厦", :pinyin "sha4", :usage-count 1},
{:hanyu "删掉", :pinyin "shan1 diao4", :usage-count 1},
{:hanyu "善", :pinyin "shan4", :usage-count 1},
{:hanyu "善良", :pinyin "shan4 liang2", :usage-count 1},
{:hanyu "伤", :pinyin "shang1", :usage-count 1},
{:hanyu "商场", :pinyin "shang1 chang3", :usage-count 1},
{:hanyu "商店", :pinyin "shang1 dian4", :usage-count 1},
{:hanyu "伤害", :pinyin "shang1 hai4", :usage-count 1},
{:hanyu "伤心", :pinyin "shang1 xin1", :usage-count 1},
{:hanyu "上", :pinyin "shang4", :usage-count 1},
{:hanyu "上传", :pinyin "shang4 chuan2", :usage-count 1},
{:known true, :short-english "Shanghai", :hanyu "上海", :pinyin "Shang4 hai3", :usage-count 3},
{:hanyu "上课", :pinyin "shang4 ke4", :usage-count 1},
{:hanyu "上去", :pinyin "shang4 qu4", :usage-count 1},
{:hanyu "上天", :pinyin "shang4 tian1", :usage-count 1},
{:hanyu "上网", :pinyin "shang4 wang3", :usage-count 1},
{:hanyu "上线", :pinyin "shang4 xian4", :usage-count 1},
{:hanyu "上星期", :pinyin "shang4 xing1 qi1", :usage-count 1},
{:hanyu "稍", :pinyin "shao1", :usage-count 1},
{:hanyu "少", :pinyin "shao3", :usage-count 2},
{:hanyu "舍得", :pinyin "she3 de5", :usage-count 1},
{:hanyu "摄", :pinyin "she4", :usage-count 1},
{:hanyu "设计", :pinyin "she4 ji4", :usage-count 1},
{:hanyu "社团", :pinyin "she4 tuan2", :usage-count 1},
{:hanyu "深", :pinyin "shen1", :usage-count 1},
{:hanyu "身边", :pinyin "shen1 bian1", :usage-count 1},
{:hanyu "身材", :pinyin "shen1 cai2", :usage-count 1},
{:hanyu "身份", :pinyin "shen1 fen4", :usage-count 1},
{:hanyu "身份证", :pinyin "shen1 fen4 zheng4", :usage-count 1},
{:hanyu "身上", :pinyin "shen1 shang5", :usage-count 1},
{:hanyu "身体", :pinyin "shen1 ti3", :usage-count 1},
{:hanyu "深夜", :pinyin "shen1 ye4", :usage-count 1},
{:known true, :hanyu "什么", :pinyin "shen2 me5", :usage-count 7},
{:hanyu "甚至", :pinyin "shen4 zhi4", :usage-count 1},
{:hanyu "声", :pinyin "sheng1", :usage-count 1},
{:hanyu "生", :pinyin "sheng1", :usage-count 1},
{:hanyu "生病", :pinyin "sheng1 bing4", :usage-count 1},
{:hanyu "生日", :pinyin "sheng1 ri4", :usage-count 1},
{:hanyu "声音", :pinyin "sheng1 yin1", :usage-count 1},
{:hanyu "圣诞节", :pinyin "Sheng4 dan4 jie2", :usage-count 1},
{:hanyu "圣诞树", :pinyin "Sheng4 dan4 shu4", :usage-count 1},
{:hanyu "胜利", :pinyin "sheng4 li4", :usage-count 1},
{:hanyu "剩下", :pinyin "sheng4 xia4", :usage-count 1},
{:hanyu "失败", :pinyin "shi1 bai4", :usage-count 1},
{:hanyu "失眠", :pinyin "shi1 mian2", :usage-count 1},
{:hanyu "失望", :pinyin "shi1 wang4", :usage-count 1},
{:hanyu "失误", :pinyin "shi1 wu4", :usage-count 1},
{:known true, :hanyu "十", :pinyin "shi2", :usage-count 1},
{:hanyu "时", :pinyin "shi2", :usage-count 1},
{:hanyu "时", :pinyin "Shi2", :usage-count 1},
{:hanyu "时常", :pinyin "shi2 chang2", :usage-count 1},
{:hanyu "时光", :pinyin "shi2 guang1", :usage-count 1},
{:known true, :hanyu "时候", :pinyin "shi2 hou5", :usage-count 3},
{:hanyu "时间", :pinyin "shi2 jian1", :usage-count 2},
{:hanyu "实在", :pinyin "shi2 zai4", :usage-count 1},
{:hanyu "使", :pinyin "shi3", :usage-count 1},
{:hanyu "使用", :pinyin "shi3 yong4", :usage-count 1},
{:hanyu "市", :pinyin "shi4", :usage-count 1},
{:known true, :hanyu "是", :pinyin "shi4", :usage-count 5},
{:hanyu "试", :pinyin "shi4", :usage-count 1},
{:hanyu "市场", :pinyin "shi4 chang3", :usage-count 1},
{:hanyu "是的", :pinyin "shi4 de5", :usage-count 1},
{:hanyu "是否", :pinyin "shi4 fou3", :usage-count 1},
{:hanyu "世界", :pinyin "shi4 jie4", :usage-count 1},
{:hanyu "室内", :pinyin "shi4 nei4", :usage-count 1},
{:hanyu "视频", :pinyin "shi4 pin2", :usage-count 1},
{:hanyu "收到", :pinyin "shou1 dao4", :usage-count 1},
{:hanyu "收费", :pinyin "shou1 fei4", :usage-count 1},
{:hanyu "手机", :pinyin "shou3 ji1", :usage-count 5},
{:hanyu "瘦", :pinyin "shou4", :usage-count 1},
{:hanyu "瘦子", :pinyin "shou4 zi5", :usage-count 1},
{:hanyu "书", :pinyin "shu1", :usage-count 1},
{:hanyu "书", :pinyin "Shu1", :usage-count 1},
{:hanyu "蔬菜", :pinyin "shu1 cai4", :usage-count 1},
{:hanyu "舒服", :pinyin "shu1 fu5", :usage-count 1},
{:hanyu "输液", :pinyin "shu1 ye4", :usage-count 1},
{:hanyu "熟练", :pinyin "shu2 lian4", :usage-count 1},
{:hanyu "数据库", :pinyin "shu4 ju4 ku4", :usage-count 1},
{:hanyu "帅哥", :pinyin "shuai4 ge1", :usage-count 1},
{:hanyu "双", :pinyin "shuang1", :usage-count 1},
{:hanyu "双", :pinyin "Shuang1", :usage-count 1},
{:known true, :hanyu "水", :pinyin "shui3", :usage-count 1},
{:hanyu "水", :pinyin "Shui3", :usage-count 1},
{:hanyu "水果", :pinyin "shui3 guo3", :usage-count 1},
{:hanyu "睡", :pinyin "shui4", :usage-count 1},
{:known true, :hanyu "睡觉", :pinyin "shui4 jiao4", :usage-count 1},
{:hanyu "睡醒", :pinyin "shui4 xing3", :usage-count 1},
{:hanyu "顺风", :pinyin "shun4 feng1", :usage-count 1},
{:known true, :hanyu "说", :pinyin "shuo1", :usage-count 7},
{:hanyu "说话", :pinyin "shuo1 hua4", :usage-count 1},
{:hanyu "思科", :pinyin "Si1 ke1", :usage-count 1},
{:hanyu "私人", :pinyin "si1 ren2", :usage-count 1},
{:hanyu "死", :pinyin "si3", :usage-count 1},
{:hanyu "死板", :pinyin "si3 ban3", :usage-count 1},
{:known true, :hanyu "四", :pinyin "si4", :usage-count 1},
{:hanyu "速", :pinyin "su4", :usage-count 1},
{:hanyu "宿舍", :pinyin "su4 she4", :usage-count 1},
{:hanyu "蒜", :pinyin "suan4", :usage-count 1},
{:hanyu "岁", :pinyin "sui4", :usage-count 1},
{:hanyu "穗", :pinyin "sui4", :usage-count 1},
{:hanyu "穗", :pinyin "Sui4", :usage-count 1},
{:hanyu "所以", :pinyin "suo3 yi3", :usage-count 6},
{:hanyu "他", :pinyin "ta1", :usage-count 1},
{:known true, :short-english "she", :hanyu "她", :pinyin "ta1", :usage-count 11},
{:hanyu "它", :pinyin "ta1", :usage-count 1},
{:hanyu "他妈的", :pinyin "ta1 ma1 de5", :usage-count 1},
{:hanyu "他们", :pinyin "ta1 men5", :usage-count 1},
{:hanyu "她们", :pinyin "ta1 men5", :usage-count 1},
{:hanyu "它们", :pinyin "ta1 men5", :usage-count 1},
{:hanyu "太", :pinyin "tai4", :usage-count 2},
{:short-english "Mrs", :hanyu "太太", :pinyin "tai4 tai5", :usage-count 2},
{:hanyu "贪玩", :pinyin "tan1 wan2", :usage-count 1},
{:hanyu "谈谈", :pinyin "tan2 tan2", :usage-count 1},
{:hanyu "探讨", :pinyin "tan4 tao3", :usage-count 1},
{:hanyu "汤", :pinyin "tang1", :usage-count 1},
{:hanyu "汤", :pinyin "Tang1", :usage-count 1},
{:hanyu "糖", :pinyin "tang2", :usage-count 1},
{:hanyu "躺", :pinyin "tang3", :usage-count 1},
{:hanyu "讨厌", :pinyin "tao3 yan4", :usage-count 1},
{:hanyu "疼", :pinyin "teng2", :usage-count 1},
{:hanyu "天", :pinyin "tian1", :usage-count 1},
{:hanyu "天气", :pinyin "tian1 qi4", :usage-count 1},
{:hanyu "甜", :pinyin "tian2", :usage-count 1},
{:hanyu "甜点", :pinyin "tian2 dian3", :usage-count 1},
{:hanyu "条", :pinyin "tiao2", :usage-count 1},
{:hanyu "调", :pinyin "tiao2", :usage-count 1},
{:hanyu "调整", :pinyin "tiao2 zheng3", :usage-count 1},
{:hanyu "跳", :pinyin "tiao4", :usage-count 1},
{:hanyu "跳舞", :pinyin "tiao4 wu3", :usage-count 1},
{:hanyu "听", :pinyin "ting1", :usage-count 3},
{:hanyu "通常", :pinyin "tong1 chang2", :usage-count 1},
{:hanyu "同僚", :pinyin "tong2 liao2", :usage-count 2},
{:hanyu "同事", :pinyin "tong2 shi4", :usage-count 2},
{:hanyu "同学", :pinyin "tong2 xue2", :usage-count 1},
{:hanyu "同意", :pinyin "tong2 yi4", :usage-count 1},
{:hanyu "痛", :pinyin "tong4", :usage-count 1},
{:hanyu "偷偷", :pinyin "tou1 tou1", :usage-count 1},
{:hanyu "头", :pinyin "tou2", :usage-count 1},
{:short-english "hair", :hanyu "头发", :pinyin "tou2 fa5", :usage-count 1},
{:hanyu "头巾", :pinyin "tou2 jin1", :usage-count 1},
{:hanyu "头疼", :pinyin "tou2 teng2", :usage-count 1},
{:hanyu "头痛", :pinyin "tou2 tong4", :usage-count 1},
{:hanyu "图", :pinyin "tu2", :usage-count 1},
{:hanyu "图书馆", :pinyin "tu2 shu1 guan3", :usage-count 1},
{:hanyu "图像", :pinyin "tu2 xiang4", :usage-count 1},
{:hanyu "兔子", :pinyin "tu4 zi5", :usage-count 1},
{:hanyu "团", :pinyin "tuan2", :usage-count 1},
{:hanyu "推", :pinyin "tui1", :usage-count 1},
{:hanyu "哇", :pinyin "wa5", :usage-count 1},
{:hanyu "外地", :pinyin "wai4 di4", :usage-count 1},
{:hanyu "外面", :pinyin "wai4 mian4", :usage-count 1},
{:hanyu "外滩", :pinyin "Wai4 tan1", :usage-count 1},
{:hanyu "完", :pinyin "wan2", :usage-count 1},
{:hanyu "玩", :pinyin "wan2", :usage-count 3},
{:hanyu "完成", :pinyin "wan2 cheng2", :usage-count 1},
{:hanyu "晚", :pinyin "wan3", :usage-count 1},
{:hanyu "晚安", :pinyin "wan3 an1", :usage-count 1},
{:hanyu "晚餐", :pinyin "wan3 can1", :usage-count 1},
{:hanyu "晚晌", :pinyin "wan3 shang3", :usage-count 3},
{:hanyu "往", :pinyin "wang3", :usage-count 1},
{:hanyu "网", :pinyin "wang3", :usage-count 1},
{:hanyu "网吧", :pinyin "wang3 ba1", :usage-count 1},
{:short-english "network", :hanyu "网络", :pinyin "wang3 luo4", :usage-count 1},
{:short-english "internet", :hanyu "网络", :pinyin "Wang3 luo4", :usage-count 1},
{:hanyu "往前", :pinyin "wang3 qian2", :usage-count 1},
{:hanyu "网球", :pinyin "wang3 qiu2", :usage-count 1},
{:hanyu "网上", :pinyin "wang3 shang4", :usage-count 1},
{:hanyu "网页", :pinyin "wang3 ye4", :usage-count 1},
{:hanyu "微", :pinyin "wei1", :usage-count 1},
{:hanyu "微", :pinyin "Wei1", :usage-count 1},
{:hanyu "围巾", :pinyin "wei2 jin1", :usage-count 1},
{:hanyu "为难", :pinyin "wei2 nan2", :usage-count 1},
{:hanyu "为", :pinyin "wei4", :usage-count 1},
{:hanyu "味精", :pinyin "wei4 jing1", :usage-count 1},
{:hanyu "未来", :pinyin "wei4 lai2", :usage-count 1},
{:hanyu "为了", :pinyin "wei4 le5", :usage-count 1},
{:hanyu "为什么", :pinyin "wei4 shen2 me5", :usage-count 5},
{:hanyu "文", :pinyin "wen2", :usage-count 1},
{:hanyu "文", :pinyin "Wen2", :usage-count 1},
{:hanyu "文本", :pinyin "wen2 ben3", :usage-count 1},
{:hanyu "文书处理", :pinyin "wen2 shu1 chu3 li3", :usage-count 1},
{:hanyu "文章", :pinyin "wen2 zhang1", :usage-count 1},
{:hanyu "吻", :pinyin "wen3", :usage-count 1},
{:hanyu "问", :pinyin "wen4", :usage-count 1},
{:hanyu "问题", :pinyin "wen4 ti2", :usage-count 3},
{:known true, :short-english "I", :hanyu "我", :pinyin "wo3", :usage-count 114},
{:known true, :hanyu "我们", :pinyin "wo3 men5", :usage-count 8},
{:hanyu "卧室", :pinyin "wo4 shi4", :usage-count 1},
{:hanyu "污染", :pinyin "wu1 ran3", :usage-count 1},
{:hanyu "无礼", :pinyin "wu2 li3", :usage-count 1},
{:hanyu "无聊", :pinyin "wu2 liao2", :usage-count 1},
{:hanyu "五", :pinyin "wu3", :usage-count 1},
{:hanyu "舞", :pinyin "wu3", :usage-count 1},
{:hanyu "舞会", :pinyin "wu3 hui4", :usage-count 1},
{:hanyu "雾", :pinyin "wu4", :usage-count 1},
{:hanyu "西瓜", :pinyin "xi1 gua1", :usage-count 1},
{:hanyu "西红柿", :pinyin "xi1 hong2 shi4", :usage-count 1},
{:hanyu "希望", :pinyin "xi1 wang4", :usage-count 3},
{:hanyu "习俗", :pinyin "xi2 su2", :usage-count 1},
{:hanyu "喜", :pinyin "xi3", :usage-count 1},
{:hanyu "洗", :pinyin "xi3", :usage-count 1},
{:known true, :short-english "to like", :hanyu "喜欢", :pinyin "xi3 huan5", :usage-count 10},
{:hanyu "洗头", :pinyin "xi3 tou2", :usage-count 1},
{:hanyu "洗澡", :pinyin "xi3 zao3", :usage-count 1},
{:hanyu "阋", :pinyin "xi4", :usage-count 1},
{:hanyu "下", :pinyin "xia4", :usage-count 1},
{:hanyu "下课", :pinyin "xia4 ke4", :usage-count 1},
{:hanyu "夏天", :pinyin "xia4 tian1", :usage-count 3},
{:hanyu "下午", :pinyin "xia4 wu3", :usage-count 1},
{:hanyu "下雪", :pinyin "xia4 xue3", :usage-count 1},
{:hanyu "下雨", :pinyin "xia4 yu3", :usage-count 1},
{:hanyu "下载", :pinyin "xia4 zai3", :usage-count 1},
{:hanyu "先", :pinyin "xian1", :usage-count 1},
{:hanyu "线", :pinyin "xian4", :usage-count 1},
{:hanyu "现在", :pinyin "xian4 zai4", :short-english "now", :known true, :usage-count 12},
{:hanyu "现状", :pinyin "xian4 zhuang4", :usage-count 1},
{:hanyu "相", :pinyin "xiang1", :usage-count 1},
{:hanyu "相", :pinyin "Xiang1", :usage-count 1},
{:hanyu "相处", :pinyin "xiang1 chu3", :usage-count 1},
{:hanyu "香港", :pinyin "Xiang1 gang3", :usage-count 1},
{:hanyu "相互", :pinyin "xiang1 hu4", :usage-count 1},
{:hanyu "相似", :pinyin "xiang1 si4", :usage-count 1},
{:hanyu "想", :pinyin "xiang3", :usage-count 1},
{:hanyu "想到", :pinyin "xiang3 dao4", :usage-count 1},
{:hanyu "想念", :pinyin "xiang3 nian4", :usage-count 1},
{:hanyu "想要", :pinyin "xiang3 yao4", :usage-count 1},
{:hanyu "像", :pinyin "xiang4", :usage-count 1},
{:hanyu "向", :pinyin "xiang4", :usage-count 1},
{:hanyu "相机", :pinyin "xiang4 ji1", :usage-count 1},
{:hanyu "消费", :pinyin "xiao1 fei4", :usage-count 1},
{:hanyu "消息", :pinyin "xiao1 xi5", :usage-count 1},
{:hanyu "小", :pinyin "xiao3", :usage-count 4},
{:hanyu "小时", :pinyin "xiao3 shi2", :usage-count 1},
{:hanyu "笑", :pinyin "xiao4", :usage-count 1},
{:hanyu "校园", :pinyin "xiao4 yuan2", :usage-count 2},
{:hanyu "些", :pinyin "xie1", :usage-count 1},
{:hanyu "写", :pinyin "xie3", :usage-count 11},
{:hanyu "写信", :pinyin "xie3 xin4", :usage-count 1},
{:hanyu "谢", :pinyin "xie4", :usage-count 1},
{:hanyu "谢", :pinyin "Xie4", :usage-count 1},
{:hanyu "谢谢", :pinyin "xie4 xie5", :usage-count 2},
{:hanyu "心", :pinyin "xin1", :usage-count 1},
{:hanyu "新", :pinyin "xin1", :usage-count 1},
{:hanyu "新港", :pinyin "Xin1 gang3", :usage-count 1},
{:hanyu "辛苦", :pinyin "xin1 ku3", :usage-count 1},
{:hanyu "心理", :pinyin "xin1 li3", :usage-count 1},
{:known false, :short-english "heart", :hanyu "心里", :pinyin "xin1 li5"},
{:hanyu "新年", :pinyin "xin1 nian2", :usage-count 1},
{:hanyu "心情", :pinyin "xin1 qing2", :usage-count 1},
{:hanyu "薪水", :pinyin "xin1 shui3", :usage-count 1},
{:hanyu "新闻", :pinyin "xin1 wen2", :usage-count 1},
{:short-english "Xinxiang city", :hanyu "新乡", :pinyin "Xin1 xiang1", :usage-count 1},
{:hanyu "心愿", :pinyin "xin1 yuan4", :usage-count 1},
{:hanyu "新郑", :pinyin "Xin1 zheng4", :usage-count 1},
{:hanyu "信", :pinyin "xin4", :usage-count 1},
{:hanyu "信号", :pinyin "xin4 hao4", :usage-count 1},
{:hanyu "信息", :pinyin "xin4 xi1", :usage-count 1},
{:hanyu "星", :pinyin "xing1", :usage-count 1},
{:hanyu "星期", :pinyin "xing1 qi1", :usage-count 1},
{:hanyu "星期六", :pinyin "Xing1 qi1 liu4", :usage-count 1},
{:hanyu "型", :pinyin "xing2", :usage-count 1},
{:hanyu "行", :pinyin "xing2", :usage-count 3},
{:hanyu "形式", :pinyin "xing2 shi4", :usage-count 1},
{:hanyu "性格", :pinyin "xing4 ge2", :usage-count 1},
{:hanyu "性交", :pinyin "xing4 jiao1", :usage-count 1},
{:hanyu "修复", :pinyin "xiu1 fu4", :usage-count 1},
{:hanyu "修改", :pinyin "xiu1 gai3", :usage-count 1},
{:hanyu "虚拟", :pinyin "xu1 ni3", :usage-count 1},
{:hanyu "需要", :pinyin "xu1 yao4", :usage-count 1},
{:hanyu "学", :pinyin "xue2", :usage-count 5},
{:hanyu "学费", :pinyin "xue2 fei4", :usage-count 1},
{:hanyu "学习", :pinyin "xue2 xi2", :usage-count 4},
{:hanyu "学校", :pinyin "xue2 xiao4", :usage-count 1},
{:hanyu "学院", :pinyin "xue2 yuan4", :usage-count 1},
{:hanyu "雪", :pinyin "xue3", :usage-count 1},
{:hanyu "雪", :pinyin "Xue3", :usage-count 1},
{:hanyu "寻找", :pinyin "xun2 zhao3", :usage-count 1},
{:hanyu "迅速", :pinyin "xun4 su4", :usage-count 1},
{:hanyu "压力", :pinyin "ya1 li4", :usage-count 1},
{:hanyu "烟花", :pinyin "yan1 hua1", :usage-count 1},
{:hanyu "言", :pinyin "yan2", :usage-count 1},
{:hanyu "严格", :pinyin "yan2 ge2", :usage-count 1},
{:hanyu "研究", :pinyin "yan2 jiu1", :usage-count 1},
{:hanyu "颜色", :pinyin "yan2 se4", :usage-count 1},
{:hanyu "严重", :pinyin "yan2 zhong4", :usage-count 1},
{:hanyu "眼镜", :pinyin "yan3 jing4", :usage-count 1},
{:hanyu "眼睛", :pinyin "yan3 jing5", :usage-count 1},
{:hanyu "仰慕", :pinyin "yang3 mu4", :usage-count 1},
{:hanyu "样", :pinyin "yang4", :usage-count 1},
{:hanyu "遥远", :pinyin "yao2 yuan3", :usage-count 1},
{:hanyu "药", :pinyin "yao4", :usage-count 1},
{:known true, :short-english "want", :hanyu "要", :pinyin "yao4", :usage-count 16},
{:hanyu "钥匙", :pinyin "yao4 shi5", :usage-count 1},
{:known true, :short-english "also", :hanyu "也", :pinyin "ye3", :usage-count 5},
{:hanyu "也许", :pinyin "ye3 xu3", :usage-count 2},
{:hanyu "夜", :pinyin "ye4", :usage-count 1},
{:hanyu "叶子", :pinyin "ye4 zi5", :usage-count 1},
{:known true, :hanyu "一", :pinyin "yi1", :usage-count 1},
{:hanyu "一般", :pinyin "yi1 ban1", :usage-count 1},
{:hanyu "一次", :pinyin "yi1 ci4", :usage-count 1},
{:known true, :hanyu "一点", :pinyin "yi1 dian3", :usage-count 2},
{:known true, :hanyu "一点点", :pinyin "yi1 dian3 dian3", :usage-count 1},
{:hanyu "一定", :pinyin "yi1 ding4", :usage-count 1},
{:known true, :hanyu "一个人", :pinyin "yi1 ge4 ren2", :usage-count 1},
{:hanyu "一会儿", :pinyin "yi1 hui4 r5", :usage-count 1},
{:known true, :hanyu "一起", :pinyin "yi1 qi3", :usage-count 3},
{:hanyu "一切", :pinyin "yi1 qie4", :usage-count 1},
{:hanyu "依然", :pinyin "yi1 ran2", :usage-count 1},
{:hanyu "医生", :pinyin "yi1 sheng1", :usage-count 1},
{:hanyu "衣食住行", :pinyin "yi1 shi2 zhu4 xing2", :usage-count 1},
{:hanyu "一些", :pinyin "yi1 xie1", :usage-count 1},
{:hanyu "一样", :pinyin "yi1 yang4", :usage-count 1},
{:hanyu "遗憾", :pinyin "yi2 han4", :usage-count 2},
{:hanyu "姨妈", :pinyin "yi2 ma1", :usage-count 1},
{:hanyu "以后", :pinyin "yi3 hou4", :usage-count 1},
{:hanyu "已经", :pinyin "yi3 jing1", :usage-count 2},
{:hanyu "以前", :pinyin "yi3 qian2", :usage-count 2},
{:hanyu "以外", :pinyin "yi3 wai4", :usage-count 1},
{:hanyu "谊", :pinyin "yi4", :usage-count 1},
{:hanyu "艺术", :pinyin "yi4 shu4", :usage-count 1},
{:hanyu "意思", :pinyin "yi4 si5", :usage-count 1},
{:hanyu "音", :pinyin "yin1", :usage-count 1},
{:known true, :hanyu "因为", :pinyin "yin1 wei4", :usage-count 1},
{:hanyu "音乐", :pinyin "yin1 yue4", :usage-count 3},
{:hanyu "银行", :pinyin "yin2 hang2", :usage-count 1},
{:hanyu "隐形", :pinyin "yin3 xing2", :usage-count 1},
{:hanyu "隐形眼镜", :pinyin "yin3 xing2 yan3 jing4", :usage-count 1},
{:known true, :hanyu "应该", :pinyin "ying1 gai1", :usage-count 13},
{:short-english "United Kingdom", :hanyu "英国", :pinyin "Ying1 guo2", :usage-count 1},
{:hanyu "英语", :pinyin "Ying1 yu3", :usage-count 1},
{:hanyu "影响", :pinyin "ying3 xiang3", :usage-count 1},
{:hanyu "应力", :pinyin "ying4 li4", :usage-count 1},
{:hanyu "永远", :pinyin "yong3 yuan3", :usage-count 1},
{:hanyu "用", :pinyin "yong4", :usage-count 4},
{:hanyu "优秀", :pinyin "you1 xiu4", :usage-count 1},
{:hanyu "邮", :pinyin "you2", :usage-count 1},
{:hanyu "邮件", :pinyin "you2 jian4", :usage-count 1},
{:hanyu "邮局", :pinyin "you2 ju2", :usage-count 1},
{:hanyu "邮票", :pinyin "you2 piao4", :usage-count 1},
{:hanyu "游戏", :pinyin "you2 xi4", :usage-count 1},
{:hanyu "邮箱", :pinyin "you2 xiang1", :usage-count 1},
{:hanyu "游泳", :pinyin "you2 yong3", :usage-count 2},
{:hanyu "由于", :pinyin "you2 yu2", :usage-count 1},
{:known true, :short-english "to have", :hanyu "有", :pinyin "you3", :usage-count 10},
{:hanyu "有趣", :pinyin "you3 qu4", :usage-count 1},
{:hanyu "有人", :pinyin "you3 ren2", :usage-count 1},
{:hanyu "友善", :pinyin "you3 shan4", :usage-count 1},
{:hanyu "有时", :pinyin "you3 shi2", :usage-count 1},
{:hanyu "有事", :pinyin "you3 shi4", :usage-count 1},
{:hanyu "友谊", :pinyin "you3 yi4", :usage-count 1},
{:hanyu "有意思", :pinyin "you3 yi4 si5", :usage-count 1},
{:hanyu "又", :pinyin "you4", :usage-count 1},
{:hanyu "右", :pinyin "you4", :usage-count 1},
{:hanyu "鱼", :pinyin "yu2", :usage-count 1},
{:hanyu "鱼", :pinyin "Yu2", :usage-count 1},
{:hanyu "愉快", :pinyin "yu2 kuai4", :usage-count 1},
{:hanyu "与", :pinyin "yu3", :usage-count 1},
{:hanyu "语", :pinyin "yu3", :usage-count 3},
{:hanyu "雨", :pinyin "yu3", :usage-count 1},
{:hanyu "羽毛球", :pinyin "yu3 mao2 qiu2", :usage-count 1},
{:hanyu "语文", :pinyin "yu3 wen2", :usage-count 1},
{:hanyu "语言", :pinyin "yu3 yan2", :usage-count 1},
{:hanyu "喻", :pinyin "yu4", :usage-count 1},
{:hanyu "浴", :pinyin "yu4", :usage-count 1},
{:hanyu "豫", :pinyin "yu4", :usage-count 1},
{:hanyu "喻", :pinyin "Yu4", :usage-count 1},
{:hanyu "豫", :pinyin "Yu4", :usage-count 1},
{:hanyu "遇到", :pinyin "yu4 dao4", :usage-count 1},
{:hanyu "预计", :pinyin "yu4 ji4", :usage-count 1},
{:hanyu "遇见", :pinyin "yu4 jian4", :usage-count 1},
{:hanyu "郁闷", :pinyin "yu4 men4", :usage-count 1},
{:hanyu "元", :pinyin "yuan2", :usage-count 1},
{:hanyu "元", :pinyin "Yuan2", :usage-count 1},
{:hanyu "原来", :pinyin "yuan2 lai2", :usage-count 1},
{:hanyu "远", :pinyin "yuan3", :usage-count 1},
{:hanyu "愿", :pinyin "yuan4", :usage-count 1},
{:hanyu "约", :pinyin "yue1", :usage-count 1},
{:hanyu "月", :pinyin "yue4", :usage-count 1},
{:hanyu "月饼", :pinyin "yue4 bing3", :usage-count 1},
{:hanyu "阅读", :pinyin "yue4 du2", :usage-count 1},
{:hanyu "云南", :pinyin "Yun2 nan2", :usage-count 1},
{:hanyu "运动", :pinyin "yun4 dong4", :usage-count 1},
{:hanyu "再", :pinyin "zai4", :usage-count 1},
{:known true, :short-english "at", :hanyu "在", :pinyin "zai4", :usage-count 37},
{:hanyu "再次", :pinyin "zai4 ci4", :usage-count 1},
{:hanyu "再见", :pinyin "zai4 jian4", :usage-count 1},
{:hanyu "在下", :pinyin "zai4 xia4", :usage-count 1},
{:hanyu "脏话", :pinyin "zang1 hua4", :usage-count 1},
{:hanyu "早", :pinyin "zao3", :usage-count 1},
{:hanyu "早饭", :pinyin "zao3 fan4", :usage-count 1},
{:hanyu "早上", :pinyin "zao3 shang5", :usage-count 1},
{:hanyu "早上好", :pinyin "zao3 shang5 hao3", :usage-count 1},
{:hanyu "造成", :pinyin "zao4 cheng2", :usage-count 1},
{:hanyu "怎", :pinyin "zen3", :usage-count 1},
{:known true, :hanyu "怎么", :pinyin "zen3 me5", :usage-count 1},
{:hanyu "怎么样", :pinyin "zen3 me5 yang4", :usage-count 5},
{:hanyu "增加", :pinyin "zeng1 jia1", :usage-count 1},
{:hanyu "站", :pinyin "zhan4", :usage-count 1},
{:hanyu "张", :pinyin "zhang1", :usage-count 1},
{:hanyu "张", :pinyin "Zhang1", :usage-count 1},
{:hanyu "长大", :pinyin "zhang3 da4", :usage-count 1},
{:hanyu "找", :pinyin "zhao3", :usage-count 1},
{:hanyu "找到", :pinyin "zhao3 dao4", :usage-count 1},
{:hanyu "照", :pinyin "zhao4", :usage-count 1},
{:hanyu "照片", :pinyin "zhao4 pian4", :usage-count 1},
{:hanyu "照相", :pinyin "zhao4 xiang4", :usage-count 1},
{:hanyu "这", :pinyin "zhe4", :usage-count 1},
{:known true, :hanyu "这个", :pinyin "zhe4 ge5", :usage-count 2},
{:known true, :hanyu "这里", :pinyin "zhe4 li3", :usage-count 2},
{:hanyu "这么", :pinyin "zhe4 me5", :usage-count 1},
{:hanyu "这些", :pinyin "zhe4 xie1", :usage-count 1},
{:hanyu "这样", :pinyin "zhe4 yang4", :usage-count 1},
{:hanyu "真", :pinyin "zhen1", :usage-count 1},
{:hanyu "挣", :pinyin "zheng1", :usage-count 1},
{:hanyu "争吵", :pinyin "zheng1 chao3", :usage-count 1},
{:hanyu "征服", :pinyin "zheng1 fu2", :usage-count 1},
{:hanyu "正常", :pinyin "zheng4 chang2", :usage-count 1},
{:hanyu "政府", :pinyin "zheng4 fu3", :usage-count 1},
{:short-english "Zhengzhou city", :hanyu "郑州", :pinyin "Zheng4 zhou1", :usage-count 1},
{:hanyu "知道", :pinyin "zhi1 dao4", :usage-count 3},
{:hanyu "支付", :pinyin "zhi1 fu4", :usage-count 1},
{:hanyu "之前", :pinyin "zhi1 qian2", :usage-count 1},
{:hanyu "直", :pinyin "zhi2", :usage-count 1},
{:hanyu "直", :pinyin "Zhi2", :usage-count 1},
{:hanyu "直接", :pinyin "zhi2 jie1", :usage-count 1},
{:hanyu "职业", :pinyin "zhi2 ye4", :usage-count 1},
{:hanyu "只", :pinyin "zhi3", :usage-count 1},
{:hanyu "只有", :pinyin "zhi3 you3", :usage-count 1},
{:hanyu "质量", :pinyin "zhi4 liang4", :usage-count 1},
{:pinyin "zhi4 liao2", :hanyu "治疗", :short-english "treatment", :known false, :usage-count 1},
{:hanyu "至少", :pinyin "zhi4 shao3", :usage-count 1},
{:hanyu "制作", :pinyin "zhi4 zuo4", :usage-count 1},
{:hanyu "中", :pinyin "zhong1", :usage-count 1},
{:hanyu "钟", :pinyin "zhong1", :usage-count 1},
{:hanyu "中", :pinyin "Zhong1", :usage-count 1},
{:hanyu "钟", :pinyin "Zhong1", :usage-count 1},
{:hanyu "忠诚", :pinyin "zhong1 cheng2", :usage-count 1},
{:known true, :hanyu "中国", :pinyin "Zhong1 guo2", :usage-count 7},
{:hanyu "中国人", :pinyin "Zhong1 guo2 ren2", :usage-count 1},
{:hanyu "中间", :pinyin "zhong1 jian1", :usage-count 1},
{:hanyu "中秋节", :pinyin "Zhong1 qiu1 jie2", :usage-count 1},
{:known true, :hanyu "中文", :pinyin "Zhong1 wen2", :usage-count 4},
{:hanyu "中午", :pinyin "zhong1 wu3", :usage-count 1},
{:hanyu "中心", :pinyin "zhong1 xin1", :usage-count 1},
{:hanyu "重视", :pinyin "zhong4 shi4", :usage-count 1},
{:hanyu "周", :pinyin "zhou1", :usage-count 1},
{:hanyu "周", :pinyin "Zhou1", :usage-count 1},
{:hanyu "周二", :pinyin "zhou1 er4", :usage-count 1},
{:hanyu "周末", :pinyin "zhou1 mo4", :usage-count 2},
{:hanyu "周五", :pinyin "zhou1 wu3", :usage-count 2},
{:hanyu "周一", :pinyin "zhou1 yi1", :usage-count 1},
{:hanyu "猪肉", :pinyin "zhu1 rou4", :usage-count 1},
{:hanyu "主义", :pinyin "zhu3 yi4", :usage-count 1},
{:hanyu "住", :pinyin "zhu4", :usage-count 4},
{:hanyu "祝", :pinyin "zhu4", :usage-count 1},
{:hanyu "专用", :pinyin "zhuan1 yong4", :usage-count 1},
{:hanyu "赚", :pinyin "zhuan4", :usage-count 1},
{:hanyu "转盘", :pinyin "zhuan4 pan2", :usage-count 1},
{:hanyu "准备", :pinyin "zhun3 bei4", :usage-count 1},
{:hanyu "滋味", :pinyin "zi1 wei4", :usage-count 1},
{:hanyu "字符", :pinyin "zi4 fu2", :usage-count 1},
{:hanyu "自己", :pinyin "zi4 ji3", :usage-count 1},
{:hanyu "自然", :pinyin "zi4 ran2", :usage-count 1},
{:hanyu "自行车", :pinyin "zi4 xing2 che1", :usage-count 1},
{:hanyu "自由", :pinyin "zi4 you2", :usage-count 1},
{:hanyu "自责", :pinyin "zi4 ze2", :usage-count 1},
{:hanyu "自尊心", :pinyin "zi4 zun1 xin1", :usage-count 1},
{:hanyu "总", :pinyin "zong3", :usage-count 1},
{:hanyu "总是", :pinyin "zong3 shi4", :usage-count 1},
{:hanyu "走", :pinyin "zou3", :usage-count 1},
{:hanyu "走进", :pinyin "zou3 jin4", :usage-count 1},
{:hanyu "租", :pinyin "zu1", :usage-count 1},
{:hanyu "足够", :pinyin "zu2 gou4", :usage-count 1},
{:hanyu "嘴", :pinyin "zui3", :usage-count 1},
{:hanyu "最", :pinyin "zui4", :usage-count 1},
{:hanyu "最后", :pinyin "zui4 hou4", :usage-count 1},
{:hanyu "最近", :pinyin "zui4 jin4", :usage-count 1},
{:hanyu "尊重", :pinyin "zun1 zhong4", :usage-count 1},
{:hanyu "昨天", :pinyin "zuo2 tian1", :usage-count 1},
{:hanyu "做", :pinyin "zuo4", :usage-count 4},
{:hanyu "坐", :pinyin "zuo4", :usage-count 3},
{:hanyu "坐", :pinyin "Zuo4", :usage-count 1},
{:hanyu "做到", :pinyin "zuo4 dao4", :usage-count 1},
{:hanyu "作品", :pinyin "zuo4 pin3", :usage-count 1},
{:hanyu "作业", :pinyin "zuo4 ye4", :usage-count 1},
]
