[
{:pinyin "a1", :hanyu "啊", :short-english "ah!", :usage-count 3},
{:pinyin "ai1", :hanyu "哎", :usage-count 1},
{:pinyin "ai4", :hanyu "爱", :known true, :usage-count 10},
{:pinyin "ai4 ren5", :hanyu "爱人", :usage-count 2},
{:pinyin "an1", :hanyu "安", :usage-count 1},
{:pinyin "An1", :hanyu "安", :usage-count 1},
{:pinyin "An1 hui1", :hanyu "安徽", :usage-count 1},
{:pinyin "an1 jing4", :hanyu "安静", :usage-count 2},
{:pinyin "an1 mian2 yao4", :hanyu "安眠药", :usage-count 1},
{:pinyin "ang2", :hanyu "昂", :usage-count 1},
{:pinyin "ang2 gui4", :hanyu "昂贵", :usage-count 1},
{:pinyin "ba1", :hanyu "八", :usage-count 1},
{:pinyin "ba1 shi4", :hanyu "巴士", :usage-count 1},
{:pinyin "ba3", :hanyu "把", :usage-count 4},
{:pinyin "ba4 ba5", :hanyu "爸爸", :usage-count 1},
{:known true, :pinyin "ba5", :hanyu "吧", :short-english "(suggestion)", :usage-count 4},
{:pinyin "bai2", :hanyu "白", :usage-count 1},
{:pinyin "Bai2", :hanyu "白", :usage-count 1},
{:pinyin "bai2 jiu3", :hanyu "白酒", :usage-count 1},
{:hanyu "白色", :pinyin "bai2 se4", :usage-count 1},
{:pinyin "bai3", :hanyu "百", :short-english "hundred", :known true, :usage-count 4},
{:pinyin "Bai3", :hanyu "百", :usage-count 1},
{:pinyin "Bai3 du4", :hanyu "百度", :usage-count 1},
{:pinyin "bai3 huo4 gong1 si1", :hanyu "百货公司", :usage-count 1},
{:pinyin "ban1", :hanyu "搬", :usage-count 1},
{:pinyin "ban1", :hanyu "般", :usage-count 1},
{:known false, :short-english "class", :hanyu "班级", :pinyin "ban1 ji2", :usage-count 1},
{:pinyin "ban1 jia1", :hanyu "搬家", :usage-count 1},
{:pinyin "ban3", :hanyu "版", :usage-count 1},
{:pinyin "ban4", :hanyu "半", :usage-count 1},
{:pinyin "ban4 gong1 shi4", :hanyu "办公室", :usage-count 1},
{:pinyin "ban4 ye4", :hanyu "半夜", :usage-count 1},
{:pinyin "bang1", :hanyu "帮", :usage-count 1},
{:pinyin "bang1 zhu4", :hanyu "帮助", :usage-count 8},
{:pinyin "bao1", :hanyu "包", :usage-count 1},
{:pinyin "Bao1", :hanyu "包", :usage-count 1},
{:pinyin "bao3 bei4", :hanyu "宝贝", :usage-count 1},
{:pinyin "bao3 chi2", :hanyu "保持", :usage-count 1},
{:pinyin "bao3 mi4", :hanyu "保密", :usage-count 1},
{:pinyin "bao3 nuan3", :hanyu "保暖", :usage-count 1},
{:pinyin "bao3 shou3", :hanyu "保守", :usage-count 1},
{:pinyin "bao3 you4", :hanyu "保佑", :usage-count 1},
{:pinyin "bao4 qian4", :hanyu "抱歉", :usage-count 1},
{:pinyin "bei3", :hanyu "北", :usage-count 1},
{:pinyin "Bei3 jing1", :hanyu "北京", :known true, :usage-count 2},
{:pinyin "bei4", :hanyu "被", :usage-count 1},
{:pinyin "ben3", :hanyu "本", :usage-count 1},
{:pinyin "bi3", :hanyu "比", :short-english "(compare)", :usage-count 10},
{:hanyu "笔", :pinyin "bi3", :usage-count 1},
{:pinyin "Bi3", :hanyu "比", :usage-count 1},
{:pinyin "bi3 ji4 ben3", :hanyu "笔记本", :usage-count 1},
{:pinyin "bi3 jiao4", :hanyu "比较", :usage-count 1},
{:pinyin "bi3 ru2", :hanyu "比如", :usage-count 1},
{:pinyin "bi3 sa4", :hanyu "比萨", :usage-count 1},
{:pinyin "Bi3 sa4", :hanyu "比萨", :usage-count 1},
{:pinyin "bi3 yu4", :hanyu "比喻", :usage-count 1},
{:pinyin "bi4", :hanyu "必", :usage-count 1},
{:pinyin "bi4 qiu2", :hanyu "壁球", :usage-count 1},
{:pinyin "bi4 xu1", :hanyu "必须", :usage-count 1},
{:pinyin "bi4 ye4", :hanyu "毕业", :usage-count 1},
{:pinyin "bi4 zhe5", :hanyu "闭着", :usage-count 1},
{:pinyin "bian1", :hanyu "边", :usage-count 1},
{:pinyin "bian4 hua4", :hanyu "变化", :usage-count 1},
{:hanyu "表", :pinyin "biao3", :usage-count 1},
{:pinyin "biao3 da2", :hanyu "表达", :short-english "express", :known false, :usage-count 1},
{:pinyin "biao3 dan1", :hanyu "表单", :usage-count 2},
{:known true, :pinyin "bie2", :hanyu "别", :short-english "do not", :usage-count 3},
{:pinyin "Bie2", :hanyu "别", :usage-count 1},
{:pinyin "bie2 shu4", :hanyu "别墅", :usage-count 1},
{:pinyin "bin1 guan3", :hanyu "宾馆", :usage-count 1},
{:pinyin "bing4", :hanyu "并", :usage-count 1},
{:pinyin "bo2 ke4", :hanyu "博客", :usage-count 1},
{:pinyin "bu4", :hanyu "不", :known true, :usage-count 37},
{:pinyin "bu4", :hanyu "布", :usage-count 1},
{:pinyin "bu4 bian4", :hanyu "不便", :usage-count 1},
{:pinyin "bu4 cuo4", :hanyu "不错", :usage-count 1},
{:pinyin "bu4 hao3", :hanyu "不好", :known true, :usage-count 2},
{:pinyin "bu4 jiu3", :hanyu "不久", :usage-count 3},
{:pinyin "bu4 ke3 si1 yi4", :hanyu "不可思议", :usage-count 1},
{:known true, :short-english "cannot", :pinyin "bu4 neng2", :hanyu "不能", :usage-count 1},
{:pinyin "bu4 ru2", :hanyu "不如", :usage-count 1},
{:pinyin "bu4 shi4", :hanyu "不是", :short-english "no", :known true, :usage-count 1},
{:pinyin "bu4 xia4", :hanyu "不下", :short-english "to be not less than", :known false, :usage-count 2},
{:pinyin "bu4 xiang4 hua4", :hanyu "不像话", :usage-count 1},
{:pinyin "bu4 xing2", :hanyu "不行", :usage-count 1},
{:pinyin "bu4 xing4", :hanyu "不幸", :usage-count 1},
{:pinyin "cai1", :hanyu "猜", :usage-count 1},
{:pinyin "cai2 neng2", :hanyu "才能", :usage-count 1},
{:pinyin "cai3 qu3", :hanyu "采取", :usage-count 1},
{:pinyin "cai4", :hanyu "菜", :usage-count 1},
{:pinyin "cai4 dan1", :hanyu "菜单", :usage-count 1},
{:pinyin "can1 guan1", :hanyu "参观", :usage-count 1},
{:pinyin "can1 jia1", :hanyu "参加", :usage-count 1},
{:pinyin "cao3", :hanyu "艸", :usage-count 1},
{:pinyin "cha2 kan4", :hanyu "查看", :usage-count 1},
{:pinyin "cha2 zhao3", :hanyu "查找", :usage-count 1},
{:pinyin "cha4", :hanyu "差", :usage-count 1},
{:pinyin "cha4 dian3", :hanyu "差点", :usage-count 1},
{:pinyin "chang2", :hanyu "长", :usage-count 1},
{:pinyin "chang2 chang2", :hanyu "常常", :usage-count 1},
{:pinyin "Chang2 cheng2", :hanyu "长城", :usage-count 1},
{:pinyin "chang2 shi4", :hanyu "尝试", :usage-count 2},
{:pinyin "chang2 tu2", :hanyu "长途", :usage-count 1},
{:hanyu "唱歌", :pinyin "chang4 ge1", :usage-count 1},
{:pinyin "chang4 yi4", :hanyu "倡议", :usage-count 1},
{:pinyin "chao2 xiao4", :hanyu "嘲笑", :usage-count 1},
{:pinyin "chao3", :hanyu "炒", :usage-count 1},
{:pinyin "chao3 zui3", :hanyu "吵嘴", :usage-count 2},
{:pinyin "che1", :hanyu "车", :usage-count 1},
{:pinyin "Che1", :hanyu "车", :usage-count 1},
{:pinyin "chen2 mo4", :hanyu "沉默", :usage-count 1},
{:pinyin "cheng2", :hanyu "城", :usage-count 1},
{:pinyin "cheng2 gong1", :hanyu "成功", :usage-count 1},
{:pinyin "Cheng2 gong1", :hanyu "成功", :usage-count 1},
{:pinyin "cheng2 nuo4", :hanyu "承诺", :usage-count 1},
{:pinyin "cheng2 shu2", :hanyu "成熟", :usage-count 1},
{:pinyin "chi1", :hanyu "吃", :usage-count 2},
{:pinyin "chi1 fan4", :hanyu "吃饭", :usage-count 1},
{:pinyin "chi2 dao4", :hanyu "迟到", :usage-count 1},
{:pinyin "chi3", :hanyu "齿", :usage-count 1},
{:pinyin "Chong2 qing4", :hanyu "重庆", :usage-count 1},
{:pinyin "chong3", :hanyu "宠", :usage-count 1},
{:known true, :short-english "pet", :pinyin "chong3 er2", :hanyu "宠儿", :usage-count 4},
{:pinyin "chong3 wu4", :hanyu "宠物", :usage-count 1},
{:pinyin "chu1", :hanyu "出", :usage-count 1},
{:pinyin "chu1 qu4", :hanyu "出去", :usage-count 1},
{:pinyin "chu1 sheng1", :hanyu "出生", :usage-count 1},
{:pinyin "chu1 wai4", :hanyu "出外", :usage-count 1},
{:pinyin "chu1 xian4", :hanyu "出现", :usage-count 1},
{:pinyin "chu1 xing2", :hanyu "出行", :usage-count 1},
{:pinyin "chu1 zu1", :hanyu "出租", :usage-count 1},
{:pinyin "chu1 zu1 qi4 che1", :hanyu "出租汽车", :usage-count 1},
{:pinyin "chu2 le5", :hanyu "除了", :usage-count 1},
{:pinyin "chu3", :hanyu "处", :usage-count 1},
{:pinyin "chuan1", :hanyu "穿", :short-english "wear", :known false, :usage-count 2},
{:pinyin "chuan2 shuo1", :hanyu "传说", :usage-count 1},
{:pinyin "chuang2", :hanyu "床", :usage-count 1},
{:pinyin "Chun1 jie2", :hanyu "春节", :usage-count 1},
{:pinyin "chun1 tian1", :hanyu "春天", :usage-count 1},
{:pinyin "chun1 yun4", :hanyu "春运", :usage-count 1},
{:pinyin "ci2", :hanyu "词", :usage-count 1},
{:pinyin "ci2 yu3", :hanyu "词语", :usage-count 1},
{:pinyin "ci3", :hanyu "此", :usage-count 1},
{:pinyin "cong2", :hanyu "从", :usage-count 1},
{:pinyin "Cong2", :hanyu "从", :usage-count 1},
{:pinyin "cong2 bu4", :hanyu "从不", :usage-count 1},
{:pinyin "cui4 ruo4", :hanyu "脆弱", :usage-count 1},
{:hanyu "存", :pinyin "cun2", :usage-count 1},
{:pinyin "cuo4", :hanyu "错", :usage-count 1},
{:pinyin "Cuo4", :hanyu "错", :usage-count 1},
{:pinyin "cuo4 wu4", :hanyu "错误", :usage-count 1},
{:pinyin "da3", :hanyu "打", :usage-count 1},
{:pinyin "da3 gong1", :hanyu "打工", :usage-count 1},
{:pinyin "da3 kai1", :hanyu "打开", :usage-count 1},
{:pinyin "da4", :hanyu "大", :usage-count 1},
{:pinyin "da4 ba1", :hanyu "大巴", :usage-count 1},
{:pinyin "da4 gai4", :hanyu "大概", :usage-count 1},
{:pinyin "da4 jia1", :hanyu "大家", :usage-count 1},
{:pinyin "da4 men2", :hanyu "大门", :usage-count 1},
{:pinyin "da4 nao3", :hanyu "大脑", :usage-count 1},
{:pinyin "da4 sha4", :hanyu "大厦", :usage-count 1},
{:pinyin "da4 shi3 guan3", :hanyu "大使馆", :usage-count 3},
{:pinyin "da4 suan4", :hanyu "大蒜", :usage-count 1},
{:pinyin "da4 xiao3", :hanyu "大小", :usage-count 1},
{:pinyin "da4 xue2", :hanyu "大学", :usage-count 1},
{:pinyin "Da4 xue2", :hanyu "大学", :usage-count 1},
{:pinyin "da4 yue1", :hanyu "大约", :usage-count 1},
{:pinyin "dai4", :hanyu "带", :usage-count 1},
{:pinyin "dan1", :hanyu "单", :usage-count 1},
{:pinyin "dan1 du2", :hanyu "单独", :usage-count 1},
{:pinyin "dan1 ren2", :hanyu "单人", :usage-count 1},
{:pinyin "dan1 xin1", :hanyu "担心", :usage-count 1},
{:pinyin "dan4", :hanyu "但", :usage-count 1},
{:pinyin "dan4", :hanyu "蛋", :usage-count 1},
{:pinyin "dan4 gao1", :hanyu "蛋糕", :usage-count 1},
{:pinyin "dan4 shi4", :hanyu "但是", :known true, :usage-count 9},
{:known false, :short-english "when", :pinyin "dang1", :hanyu "当", :usage-count 4},
{:pinyin "dang1 ran2", :hanyu "当然", :usage-count 1},
{:pinyin "dang1 shi2", :hanyu "当时", :usage-count 1},
{:pinyin "dao4", :hanyu "到", :short-english "to", :usage-count 6},
{:pinyin "dao4 chu4", :hanyu "到处", :usage-count 1},
{:pinyin "dao4 da2", :hanyu "到达", :usage-count 1},
{:pinyin "dao4 lai2", :hanyu "到来", :usage-count 1},
{:pinyin "de2 dao4", :hanyu "得到", :usage-count 1},
{:pinyin "de5", :hanyu "地", :usage-count 1},
{:pinyin "de5", :hanyu "得", :short-english "(verb specifier)", :usage-count 8},
{:pinyin "de5", :hanyu "的", :known true, :usage-count 63},
{:pinyin "deng1", :hanyu "灯", :usage-count 1},
{:pinyin "deng1 lu4", :hanyu "登陆", :usage-count 1},
{:pinyin "deng3", :hanyu "等", :short-english "wait for", :usage-count 2},
{:pinyin "deng3 deng3", :hanyu "等等", :usage-count 1},
{:pinyin "deng3 yu2", :hanyu "等于", :usage-count 1},
{:pinyin "di1 tou2", :hanyu "低头", :usage-count 1},
{:pinyin "di4", :hanyu "第", :usage-count 1},
{:pinyin "di4 dao5", :hanyu "地道", :usage-count 1},
{:pinyin "di4 er4", :hanyu "第二", :usage-count 1},
{:pinyin "di4 fang1", :hanyu "地方", :usage-count 1},
{:pinyin "di4 tie3", :hanyu "地铁", :usage-count 1},
{:pinyin "di4 tu2", :hanyu "地图", :usage-count 1},
{:pinyin "di4 yi1 ci4", :hanyu "第一次", :usage-count 1},
{:pinyin "di4 zhi3", :hanyu "地址", :usage-count 1},
{:pinyin "dian3", :hanyu "典", :usage-count 1},
{:known true, :short-english "point", :pinyin "dian3", :hanyu "点", :usage-count 3},
{:pinyin "dian4", :hanyu "店", :usage-count 1},
{:pinyin "dian4 hua4", :hanyu "电话", :usage-count 1},
{:pinyin "dian4 nao3", :hanyu "电脑", :usage-count 3},
{:pinyin "dian4 nao3 ye4 zhe3", :hanyu "电脑业者", :usage-count 1},
{:pinyin "dian4 ying3", :hanyu "电影", :usage-count 1},
{:pinyin "dian4 you2", :hanyu "电邮", :usage-count 11},
{:pinyin "dian4 zi3", :hanyu "电子", :usage-count 1},
{:pinyin "dian4 zi3 you2 jian4", :hanyu "电子邮件", :usage-count 1},
{:pinyin "diao4 cha2", :hanyu "调查", :usage-count 1},
{:pinyin "dong1 ji4", :hanyu "冬季", :usage-count 1},
{:pinyin "dong1 tian1", :hanyu "冬天", :usage-count 1},
{:known true, :short-english "thing", :pinyin "dong1 xi5", :hanyu "东西", :usage-count 2},
{:pinyin "dong3", :hanyu "懂", :usage-count 1},
{:pinyin "dong4 wu4", :hanyu "动物", :usage-count 1},
{:pinyin "dou1", :hanyu "都", :usage-count 2},
{:pinyin "du2 zi4", :hanyu "独自", :usage-count 1},
{:pinyin "du4", :hanyu "度", :usage-count 1},
{:pinyin "du4 zi5", :hanyu "肚子", :usage-count 1},
{:pinyin "duan3", :hanyu "短", :usage-count 1},
{:pinyin "duan3 xin4", :hanyu "短信", :usage-count 1},
{:pinyin "duan3 zan4", :hanyu "短暂", :usage-count 1},
{:pinyin "dui4", :hanyu "对", :usage-count 2},
{:known false, :short-english "sorry", :hanyu "对不起", :pinyin "dui4 bu5 qi3", :usage-count 2},
{:pinyin "dui4 huan4", :hanyu "兑换", :usage-count 1},
{:hanyu "对了", :pinyin "dui4 le5", :usage-count 1},
{:pinyin "dun4", :hanyu "顿", :usage-count 1},
{:known true, :short-english "many", :pinyin "duo1", :hanyu "多", :usage-count 13},
{:pinyin "duo1 jiu3", :hanyu "多久", :usage-count 1},
{:pinyin "duo1 me5", :hanyu "多么", :usage-count 1},
{:pinyin "duo1 shao3", :hanyu "多少", :usage-count 1},
{:pinyin "duo1 shao5", :hanyu "多少", :short-english "how much", :known true, :usage-count 2},
{:pinyin "duo1 yu2", :hanyu "多余", :usage-count 1},
{:pinyin "e3 xin1", :hanyu "恶心", :usage-count 1},
{:pinyin "e4", :hanyu "饿", :usage-count 1},
{:pinyin "en1", :hanyu "恩", :usage-count 1},
{:pinyin "er2 qie3", :hanyu "而且", :usage-count 1},
{:pinyin "er2 zi5", :hanyu "儿子", :usage-count 1},
{:pinyin "er4", :hanyu "二", :known true, :usage-count 1},
{:pinyin "fa1", :hanyu "发", :short-english "send", :known false, :usage-count 6},
{:pinyin "fa1 che1", :hanyu "发车", :usage-count 1},
{:known false, :short-english "send out", :hanyu "发出", :pinyin "fa1 chu1", :usage-count 1},
{:pinyin "fa1 gei3", :hanyu "发给", :usage-count 2},
{:pinyin "fa1 sheng1", :hanyu "发生", :usage-count 1},
{:pinyin "fa1 song4", :hanyu "发送", :usage-count 1},
{:pinyin "fa1 xian4", :hanyu "发现", :usage-count 1},
{:pinyin "fan1 yi4", :hanyu "翻译", :usage-count 1},
{:pinyin "fan2 nao3", :hanyu "烦恼", :usage-count 1},
{:pinyin "fan2 ren2", :hanyu "烦人", :usage-count 1},
{:pinyin "fan4", :hanyu "饭", :usage-count 1},
{:pinyin "fan4 cai4", :hanyu "饭菜", :usage-count 1},
{:pinyin "fan4 dian4", :hanyu "饭店", :usage-count 1},
{:pinyin "fan4 guan3", :hanyu "饭馆", :usage-count 1},
{:pinyin "fang1", :hanyu "方", :usage-count 1},
{:pinyin "fang1 bian4", :hanyu "方便", :usage-count 1},
{:pinyin "fang2", :hanyu "房", :usage-count 1},
{:pinyin "Fang2", :hanyu "房", :usage-count 1},
{:pinyin "fang2 jian1", :hanyu "房间", :usage-count 3},
{:pinyin "fang2 zi5", :hanyu "房子", :usage-count 2},
{:pinyin "fang4", :hanyu "放", :usage-count 1},
{:pinyin "fang4 jia4", :hanyu "放假", :usage-count 1},
{:pinyin "fang4 song1", :hanyu "放松", :usage-count 1},
{:pinyin "fei1 chang2", :hanyu "非常", :usage-count 1},
{:pinyin "fei1 ji1", :hanyu "飞机", :known true, :usage-count 1},
{:pinyin "fei1 ji1 chang3", :hanyu "飞机场", :known true, :usage-count 1},
{:pinyin "fei1 ji1 piao4", :hanyu "飞机票", :usage-count 1},
{:pinyin "fei2", :hanyu "肥", :usage-count 1},
{:pinyin "fen1", :hanyu "分", :usage-count 1},
{:hanyu "分开", :pinyin "fen1 kai1", :usage-count 2},
{:pinyin "Fen1 lan2", :hanyu "芬兰", :short-english "Finland", :known true, :usage-count 30},
{:pinyin "Fen1 lan2 yu3", :hanyu "芬兰语", :usage-count 1},
{:pinyin "fen1 zhong1", :hanyu "分钟", :usage-count 1},
{:pinyin "fen4 nu4", :hanyu "愤怒", :usage-count 1},
{:pinyin "feng1", :hanyu "封", :usage-count 1},
{:pinyin "Feng1", :hanyu "封", :usage-count 1},
{:pinyin "feng1 jing3", :hanyu "风景", :usage-count 1},
{:pinyin "fu2 wu4 yuan2", :hanyu "服务员", :usage-count 1},
{:pinyin "fu4", :hanyu "付", :usage-count 1},
{:pinyin "Fu4", :hanyu "付", :usage-count 1},
{:pinyin "fu4 ben3", :hanyu "副本", :usage-count 1},
{:pinyin "fu4 jin4", :hanyu "附近", :usage-count 1},
{:pinyin "fu4 mu3", :hanyu "父母", :usage-count 1},
{:pinyin "fu4 qian2", :hanyu "付钱", :usage-count 1},
{:pinyin "fu4 qin1", :hanyu "父亲", :usage-count 1},
{:pinyin "fu4 yu4", :hanyu "富裕", :usage-count 1},
{:pinyin "Fu4 yu4", :hanyu "富裕", :usage-count 1},
{:pinyin "fu4 za2", :hanyu "复杂", :usage-count 1},
{:pinyin "gai1", :hanyu "该", :usage-count 1},
{:pinyin "gai3 bian4", :hanyu "改变", :usage-count 1},
{:pinyin "gan1 jing4", :hanyu "干净", :usage-count 1},
{:pinyin "gan3", :hanyu "敢", :usage-count 1},
{:pinyin "gan3", :hanyu "赶", :usage-count 1},
{:pinyin "gan3 dao4", :hanyu "感到", :usage-count 1},
{:pinyin "gan3 jue2", :hanyu "感觉", :usage-count 1},
{:pinyin "gan3 mao4", :hanyu "感冒", :usage-count 1},
{:pinyin "gan3 qing2", :hanyu "感情", :usage-count 1},
{:pinyin "gan3 xie4", :hanyu "感谢", :usage-count 1},
{:pinyin "gang1", :hanyu "刚", :usage-count 1},
{:pinyin "gao1", :hanyu "高", :usage-count 1},
{:pinyin "Gao1", :hanyu "高", :usage-count 1},
{:pinyin "gao1 su4", :hanyu "高速", :usage-count 1},
{:hanyu "高速路", :pinyin "gao1 su4 lu4", :usage-count 1},
{:pinyin "gao1 xing4", :hanyu "高兴", :usage-count 1},
{:known true, :short-english "to tell", :pinyin "gao4 su5", :hanyu "告诉", :usage-count 8},
{:pinyin "ge1", :hanyu "歌", :usage-count 1},
{:pinyin "ge1 ci2", :hanyu "歌词", :usage-count 1},
{:pinyin "ge2", :hanyu "格", :usage-count 1},
{:known true, :short-english "individual", :pinyin "ge4", :hanyu "个", :usage-count 6},
{:pinyin "gei3", :hanyu "给", :known true, :usage-count 8},
{:pinyin "gen1", :hanyu "跟", :usage-count 1},
{:known true, :short-english "more", :pinyin "geng4", :hanyu "更", :usage-count 4},
{:pinyin "gong1 gong4", :hanyu "公共", :usage-count 1},
{:pinyin "gong1 gong4 qi4 che1", :hanyu "公共汽车", :usage-count 1},
{:pinyin "gong1 ju4", :hanyu "工具", :usage-count 1},
{:pinyin "gong1 lu4", :hanyu "公路", :usage-count 1},
{:pinyin "gong1 yi4 mei3 shu4", :hanyu "工艺美术", :usage-count 1},
{:pinyin "gong1 yuan2", :hanyu "公园", :usage-count 1},
{:pinyin "gong1 zuo4", :hanyu "工作", :usage-count 4},
{:pinyin "gou3", :hanyu "狗", :known true, :usage-count 1},
{:pinyin "gou3 liang2", :hanyu "狗粮", :usage-count 1},
{:pinyin "gou4", :hanyu "购", :usage-count 1},
{:pinyin "gou4 cheng2", :hanyu "构成", :usage-count 1},
{:pinyin "gou4 mai3", :hanyu "购买", :usage-count 1},
{:pinyin "gu1 er2 yuan4", :hanyu "孤儿院", :usage-count 1},
{:pinyin "gu4 ding4", :hanyu "固定", :usage-count 1},
{:pinyin "gu4 ke4", :hanyu "顾客", :usage-count 1},
{:pinyin "gu4 shi4", :hanyu "故事", :usage-count 1},
{:pinyin "guai3", :hanyu "拐", :usage-count 1},
{:pinyin "guan1", :hanyu "关", :usage-count 1},
{:pinyin "Guan1", :hanyu "关", :usage-count 1},
{:pinyin "guan1 bi4", :hanyu "关闭", :usage-count 1},
{:pinyin "guan1 xin1", :hanyu "关心", :usage-count 1},
{:pinyin "guan1 yu2", :hanyu "关于", :usage-count 1},
{:pinyin "guan3", :hanyu "馆", :usage-count 4},
{:pinyin "guang4", :hanyu "逛", :usage-count 1},
{:pinyin "gui3", :hanyu "鬼", :usage-count 1},
{:pinyin "gui4", :hanyu "贵", :usage-count 2},
{:pinyin "guo2", :hanyu "国", :usage-count 1},
{:pinyin "Guo2", :hanyu "国", :usage-count 1},
{:pinyin "guo2 ji4", :hanyu "国际", :usage-count 1},
{:pinyin "guo2 jia1", :hanyu "国家", :usage-count 1},
{:pinyin "guo3", :hanyu "果", :usage-count 1},
{:pinyin "guo3 zhi1", :hanyu "果汁", :usage-count 1},
{:pinyin "guo4", :hanyu "过", :short-english "(experienced)", :usage-count 4},
{:pinyin "Guo4", :hanyu "过", :usage-count 1},
{:pinyin "guo4 du4", :hanyu "过度", :usage-count 1},
{:pinyin "guo4 nian2", :hanyu "过年", :usage-count 1},
{:pinyin "ha1", :hanyu "哈", :usage-count 1},
{:pinyin "Ha1", :hanyu "哈", :usage-count 1},
{:pinyin "ha1 ha1", :hanyu "哈哈", :usage-count 1},
{:pinyin "hai1", :hanyu "嗨", :short-english "hey!", :known false, :usage-count 1},
{:pinyin "hai2", :hanyu "孩", :usage-count 1},
{:known true, :short-english "still", :pinyin "hai2", :hanyu "还", :usage-count 4},
{:pinyin "hai2 shi5", :hanyu "还是", :usage-count 5},
{:pinyin "hai2 you3", :hanyu "还有", :short-english "furthermore", :known true, :usage-count 3},
{:known true, :short-english "child", :pinyin "hai2 zi5", :hanyu "孩子", :usage-count 1},
{:pinyin "hai2 zi5 men5", :hanyu "孩子们", :usage-count 5},
{:pinyin "hai3", :hanyu "海", :usage-count 1},
{:pinyin "Hai3", :hanyu "海", :usage-count 1},
{:pinyin "hai4 pa4", :hanyu "害怕", :usage-count 1},
{:pinyin "hai4 xiu1", :hanyu "害羞", :usage-count 1},
{:pinyin "han2 leng3", :hanyu "寒冷", :usage-count 1},
{:pinyin "Han4 yu3", :hanyu "汉语", :usage-count 2},
{:pinyin "hao3", :hanyu "好", :short-english "good", :known true, :usage-count 27},
{:pinyin "hao3 hao3", :hanyu "好好", :usage-count 1},
{:pinyin "hao3 kan4", :hanyu "好看", :usage-count 2},
{:pinyin "hao4", :hanyu "号", :short-english "number", :known false, :usage-count 1},
{:pinyin "hao4 ma3", :hanyu "号码", :usage-count 1},
{:pinyin "he1", :hanyu "喝", :usage-count 1},
{:pinyin "he1 he1", :hanyu "呵呵", :usage-count 1},
{:pinyin "he1 jiu3", :hanyu "喝酒", :usage-count 1},
{:known true, :short-english "and", :pinyin "he2", :hanyu "和", :usage-count 15},
{:pinyin "he2", :hanyu "河", :usage-count 1},
{:pinyin "He2", :hanyu "和", :usage-count 1},
{:pinyin "he2 li3", :hanyu "合理", :usage-count 1},
{:pinyin "He2 nan2", :hanyu "河南", :usage-count 1},
{:pinyin "he2 shui3", :hanyu "河水", :usage-count 1},
{:pinyin "he2 ying3", :hanyu "合影", :usage-count 1},
{:pinyin "He4 er3 xin1 ji1", :hanyu "赫尔辛基", :short-english "Helsinki", :usage-count 1},
{:pinyin "hei1", :hanyu "黑", :usage-count 1},
{:pinyin "Hei1", :hanyu "黑", :usage-count 1},
{:hanyu "黑色", :pinyin "hei1 se4", :usage-count 1},
{:pinyin "hen3", :hanyu "很", :short-english "very", :known true, :usage-count 41},
{:pinyin "hen4", :hanyu "恨", :usage-count 1},
{:pinyin "hong2", :hanyu "宏", :usage-count 1},
{:pinyin "hong2", :hanyu "红", :usage-count 1},
{:pinyin "Hong2", :hanyu "红", :usage-count 1},
{:pinyin "hong2 qi2", :hanyu "红旗", :usage-count 1},
{:pinyin "Hong2 qi2", :hanyu "红旗", :usage-count 1},
{:pinyin "hong2 se4", :hanyu "红色", :usage-count 2},
{:pinyin "hou2 long2", :hanyu "喉咙", :usage-count 1},
{:pinyin "hou4", :hanyu "后", :usage-count 1},
{:pinyin "Hou4", :hanyu "后", :usage-count 1},
{:known true, :short-english "afterwards", :pinyin "hou4 lai2", :hanyu "后来", :usage-count 3},
{:pinyin "hou4 mian5", :hanyu "后面", :usage-count 1},
{:pinyin "hou4 tian1", :hanyu "后天", :usage-count 1},
{:pinyin "hu2 zi5", :hanyu "胡子", :usage-count 1},
{:pinyin "hu4", :hanyu "互", :usage-count 1},
{:pinyin "hu4", :hanyu "护", :usage-count 1},
{:pinyin "hu4 zhao4", :hanyu "护照", :usage-count 1},
{:pinyin "hua1", :hanyu "花", :short-english "spend", :known false, :usage-count 1},
{:pinyin "Hua1", :hanyu "花", :usage-count 1},
{:pinyin "hua1 yuan2", :hanyu "花园", :usage-count 1},
{:pinyin "hua2 xue3", :hanyu "滑雪", :usage-count 1},
{:pinyin "hua4", :hanyu "画", :usage-count 6},
{:pinyin "hua4", :hanyu "话", :short-english "words", :known false, :usage-count 2},
{:pinyin "hua4 mian4", :hanyu "画面", :usage-count 1},
{:pinyin "hua4 xiang4", :hanyu "画像", :usage-count 1},
{:hanyu "化学家", :pinyin "hua4 xue2 jia1", :usage-count 1},
{:pinyin "hua4 zhuang1", :hanyu "化妆", :usage-count 1},
{:pinyin "huai4", :hanyu "坏", :usage-count 1},
{:pinyin "huai4 ren2", :hanyu "坏人", :usage-count 1},
{:pinyin "huai4 shi4", :hanyu "坏事", :usage-count 1},
{:pinyin "huan1 ying2", :hanyu "欢迎", :usage-count 3},
{:pinyin "huan2 cheng2", :hanyu "环城", :usage-count 1},
{:pinyin "huan2 gei3", :hanyu "还给", :usage-count 1},
{:pinyin "huan2 jing4", :hanyu "环境", :usage-count 1},
{:pinyin "huan3 man4", :hanyu "缓慢", :usage-count 1},
{:pinyin "huan4", :hanyu "换", :usage-count 4},
{:pinyin "huan4 cheng2", :hanyu "换成", :short-english "to exchange (sth)", :known false, :usage-count 1},
{:pinyin "hui1", :hanyu "灰", :usage-count 1},
{:pinyin "hui1 se4", :hanyu "灰色", :usage-count 1},
{:pinyin "hui2", :hanyu "回", :usage-count 1},
{:pinyin "hui2 da2", :hanyu "回答", :usage-count 6},
{:pinyin "hui2 fu4", :hanyu "回复", :usage-count 1},
{:pinyin "hui2 jia1", :hanyu "回家", :usage-count 1},
{:known true, :short-english "can", :pinyin "hui4", :hanyu "会", :usage-count 7},
{:pinyin "hui4 hua4", :hanyu "绘画", :usage-count 1},
{:pinyin "huo2 dong4", :hanyu "活动", :usage-count 1},
{:pinyin "huo3 che1", :hanyu "火车", :usage-count 1},
{:pinyin "huo3 che1 zhan4", :hanyu "火车站", :usage-count 1},
{:pinyin "huo4 xu3", :hanyu "或许", :usage-count 1},
{:pinyin "huo4 zhe3", :hanyu "或者", :usage-count 1},
{:pinyin "ji1", :hanyu "机", :usage-count 1},
{:pinyin "Ji1", :hanyu "机", :usage-count 1},
{:pinyin "ji1 chang3", :hanyu "机场", :usage-count 1},
{:pinyin "ji1 dan4", :hanyu "鸡蛋", :usage-count 1},
{:pinyin "ji1 rou4", :hanyu "鸡肉", :usage-count 1},
{:pinyin "ji2", :hanyu "即", :usage-count 1},
{:pinyin "ji2", :hanyu "极", :usage-count 1},
{:pinyin "ji2 jiang1", :hanyu "即将", :usage-count 1},
{:pinyin "ji2 shi3", :hanyu "即使", :usage-count 1},
{:pinyin "ji3", :hanyu "几", :usage-count 1},
{:pinyin "ji3 tian1", :hanyu "几天", :usage-count 1},
{:pinyin "ji4", :hanyu "寄", :usage-count 3},
{:pinyin "ji4 de5", :hanyu "记得", :usage-count 1},
{:pinyin "ji4 hua4", :hanyu "计划", :usage-count 6},
{:pinyin "ji4 jie2", :hanyu "季节", :usage-count 1},
{:pinyin "ji4 suan4", :hanyu "计算", :usage-count 1},
{:pinyin "ji4 suan4 ji1", :hanyu "计算机", :usage-count 1},
{:pinyin "ji4 xu4", :hanyu "继续", :usage-count 2},
{:pinyin "jia1", :hanyu "家", :usage-count 1},
{:pinyin "Jia1", :hanyu "家", :usage-count 1},
{:pinyin "Jia1 ding4", :hanyu "嘉定", :usage-count 1},
{:pinyin "jia1 ren2", :hanyu "家人", :usage-count 1},
{:pinyin "jia1 ting2", :hanyu "家庭", :usage-count 1},
{:pinyin "jia1 wu4", :hanyu "家务", :usage-count 1},
{:pinyin "jia4 ge2", :hanyu "价格", :usage-count 1},
{:pinyin "jian1", :hanyu "间", :usage-count 1},
{:pinyin "jian1 chi2", :hanyu "坚持", :usage-count 1},
{:pinyin "jian1 yu4", :hanyu "监狱", :usage-count 1},
{:pinyin "jian1 zhi2", :hanyu "兼职", :usage-count 1},
{:pinyin "jian3 cha2", :hanyu "检查", :usage-count 1},
{:pinyin "jian3 fei2", :hanyu "减肥", :usage-count 1},
{:pinyin "jian3 shao3", :hanyu "减少", :usage-count 1},
{:pinyin "jian4", :hanyu "件", :usage-count 2},
{:pinyin "jian4", :hanyu "见", :usage-count 1},
{:pinyin "jian4 mian4", :hanyu "见面", :usage-count 1},
{:pinyin "jiang1", :hanyu "将", :usage-count 1},
{:pinyin "Jiang1 bei3", :hanyu "江北", :usage-count 1},
{:pinyin "jiang4", :hanyu "降", :usage-count 1},
{:pinyin "jiao1 cha1", :hanyu "交叉", :usage-count 1},
{:pinyin "jiao1 cha1 kou3", :hanyu "交叉口", :usage-count 1},
{:pinyin "jiao1 liu2", :hanyu "交流", :usage-count 1},
{:pinyin "jiao1 qu1", :hanyu "郊区", :usage-count 1},
{:pinyin "jiao4", :hanyu "叫", :usage-count 1},
{:pinyin "jiao4", :hanyu "教", :usage-count 1},
{:pinyin "Jiao4", :hanyu "教", :usage-count 1},
{:pinyin "jiao4 shi4", :hanyu "教室", :usage-count 1},
{:pinyin "jiao4 yu4", :hanyu "教育", :usage-count 1},
{:pinyin "jie1", :hanyu "接", :usage-count 2},
{:known false, :short-english "receive", :pinyin "jie1 shou4", :hanyu "接受", :usage-count 1},
{:pinyin "jie2", :hanyu "节", :usage-count 1},
{:pinyin "jie2 guo3", :hanyu "结果", :usage-count 1},
{:pinyin "jie2 hun1", :hanyu "结婚", :usage-count 1},
{:pinyin "jie2 shu4", :hanyu "结束", :usage-count 1},
{:pinyin "jie3 da2", :hanyu "解答", :usage-count 1},
{:pinyin "jie3 jue2", :hanyu "解决", :usage-count 1},
{:pinyin "jie4 shao4", :hanyu "介绍", :usage-count 1},
{:known false, :short-english "to borrow sth", :hanyu "借用", :pinyin "jie4 yong4", :usage-count 1},
{:pinyin "jin1", :hanyu "今", :usage-count 1},
{:pinyin "jin1", :hanyu "斤", :short-english "0.5 kg", :known false, :usage-count 1},
{:pinyin "jin1", :hanyu "金", :usage-count 1},
{:pinyin "Jin1", :hanyu "金", :usage-count 1},
{:pinyin "jin1 nian2", :hanyu "今年", :usage-count 1},
{:pinyin "jin1 qian2", :hanyu "金钱", :usage-count 1},
{:pinyin "jin1 tian1", :hanyu "今天", :known true, :usage-count 5},
{:pinyin "jin3 jin3", :hanyu "仅仅", :usage-count 1},
{:pinyin "jin3 liang4", :hanyu "尽量", :usage-count 1},
{:pinyin "jin3 zhang1", :hanyu "紧张", :usage-count 1},
{:pinyin "jin4", :hanyu "劲", :usage-count 1},
{:pinyin "jin4", :hanyu "近", :usage-count 1},
{:pinyin "jin4", :hanyu "进", :usage-count 2},
{:pinyin "jin4 bu4", :hanyu "进步", :usage-count 1},
{:pinyin "jin4 cheng2", :hanyu "进城", :usage-count 1},
{:pinyin "jin4 qu4", :hanyu "进去", :usage-count 1},
{:pinyin "jin4 ru4", :hanyu "进入", :usage-count 1},
{:pinyin "jing1 chang2", :hanyu "经常", :usage-count 2},
{:pinyin "jing1 ya4", :hanyu "惊讶", :usage-count 1},
{:pinyin "jiu3", :hanyu "久", :usage-count 1},
{:pinyin "jiu3", :hanyu "九", :usage-count 1},
{:pinyin "jiu3", :hanyu "酒", :usage-count 1},
{:pinyin "jiu3 ba1", :hanyu "酒吧", :usage-count 2},
{:pinyin "jiu3 dian4", :hanyu "酒店", :usage-count 1},
{:pinyin "jiu4", :hanyu "就", :usage-count 1},
{:pinyin "jiu4 shi4", :hanyu "就是", :usage-count 1},
{:pinyin "ju4 li2", :hanyu "距离", :usage-count 1},
{:pinyin "jue2", :hanyu "觉", :usage-count 1},
{:pinyin "jue2 de5", :hanyu "觉得", :usage-count 1},
{:pinyin "jue2 ding4", :hanyu "决定", :short-english "decide", :known false, :usage-count 1},
{:pinyin "jun1 dui4", :hanyu "军队", :usage-count 1},
{:pinyin "ka1 fei1", :hanyu "咖啡", :known true, :usage-count 1},
{:pinyin "ka3", :hanyu "卡", :usage-count 1},
{:pinyin "kai1", :hanyu "开", :usage-count 2},
{:pinyin "kai1 che1", :hanyu "开车", :usage-count 1},
{:pinyin "kai1 hui4", :hanyu "开会", :usage-count 1},
{:known false, :short-english "open mouth", :pinyin "kai1 kou3", :hanyu "开口", :usage-count 1},
{:pinyin "kai1 shi3", :hanyu "开始", :usage-count 1},
{:known true, :short-english "to feel happy", :pinyin "kai1 xin1", :hanyu "开心", :usage-count 5},
{:pinyin "kai1 xue2", :hanyu "开学", :usage-count 1},
{:pinyin "kan4", :hanyu "看", :short-english "to see", :known true, :usage-count 5},
{:pinyin "kan4 jian4", :hanyu "看见", :usage-count 1},
{:pinyin "kan4 kan5", :hanyu "看看", :usage-count 1},
{:pinyin "kan4 qi3 lai2", :hanyu "看起来", :usage-count 1},
{:pinyin "kao3", :hanyu "考", :usage-count 1},
{:pinyin "kao3 lu:4", :hanyu "考虑", :usage-count 1},
{:pinyin "kao3 shi4", :hanyu "考试", :usage-count 1},
{:pinyin "Ke1 qing1", :hanyu "科卿", :usage-count 1},
{:pinyin "ke3", :hanyu "可", :usage-count 2},
{:pinyin "ke3 ai4", :hanyu "可爱", :usage-count 1},
{:pinyin "ke3 bei1", :hanyu "可悲", :usage-count 1},
{:pinyin "ke3 lian2", :hanyu "可怜", :usage-count 1},
{:pinyin "ke3 neng2", :hanyu "可能", :usage-count 1},
{:pinyin "ke3 shi4", :hanyu "可是", :usage-count 2},
{:pinyin "ke3 xi1", :hanyu "可惜", :usage-count 2},
{:known true, :short-english "can", :pinyin "ke3 yi3", :hanyu "可以", :usage-count 12},
{:pinyin "ke4", :hanyu "课", :usage-count 1},
{:pinyin "ke4 qi5", :hanyu "客气", :usage-count 2},
{:pinyin "ke4 tang2", :hanyu "课堂", :usage-count 1},
{:pinyin "ke4 ti2", :hanyu "课题", :usage-count 1},
{:pinyin "ken3 ding4", :hanyu "肯定", :usage-count 1},
{:pinyin "kong1 jian1", :hanyu "空间", :usage-count 2},
{:pinyin "kong1 tiao2", :hanyu "空调", :usage-count 1},
{:pinyin "kong4", :hanyu "空", :usage-count 2},
{:pinyin "kong4 xian2", :hanyu "空闲", :usage-count 1},
{:pinyin "kou3", :hanyu "口", :usage-count 1},
{:pinyin "ku1", :hanyu "哭", :usage-count 1},
{:pinyin "kuai4", :hanyu "块", :short-english "piece", :usage-count 1},
{:pinyin "kuai4", :hanyu "快", :usage-count 1},
{:pinyin "kuai4 dian3", :hanyu "快点", :usage-count 1},
{:pinyin "kuai4 jie2", :hanyu "快捷", :usage-count 1},
{:pinyin "kuai4 le4", :hanyu "快乐", :usage-count 1},
{:pinyin "kuang4 quan2 shui3", :hanyu "矿泉水", :usage-count 1},
{:pinyin "kun4", :hanyu "困", :usage-count 1},
{:pinyin "kun4 nan5", :hanyu "困难", :usage-count 2},
{:pinyin "la1 mian4", :hanyu "拉面", :usage-count 1},
{:pinyin "lai2", :hanyu "来", :short-english "to come", :known true, :usage-count 16},
{:pinyin "lai2 lin2", :hanyu "来临", :usage-count 1},
{:hanyu "蓝色", :pinyin "lan2 se4", :usage-count 1},
{:pinyin "lang2", :hanyu "狼", :usage-count 1},
{:pinyin "lao3", :hanyu "老", :usage-count 1},
{:pinyin "lao3 ren2", :hanyu "老人", :usage-count 1},
{:pinyin "lao3 shi1", :hanyu "老师", :usage-count 3},
{:pinyin "le4", :hanyu "乐", :usage-count 1},
{:pinyin "Le4", :hanyu "乐", :usage-count 1},
{:pinyin "le5", :hanyu "了", :short-english "(past)", :known true, :usage-count 21},
{:pinyin "lei4", :hanyu "累", :usage-count 1},
{:pinyin "lei4 si4", :hanyu "类似", :usage-count 1},
{:pinyin "leng3", :hanyu "冷", :usage-count 3},
{:pinyin "Leng3", :hanyu "冷", :usage-count 1},
{:known false, :short-english "indifferent", :hanyu "冷淡", :pinyin "leng3 dan4", :usage-count 1},
{:hanyu "冷清", :pinyin "leng3 qing1", :usage-count 1},
{:pinyin "li2", :hanyu "离", :usage-count 1},
{:pinyin "Li2", :hanyu "离", :usage-count 1},
{:pinyin "li2 hun1", :hanyu "离婚", :usage-count 1},
{:pinyin "li2 kai1", :hanyu "离开", :usage-count 1},
{:pinyin "li3", :hanyu "里", :short-english "inside", :known true, :usage-count 2},
{:pinyin "li3 jie3", :hanyu "理解", :usage-count 1},
{:pinyin "li3 mao4", :hanyu "礼貌", :usage-count 1},
{:pinyin "li3 mian4", :hanyu "里面", :usage-count 1},
{:known true, :short-english "gift", :pinyin "li3 wu4", :hanyu "礼物", :usage-count 1},
{:pinyin "li3 you2", :hanyu "理由", :usage-count 1},
{:pinyin "li4", :hanyu "力", :usage-count 1},
{:pinyin "Li4", :hanyu "力", :usage-count 1},
{:pinyin "li4 hai5", :hanyu "利害", :usage-count 1},
{:pinyin "Li4 li4", :hanyu "丽丽", :usage-count 1},
{:pinyin "li4 ru2", :hanyu "例如", :usage-count 1},
{:pinyin "lian2 jie1", :hanyu "连接", :usage-count 1},
{:pinyin "lian2 suo3", :hanyu "连锁", :usage-count 1},
{:pinyin "lian2 wang3", :hanyu "联网", :usage-count 1},
{:pinyin "lian2 xi4", :hanyu "联系", :usage-count 1},
{:pinyin "lian2 zi5", :hanyu "帘子", :usage-count 1},
{:pinyin "lian3", :hanyu "脸", :usage-count 1},
{:pinyin "lian4 xi2", :hanyu "练习", :usage-count 1},
{:pinyin "liang2", :hanyu "凉", :usage-count 1},
{:pinyin "Liang2", :hanyu "凉", :usage-count 1},
{:pinyin "liang3", :hanyu "两", :usage-count 1},
{:pinyin "liang4", :hanyu "辆", :usage-count 1},
{:pinyin "liang4", :hanyu "量", :usage-count 1},
{:pinyin "liao2", :hanyu "聊", :usage-count 1},
{:known true, :short-english "to chat", :pinyin "liao2 tian1", :hanyu "聊天", :usage-count 11},
{:pinyin "liao3 jie3", :hanyu "了解", :usage-count 1},
{:pinyin "lin2", :hanyu "林", :usage-count 1},
{:pinyin "Lin2", :hanyu "林", :usage-count 1},
{:pinyin "lin2 yu4", :hanyu "淋浴", :usage-count 1},
{:pinyin "ling3 yang3", :hanyu "领养", :usage-count 1},
{:pinyin "ling4 wai4", :hanyu "另外", :usage-count 1},
{:pinyin "liu2", :hanyu "留", :usage-count 1},
{:pinyin "Liu2", :hanyu "刘", :usage-count 1},
{:pinyin "liu2 gan3", :hanyu "流感", :usage-count 1},
{:pinyin "liu2 xing2", :hanyu "流行", :usage-count 1},
{:pinyin "liu2 yan2", :hanyu "留言", :usage-count 1},
{:pinyin "liu4", :hanyu "六", :usage-count 1},
{:pinyin "long2", :hanyu "龙", :usage-count 1},
{:pinyin "Long2", :hanyu "龙", :usage-count 1},
{:pinyin "lou2", :hanyu "楼", :usage-count 1},
{:pinyin "lu:3 you2", :hanyu "旅游", :usage-count 2},
{:pinyin "lu4", :hanyu "路", :usage-count 1},
{:pinyin "lu4", :hanyu "露", :usage-count 1},
{:pinyin "Lu4", :hanyu "路", :usage-count 1},
{:pinyin "Lu4", :hanyu "露", :usage-count 1},
{:pinyin "lu4 fei4", :hanyu "路费", :usage-count 1},
{:pinyin "lu4 xian4", :hanyu "路线", :usage-count 1},
{:pinyin "Luo2 bo2 te4", :hanyu "罗伯特", :usage-count 1},
{:pinyin "luo4 po4", :hanyu "落魄", :usage-count 1},
{:known true, :short-english "mama", :pinyin "ma1 ma5", :hanyu "妈妈", :usage-count 8},
{:pinyin "ma2 fan5", :hanyu "麻烦", :usage-count 1},
{:pinyin "ma3", :hanyu "马", :usage-count 1},
{:pinyin "ma3 lu4", :hanyu "马路", :usage-count 2},
{:pinyin "ma3 shang4", :hanyu "马上", :usage-count 1},
{:pinyin "ma4 ren2", :hanyu "骂人", :usage-count 1},
{:pinyin "ma5", :hanyu "么", :usage-count 1},
{:known true, :pinyin "ma5", :hanyu "吗", :short-english "(?)", :usage-count 22},
{:known true, :short-english "to buy", :pinyin "mai3", :hanyu "买", :usage-count 3},
{:pinyin "mai3 mai4", :hanyu "买卖", :usage-count 1},
{:pinyin "mai4", :hanyu "卖", :usage-count 3},
{:pinyin "mai4 ke4", :hanyu "麦克", :usage-count 1},
{:pinyin "Mai4 ke4", :hanyu "麦克", :usage-count 1},
{:pinyin "man4", :hanyu "慢", :usage-count 1},
{:known true, :short-english "busy", :pinyin "mang2", :hanyu "忙", :usage-count 6},
{:pinyin "mang2 lu4", :hanyu "忙碌", :usage-count 1},
{:pinyin "mao1", :hanyu "猫", :usage-count 1},
{:pinyin "mao4 xian3", :hanyu "冒险", :usage-count 1},
{:pinyin "mei2", :hanyu "没", :short-english "(negative)", :usage-count 2},
{:pinyin "mei2 ban4 fa3", :hanyu "没办法", :short-english "there is nothing to be done", :known true, :usage-count 2},
{:pinyin "mei2 cuo4", :hanyu "没错", :usage-count 1},
{:known true, :short-english "it doesn't matter", :hanyu "没关系", :pinyin "mei2 guan1 xi5", :usage-count 1},
{:pinyin "mei2 jin4", :hanyu "没劲", :short-english "exhausted", :known false, :usage-count 1},
{:pinyin "mei2 shi4", :hanyu "没事", :usage-count 1},
{:pinyin "mei2 wen4 ti2", :hanyu "没问题", :usage-count 1},
{:known true, :short-english "haven't", :pinyin "mei2 you3", :hanyu "没有", :usage-count 3},
{:pinyin "mei3", :hanyu "每", :usage-count 1},
{:pinyin "mei3", :hanyu "美", :usage-count 1},
{:pinyin "Mei3", :hanyu "美", :usage-count 1},
{:pinyin "Mei3 guo2", :hanyu "美国", :usage-count 1},
{:pinyin "Mei3 guo2 ren2", :hanyu "美国人", :short-english "American", :known true, :usage-count 1},
{:pinyin "mei3 hao3", :hanyu "美好", :usage-count 1},
{:known true, :short-english "beautiful", :pinyin "mei3 li4", :hanyu "美丽", :usage-count 1},
{:pinyin "mei3 tian1", :hanyu "每天", :short-english "every day", :known true, :usage-count 1},
{:pinyin "mei4 mei5", :hanyu "妹妹", :usage-count 1},
{:pinyin "men2", :hanyu "门", :usage-count 1},
{:pinyin "Men2", :hanyu "门", :usage-count 1},
{:pinyin "men2 kou3", :hanyu "门口", :usage-count 1},
{:pinyin "men5", :hanyu "们", :usage-count 1},
{:pinyin "mi2 ren2", :hanyu "迷人", :usage-count 1},
{:pinyin "mi3", :hanyu "米", :usage-count 1},
{:pinyin "mi4 mi4", :hanyu "秘密", :usage-count 1},
{:pinyin "mian3 fei4", :hanyu "免费", :usage-count 1},
{:pinyin "miao2 shu4", :hanyu "描述", :usage-count 1},
{:pinyin "miao4", :hanyu "庙", :usage-count 1},
{:pinyin "ming2", :hanyu "明", :usage-count 1},
{:pinyin "Ming2", :hanyu "明", :usage-count 1},
{:known true, :pinyin "ming2 bai5", :hanyu "明白", :short-english "understand", :usage-count 14},
{:pinyin "ming2 nian2", :hanyu "明年", :usage-count 1},
{:known true, :short-english "tomorrow", :pinyin "ming2 tian1", :hanyu "明天", :usage-count 2},
{:hanyu "明信片", :pinyin "ming2 xin4 pian4", :usage-count 1},
{:pinyin "mo2", :hanyu "磨", :usage-count 1},
{:pinyin "mo4", :hanyu "末", :usage-count 1},
{:pinyin "mu4", :hanyu "木", :usage-count 1},
{:pinyin "Mu4", :hanyu "木", :usage-count 1},
{:pinyin "na2", :hanyu "拿", :usage-count 1},
{:pinyin "na3", :hanyu "哪", :usage-count 1},
{:pinyin "na3 ge5", :hanyu "哪个", :usage-count 1},
{:pinyin "na3 li3", :hanyu "哪里", :usage-count 1},
{:pinyin "na4", :hanyu "那", :usage-count 1},
{:pinyin "na4 ge5", :hanyu "那个", :usage-count 1},
{:pinyin "na4 li5", :hanyu "那里", :usage-count 1},
{:pinyin "na4 me5", :hanyu "那么", :usage-count 3},
{:pinyin "na4 xie1", :hanyu "那些", :usage-count 1},
{:pinyin "nan2", :hanyu "南", :usage-count 1},
{:pinyin "nan2", :hanyu "难", :usage-count 1},
{:pinyin "Nan2", :hanyu "南", :usage-count 1},
{:pinyin "nan2 dao4", :hanyu "难道", :usage-count 1},
{:known true, :short-english "to feel sad", :pinyin "nan2 guo4", :hanyu "难过", :usage-count 5},
{:pinyin "nan2 hai2", :hanyu "男孩", :usage-count 1},
{:pinyin "nan2 peng2 you5", :hanyu "男朋友", :usage-count 1},
{:pinyin "nan2 ren2", :hanyu "男人", :usage-count 1},
{:pinyin "nan2 shou4", :hanyu "难受", :usage-count 1},
{:pinyin "Nan2 yang2", :hanyu "南阳", :usage-count 1},
{:pinyin "nan2 you3", :hanyu "男友", :usage-count 1},
{:pinyin "ne5", :hanyu "呢", :short-english "(emphasize)", :usage-count 2},
{:pinyin "nei4", :hanyu "内", :usage-count 1},
{:pinyin "nei4 xin1", :hanyu "内心", :usage-count 1},
{:known true, :pinyin "neng2", :hanyu "能", :short-english "be able", :usage-count 8},
{:pinyin "Neng2", :hanyu "能", :usage-count 1},
{:pinyin "ni2", :hanyu "泥", :usage-count 1},
{:pinyin "ni3", :hanyu "你", :known true, :usage-count 152},
{:pinyin "ni3 deng3", :hanyu "你等", :usage-count 1},
{:pinyin "ni3 hao3", :hanyu "你好", :usage-count 5},
{:pinyin "ni3 men5", :hanyu "你们", :usage-count 2},
{:pinyin "nian2", :hanyu "年", :usage-count 1},
{:pinyin "Nian2", :hanyu "年", :usage-count 1},
{:pinyin "nian4", :hanyu "念", :usage-count 1},
{:pinyin "niao3", :hanyu "鸟", :usage-count 1},
{:known true, :short-english "you", :pinyin "nin2", :hanyu "您", :usage-count 2},
{:pinyin "nin2 hao3", :hanyu "您好", :usage-count 1},
{:pinyin "niu2", :hanyu "牛", :usage-count 1},
{:pinyin "Niu2", :hanyu "牛", :usage-count 1},
{:pinyin "niu2 nai3", :hanyu "牛奶", :usage-count 1},
{:pinyin "niu2 rou4", :hanyu "牛肉", :usage-count 1},
{:pinyin "nong2", :hanyu "浓", :usage-count 1},
{:pinyin "nong2 cun1", :hanyu "农村", :usage-count 1},
{:pinyin "nong2 du4", :hanyu "浓度", :usage-count 1},
{:pinyin "nong4", :hanyu "弄", :usage-count 1},
{:pinyin "nu:3 peng2 you5", :hanyu "女朋友", :usage-count 4},
{:pinyin "nu:3 you3", :hanyu "女友", :usage-count 1},
{:known true, :short-english "great effort", :pinyin "nu3 li4", :hanyu "努力", :usage-count 9},
{:pinyin "Nuan3 nuan3", :hanyu "暖暖", :usage-count 1},
{:pinyin "Nuo4 ji1 ya4", :hanyu "诺基亚", :usage-count 1},
{:known false, :short-english "oh", :pinyin "o2", :hanyu "哦", :usage-count 1},
{:known true, :short-english "Euro (currency)", :pinyin "Ou1 yuan2", :hanyu "欧元", :usage-count 3},
{:pinyin "pa4", :hanyu "怕", :short-english "afraid", :usage-count 2},
{:pinyin "Pa4", :hanyu "怕", :usage-count 1},
{:pinyin "pai1", :hanyu "拍", :usage-count 1},
{:pinyin "pai1 she4", :hanyu "拍摄", :usage-count 1},
{:pinyin "pang2 bian1", :hanyu "旁边", :usage-count 1},
{:pinyin "pang4", :hanyu "胖", :usage-count 2},
{:pinyin "pei2", :hanyu "陪", :usage-count 1},
{:pinyin "peng2 you5", :hanyu "朋友", :short-english "friend", :known true, :usage-count 2},
{:pinyin "pi2 bei4", :hanyu "疲惫", :usage-count 1},
{:pinyin "pi2 jiu3", :hanyu "啤酒", :usage-count 1},
{:pinyin "pian2 yi5", :hanyu "便宜", :usage-count 1},
{:pinyin "piao4", :hanyu "票", :usage-count 1},
{:pinyin "piao4 liang5", :hanyu "漂亮", :usage-count 5},
{:pinyin "ping2", :hanyu "平", :usage-count 1},
{:pinyin "ping2 ban3", :hanyu "平板", :usage-count 1},
{:pinyin "ping2 fang1 mi3", :hanyu "平方米", :usage-count 1},
{:pinyin "ping2 guo3", :hanyu "苹果", :usage-count 1},
{:pinyin "ping2 yuan2", :hanyu "平原", :usage-count 1},
{:pinyin "qi1", :hanyu "七", :usage-count 1},
{:pinyin "qi1", :hanyu "期", :short-english "phase", :known false, :usage-count 1},
{:pinyin "qi1 zi5", :hanyu "妻子", :usage-count 1},
{:pinyin "qi2 shi2", :hanyu "其实", :usage-count 1},
{:pinyin "qi2 ta1", :hanyu "其它", :usage-count 1},
{:pinyin "qi3", :hanyu "起", :usage-count 1},
{:pinyin "qi4", :hanyu "汽", :usage-count 1},
{:pinyin "qi4 che1", :hanyu "汽车", :usage-count 1},
{:pinyin "qi4 shui3", :hanyu "汽水", :usage-count 1},
{:pinyin "qian1", :hanyu "千", :usage-count 2},
{:pinyin "qian1 zheng4", :hanyu "签证", :usage-count 2},
{:pinyin "qian2", :hanyu "前", :usage-count 1},
{:known true, :short-english "coin", :pinyin "qian2", :hanyu "钱", :usage-count 5},
{:pinyin "Qian2", :hanyu "钱", :usage-count 1},
{:pinyin "qian2 bian5", :hanyu "前边", :usage-count 1},
{:pinyin "qiang2 jian4", :hanyu "强健", :usage-count 1},
{:pinyin "qiang3 jie2", :hanyu "抢劫", :usage-count 1},
{:pinyin "qiao3 ke4 li4", :hanyu "巧克力", :usage-count 1},
{:pinyin "qin1 wen3", :hanyu "亲吻", :usage-count 1},
{:known true, :short-english "to ask", :pinyin "qing3", :hanyu "请", :usage-count 7},
{:known true, :short-english "Excuse me", :pinyin "qing3 wen4", :hanyu "请问", :usage-count 1},
{:pinyin "qing4", :hanyu "庆", :usage-count 1},
{:pinyin "qing4 dian3", :hanyu "庆典", :usage-count 1},
{:pinyin "qiu1 tian1", :hanyu "秋天", :usage-count 1},
{:pinyin "qu1", :hanyu "区", :usage-count 1},
{:pinyin "qu4", :hanyu "去", :short-english "go", :known true, :usage-count 13},
{:pinyin "que4 ding4", :hanyu "确定", :usage-count 1},
{:pinyin "ran2 hou4", :hanyu "然后", :usage-count 1},
{:pinyin "rang4", :hanyu "让", :usage-count 1},
{:pinyin "re4", :hanyu "热", :usage-count 2},
{:hanyu "热闹", :pinyin "re4 nao5", :usage-count 1},
{:hanyu "热情", :pinyin "re4 qing2", :usage-count 1},
{:known true, :short-english "man", :pinyin "ren2", :hanyu "人", :usage-count 1},
{:pinyin "ren2 min2", :hanyu "人民", :usage-count 1},
{:pinyin "ren2 min2 bi4", :hanyu "人民币", :usage-count 1},
{:pinyin "ren2 sheng1", :hanyu "人生", :usage-count 1},
{:pinyin "ren2 shi4", :hanyu "人士", :usage-count 1},
{:pinyin "ren3 nai4", :hanyu "忍耐", :usage-count 1},
{:pinyin "ren4 he2", :hanyu "任何", :usage-count 1},
{:known true, :short-english "to believe", :pinyin "ren4 wei2", :hanyu "认为", :usage-count 4},
{:pinyin "ren4 zhen1", :hanyu "认真", :usage-count 1},
{:pinyin "ri4", :hanyu "日", :usage-count 1},
{:pinyin "Ri4 ben3", :hanyu "日本", :usage-count 1},
{:pinyin "rong2 yi4", :hanyu "容易", :usage-count 1},
{:pinyin "rou4", :hanyu "肉", :usage-count 1},
{:pinyin "ru2", :hanyu "如", :usage-count 1},
{:known true, :short-english "if", :pinyin "ru2 guo3", :hanyu "如果", :usage-count 7},
{:pinyin "ru2 he2", :hanyu "如何", :usage-count 1},
{:pinyin "ru4 shui4", :hanyu "入睡", :usage-count 1},
{:pinyin "ruan3 jian4", :hanyu "软件", :usage-count 2},
{:pinyin "ruan3 jian4 kai1 fa1 ren2 yuan2", :hanyu "软件开发人员", :usage-count 1},
{:pinyin "sa1 huang3", :hanyu "撒谎", :usage-count 1},
{:pinyin "san1", :hanyu "三", :short-english "three", :known true, :usage-count 4},
{:pinyin "san1", :hanyu "毵", :usage-count 1},
{:pinyin "San1", :hanyu "三", :usage-count 1},
{:pinyin "sang1 na2", :hanyu "桑拿", :usage-count 1},
{:pinyin "se4", :hanyu "色", :usage-count 1},
{:pinyin "sha3", :hanyu "傻", :usage-count 1},
{:pinyin "sha4", :hanyu "厦", :usage-count 1},
{:pinyin "shan1 diao4", :hanyu "删掉", :usage-count 1},
{:pinyin "shan4", :hanyu "善", :usage-count 1},
{:pinyin "shan4 liang2", :hanyu "善良", :usage-count 1},
{:pinyin "shang1", :hanyu "伤", :usage-count 1},
{:pinyin "shang1 chang3", :hanyu "商场", :usage-count 1},
{:pinyin "shang1 dian4", :hanyu "商店", :usage-count 1},
{:pinyin "shang1 hai4", :hanyu "伤害", :usage-count 1},
{:pinyin "shang1 xin1", :hanyu "伤心", :usage-count 1},
{:known true, :short-english "on top", :pinyin "shang4", :hanyu "上", :usage-count 2},
{:pinyin "shang4 chuan2", :hanyu "上传", :usage-count 1},
{:pinyin "Shang4 hai3", :hanyu "上海", :short-english "Shanghai", :known true, :usage-count 4},
{:pinyin "shang4 ke4", :hanyu "上课", :usage-count 1},
{:pinyin "shang4 qu4", :hanyu "上去", :usage-count 1},
{:pinyin "shang4 tian1", :hanyu "上天", :usage-count 1},
{:known false, :short-english "on the Internet", :pinyin "shang4 wang3", :hanyu "上网", :usage-count 1},
{:pinyin "shang4 xian4", :hanyu "上线", :usage-count 1},
{:pinyin "shang4 xing1 qi1", :hanyu "上星期", :usage-count 1},
{:pinyin "shao1", :hanyu "稍", :usage-count 1},
{:pinyin "shao3", :hanyu "少", :usage-count 2},
{:pinyin "she3 de5", :hanyu "舍得", :usage-count 1},
{:pinyin "she4", :hanyu "摄", :usage-count 1},
{:pinyin "she4 ji4", :hanyu "设计", :usage-count 1},
{:pinyin "she4 tuan2", :hanyu "社团", :usage-count 1},
{:pinyin "shen1", :hanyu "深", :usage-count 1},
{:pinyin "shen1 bian1", :hanyu "身边", :usage-count 1},
{:pinyin "shen1 cai2", :hanyu "身材", :usage-count 1},
{:pinyin "shen1 fen4", :hanyu "身份", :usage-count 1},
{:pinyin "shen1 fen4 zheng4", :hanyu "身份证", :usage-count 1},
{:pinyin "shen1 shang5", :hanyu "身上", :usage-count 1},
{:pinyin "shen1 ti3", :hanyu "身体", :usage-count 1},
{:pinyin "shen1 ye4", :hanyu "深夜", :usage-count 1},
{:pinyin "shen2 me5", :hanyu "什么", :known true, :usage-count 12},
{:pinyin "shen4 zhi4", :hanyu "甚至", :usage-count 1},
{:pinyin "sheng1", :hanyu "声", :usage-count 1},
{:pinyin "sheng1", :hanyu "生", :usage-count 1},
{:pinyin "sheng1 bing4", :hanyu "生病", :usage-count 1},
{:known true, :short-english "birthday", :pinyin "sheng1 ri4", :hanyu "生日", :usage-count 1},
{:pinyin "sheng1 yin1", :hanyu "声音", :usage-count 1},
{:pinyin "Sheng4 dan4 jie2", :hanyu "圣诞节", :usage-count 1},
{:pinyin "Sheng4 dan4 shu4", :hanyu "圣诞树", :usage-count 1},
{:pinyin "sheng4 li4", :hanyu "胜利", :usage-count 1},
{:pinyin "sheng4 xia4", :hanyu "剩下", :usage-count 1},
{:pinyin "shi1 bai4", :hanyu "失败", :usage-count 1},
{:pinyin "shi1 mian2", :hanyu "失眠", :short-english "have insomnia", :known false, :usage-count 1},
{:pinyin "shi1 wang4", :hanyu "失望", :usage-count 1},
{:pinyin "shi1 wu4", :hanyu "失误", :usage-count 1},
{:pinyin "shi2", :hanyu "十", :known true, :usage-count 1},
{:known false, :short-english "time", :pinyin "shi2", :hanyu "时", :usage-count 1},
{:pinyin "Shi2", :hanyu "时", :usage-count 1},
{:pinyin "shi2 chang2", :hanyu "时常", :usage-count 1},
{:pinyin "shi2 guang1", :hanyu "时光", :usage-count 1},
{:pinyin "shi2 hou5", :hanyu "时候", :known true, :usage-count 9},
{:pinyin "shi2 jian1", :hanyu "时间", :short-english "time", :known true, :usage-count 2},
{:pinyin "shi2 zai4", :hanyu "实在", :usage-count 1},
{:pinyin "shi3", :hanyu "使", :usage-count 1},
{:pinyin "shi3 yong4", :hanyu "使用", :usage-count 1},
{:hanyu "事", :pinyin "shi4", :usage-count 1},
{:pinyin "shi4", :hanyu "市", :usage-count 1},
{:pinyin "shi4", :hanyu "是", :known true, :usage-count 9},
{:pinyin "shi4", :hanyu "试", :usage-count 1},
{:pinyin "shi4 chang3", :hanyu "市场", :usage-count 2},
{:pinyin "shi4 de5", :hanyu "是的", :usage-count 1},
{:pinyin "shi4 fou3", :hanyu "是否", :usage-count 1},
{:pinyin "shi4 jie4", :hanyu "世界", :usage-count 1},
{:pinyin "shi4 nei4", :hanyu "室内", :usage-count 1},
{:pinyin "shi4 pin2", :hanyu "视频", :usage-count 2},
{:pinyin "shi4 qing5", :hanyu "事情", :usage-count 1},
{:pinyin "shou1 dao4", :hanyu "收到", :usage-count 1},
{:pinyin "shou1 fei4", :hanyu "收费", :usage-count 1},
{:pinyin "shou3 ji1", :hanyu "手机", :short-english "cell phone", :known true, :usage-count 5},
{:pinyin "shou4", :hanyu "瘦", :usage-count 1},
{:pinyin "shou4 zi5", :hanyu "瘦子", :usage-count 1},
{:pinyin "shu1", :hanyu "书", :usage-count 1},
{:pinyin "Shu1", :hanyu "书", :usage-count 1},
{:pinyin "shu1 cai4", :hanyu "蔬菜", :usage-count 1},
{:pinyin "shu1 fu5", :hanyu "舒服", :usage-count 1},
{:pinyin "shu1 ye4", :hanyu "输液", :usage-count 1},
{:pinyin "shu2 lian4", :hanyu "熟练", :usage-count 1},
{:pinyin "shu4 ju4 ku4", :hanyu "数据库", :usage-count 1},
{:pinyin "shuai4 ge1", :hanyu "帅哥", :usage-count 1},
{:pinyin "shuang1", :hanyu "双", :usage-count 1},
{:pinyin "Shuang1", :hanyu "双", :usage-count 1},
{:pinyin "shui3", :hanyu "水", :known true, :usage-count 1},
{:pinyin "Shui3", :hanyu "水", :usage-count 1},
{:pinyin "shui3 guo3", :hanyu "水果", :usage-count 1},
{:pinyin "shui4", :hanyu "睡", :usage-count 1},
{:pinyin "shui4 jiao4", :hanyu "睡觉", :known true, :usage-count 4},
{:pinyin "shui4 xing3", :hanyu "睡醒", :usage-count 1},
{:pinyin "shun4 feng1", :hanyu "顺风", :usage-count 1},
{:pinyin "shuo1", :hanyu "说", :known true, :usage-count 10},
{:pinyin "shuo1 hua4", :hanyu "说话", :usage-count 1},
{:pinyin "Si1 ke1", :hanyu "思科", :usage-count 1},
{:pinyin "si1 ren2", :hanyu "私人", :usage-count 1},
{:pinyin "si3", :hanyu "死", :usage-count 1},
{:pinyin "si3 ban3", :hanyu "死板", :usage-count 1},
{:pinyin "si4", :hanyu "四", :known true, :usage-count 1},
{:hanyu "送给", :pinyin "song4 gei3", :usage-count 1},
{:pinyin "su4", :hanyu "速", :usage-count 1},
{:pinyin "su4 she4", :hanyu "宿舍", :usage-count 1},
{:pinyin "suan4", :hanyu "蒜", :usage-count 1},
{:known false, :short-english "years (of age)", :pinyin "sui4", :hanyu "岁", :usage-count 1},
{:pinyin "sui4", :hanyu "穗", :usage-count 1},
{:pinyin "Sui4", :hanyu "穗", :usage-count 1},
{:known true, :short-english "therefore", :pinyin "suo3 yi3", :hanyu "所以", :usage-count 10},
{:known true, :short-english "he or him", :pinyin "ta1", :hanyu "他", :usage-count 1},
{:pinyin "ta1", :hanyu "她", :short-english "she", :known true, :usage-count 11},
{:pinyin "ta1", :hanyu "它", :usage-count 1},
{:pinyin "ta1 ma1 de5", :hanyu "他妈的", :usage-count 2},
{:pinyin "ta1 men5", :hanyu "他们", :usage-count 1},
{:pinyin "ta1 men5", :hanyu "她们", :usage-count 1},
{:pinyin "ta1 men5", :hanyu "它们", :usage-count 1},
{:pinyin "tai4", :hanyu "太", :usage-count 2},
{:pinyin "tai4 tai5", :hanyu "太太", :short-english "Mrs", :usage-count 3},
{:pinyin "tan1 wan2", :hanyu "贪玩", :usage-count 1},
{:pinyin "tan2 tan2", :hanyu "谈谈", :usage-count 1},
{:pinyin "tan4 tao3", :hanyu "探讨", :usage-count 1},
{:pinyin "tang1", :hanyu "汤", :usage-count 1},
{:pinyin "Tang1", :hanyu "汤", :usage-count 1},
{:pinyin "tang2", :hanyu "糖", :usage-count 1},
{:pinyin "tang3", :hanyu "躺", :usage-count 1},
{:pinyin "tao3 yan4", :hanyu "讨厌", :usage-count 1},
{:pinyin "teng2", :hanyu "疼", :usage-count 1},
{:hanyu "提款", :pinyin "ti2 kuan3", :usage-count 1},
{:pinyin "tian1", :hanyu "天", :usage-count 3},
{:pinyin "tian1 qi4", :hanyu "天气", :usage-count 1},
{:pinyin "tian2", :hanyu "甜", :usage-count 1},
{:pinyin "tian2 dian3", :hanyu "甜点", :usage-count 1},
{:hanyu "填写", :pinyin "tian2 xie3", :usage-count 2},
{:pinyin "tiao2", :hanyu "条", :usage-count 1},
{:pinyin "tiao2", :hanyu "调", :usage-count 1},
{:pinyin "tiao2 zheng3", :hanyu "调整", :usage-count 1},
{:pinyin "tiao4", :hanyu "跳", :usage-count 1},
{:pinyin "tiao4 wu3", :hanyu "跳舞", :usage-count 2},
{:pinyin "ting1", :hanyu "听", :usage-count 3},
{:pinyin "tong1 chang2", :hanyu "通常", :usage-count 1},
{:pinyin "tong2 liao2", :hanyu "同僚", :usage-count 2},
{:pinyin "tong2 shi4", :hanyu "同事", :usage-count 2},
{:known false, :short-english "studymate", :pinyin "tong2 xue2", :hanyu "同学", :usage-count 1},
{:pinyin "tong2 yi4", :hanyu "同意", :usage-count 1},
{:pinyin "tong4", :hanyu "痛", :usage-count 1},
{:pinyin "tou1 tou1", :hanyu "偷偷", :usage-count 1},
{:pinyin "tou2", :hanyu "头", :usage-count 1},
{:pinyin "tou2 fa5", :hanyu "头发", :short-english "hair", :usage-count 1},
{:pinyin "tou2 jin1", :hanyu "头巾", :usage-count 1},
{:pinyin "tou2 teng2", :hanyu "头疼", :usage-count 1},
{:pinyin "tou2 tong4", :hanyu "头痛", :usage-count 1},
{:pinyin "tu1 ran2", :hanyu "突然", :usage-count 1},
{:pinyin "tu2", :hanyu "图", :usage-count 1},
{:pinyin "tu2 shu1 guan3", :hanyu "图书馆", :usage-count 1},
{:pinyin "tu2 xiang4", :hanyu "图像", :usage-count 1},
{:pinyin "tu4 zi5", :hanyu "兔子", :usage-count 1},
{:pinyin "tuan2", :hanyu "团", :usage-count 1},
{:pinyin "tui1", :hanyu "推", :usage-count 1},
{:pinyin "wa5", :hanyu "哇", :usage-count 1},
{:hanyu "外边", :pinyin "wai4 bian5", :usage-count 1},
{:pinyin "wai4 di4", :hanyu "外地", :usage-count 1},
{:pinyin "wai4 mian4", :hanyu "外面", :usage-count 1},
{:pinyin "Wai4 tan1", :hanyu "外滩", :usage-count 1},
{:pinyin "wan2", :hanyu "完", :usage-count 1},
{:pinyin "wan2", :hanyu "玩", :usage-count 3},
{:pinyin "wan2 cheng2", :hanyu "完成", :usage-count 1},
{:pinyin "wan3", :hanyu "晚", :usage-count 3},
{:pinyin "wan3 an1", :hanyu "晚安", :usage-count 1},
{:pinyin "wan3 can1", :hanyu "晚餐", :usage-count 1},
{:pinyin "wan3 shang3", :hanyu "晚晌", :usage-count 4},
{:known true, :short-english "evening", :hanyu "晚上", :pinyin "wan3 shang5", :usage-count 1},
{:pinyin "wang3", :hanyu "往", :usage-count 1},
{:pinyin "wang3", :hanyu "网", :usage-count 1},
{:pinyin "wang3 ba1", :hanyu "网吧", :usage-count 1},
{:known true, :pinyin "wang3 luo4", :hanyu "网络", :short-english "network", :usage-count 1},
{:pinyin "Wang3 luo4", :hanyu "网络", :short-english "internet", :usage-count 1},
{:pinyin "wang3 qian2", :hanyu "往前", :usage-count 1},
{:pinyin "wang3 qiu2", :hanyu "网球", :usage-count 1},
{:pinyin "wang3 shang4", :hanyu "网上", :usage-count 1},
{:pinyin "wang3 ye4", :hanyu "网页", :usage-count 1},
{:pinyin "wei1", :hanyu "微", :usage-count 1},
{:pinyin "Wei1", :hanyu "微", :usage-count 1},
{:pinyin "wei2 jin1", :hanyu "围巾", :usage-count 1},
{:pinyin "wei2 nan2", :hanyu "为难", :usage-count 1},
{:pinyin "wei4", :hanyu "为", :usage-count 1},
{:pinyin "wei4 jing1", :hanyu "味精", :usage-count 1},
{:pinyin "wei4 lai2", :hanyu "未来", :usage-count 1},
{:pinyin "wei4 le5", :hanyu "为了", :usage-count 1},
{:known true, :short-english "why?", :pinyin "wei4 shen2 me5", :hanyu "为什么", :usage-count 7},
{:pinyin "wen2", :hanyu "文", :usage-count 1},
{:pinyin "Wen2", :hanyu "文", :usage-count 1},
{:pinyin "wen2 ben3", :hanyu "文本", :usage-count 1},
{:pinyin "wen2 shu1 chu3 li3", :hanyu "文书处理", :usage-count 1},
{:pinyin "wen2 zhang1", :hanyu "文章", :usage-count 1},
{:pinyin "wen3", :hanyu "吻", :usage-count 1},
{:pinyin "wen4", :hanyu "问", :usage-count 1},
{:known true, :short-english "question", :pinyin "wen4 ti2", :hanyu "问题", :usage-count 6},
{:pinyin "wo3", :hanyu "我", :short-english "I", :known true, :usage-count 223},
{:pinyin "wo3 men5", :hanyu "我们", :known true, :usage-count 16},
{:pinyin "wo4 shi4", :hanyu "卧室", :usage-count 1},
{:pinyin "wu1 ran3", :hanyu "污染", :usage-count 1},
{:pinyin "wu2 li3", :hanyu "无礼", :usage-count 1},
{:pinyin "wu2 liao2", :hanyu "无聊", :usage-count 1},
{:pinyin "wu3", :hanyu "五", :usage-count 1},
{:pinyin "wu3", :hanyu "舞", :usage-count 1},
{:pinyin "wu3 hui4", :hanyu "舞会", :usage-count 1},
{:pinyin "wu4", :hanyu "雾", :usage-count 1},
{:pinyin "xi1 chen2 ji1", :hanyu "吸尘机", :usage-count 1},
{:pinyin "xi1 gua1", :hanyu "西瓜", :usage-count 1},
{:pinyin "xi1 hong2 shi4", :hanyu "西红柿", :usage-count 1},
{:known true, :short-english "to wish for", :pinyin "xi1 wang4", :hanyu "希望", :usage-count 3},
{:pinyin "xi2 su2", :hanyu "习俗", :usage-count 1},
{:pinyin "xi3", :hanyu "喜", :usage-count 1},
{:pinyin "xi3", :hanyu "洗", :usage-count 1},
{:pinyin "xi3 huan5", :hanyu "喜欢", :short-english "to like", :known true, :usage-count 13},
{:pinyin "xi3 tou2", :hanyu "洗头", :usage-count 1},
{:pinyin "xi3 zao3", :hanyu "洗澡", :usage-count 1},
{:pinyin "xi4", :hanyu "阋", :usage-count 1},
{:known true, :short-english "down", :pinyin "xia4", :hanyu "下", :usage-count 4},
{:pinyin "xia4 ke4", :hanyu "下课", :usage-count 1},
{:known true, :short-english "summer", :pinyin "xia4 tian1", :hanyu "夏天", :usage-count 8},
{:pinyin "xia4 wu3", :hanyu "下午", :usage-count 1},
{:pinyin "xia4 xue3", :hanyu "下雪", :usage-count 1},
{:pinyin "xia4 yu3", :hanyu "下雨", :usage-count 1},
{:pinyin "xia4 zai3", :hanyu "下载", :usage-count 1},
{:pinyin "xian1", :hanyu "先", :usage-count 1},
{:pinyin "xian4", :hanyu "线", :usage-count 1},
{:known true, :short-english "now", :pinyin "xian4 zai4", :hanyu "现在", :usage-count 20},
{:pinyin "xian4 zhuang4", :hanyu "现状", :usage-count 1},
{:pinyin "xiang1", :hanyu "相", :usage-count 1},
{:pinyin "Xiang1", :hanyu "相", :usage-count 1},
{:pinyin "xiang1 chu3", :hanyu "相处", :usage-count 1},
{:pinyin "Xiang1 gang3", :hanyu "香港", :usage-count 1},
{:pinyin "xiang1 hu4", :hanyu "相互", :usage-count 1},
{:pinyin "xiang1 si4", :hanyu "相似", :usage-count 1},
{:pinyin "xiang3", :hanyu "想", :short-english "to think", :known true, :usage-count 1},
{:pinyin "xiang3 dao4", :hanyu "想到", :usage-count 1},
{:pinyin "xiang3 nian4", :hanyu "想念", :usage-count 1},
{:pinyin "xiang3 yao4", :hanyu "想要", :usage-count 1},
{:pinyin "xiang4", :hanyu "像", :usage-count 1},
{:pinyin "xiang4", :hanyu "向", :usage-count 1},
{:pinyin "xiang4 ji1", :hanyu "相机", :usage-count 1},
{:pinyin "xiao1 fei4", :hanyu "消费", :usage-count 1},
{:pinyin "xiao1 xi5", :hanyu "消息", :usage-count 1},
{:pinyin "xiao3", :hanyu "小", :usage-count 4},
{:pinyin "xiao3 shi2", :hanyu "小时", :usage-count 1},
{:pinyin "xiao4", :hanyu "笑", :usage-count 1},
{:pinyin "xiao4 yuan2", :hanyu "校园", :usage-count 2},
{:pinyin "xie1", :hanyu "些", :usage-count 1},
{:known true, :short-english "to write", :pinyin "xie3", :hanyu "写", :usage-count 11},
{:pinyin "xie3 xin4", :hanyu "写信", :usage-count 1},
{:pinyin "xie4", :hanyu "谢", :usage-count 1},
{:pinyin "Xie4", :hanyu "谢", :usage-count 1},
{:pinyin "xie4 xie5", :hanyu "谢谢", :usage-count 2},
{:pinyin "xin1", :hanyu "心", :usage-count 1},
{:pinyin "xin1", :hanyu "新", :usage-count 3},
{:pinyin "Xin1 gang3", :hanyu "新港", :usage-count 1},
{:pinyin "xin1 ku3", :hanyu "辛苦", :usage-count 1},
{:pinyin "xin1 li3", :hanyu "心理", :usage-count 1},
{:pinyin "xin1 li5", :hanyu "心里", :short-english "heart", :known false, :usage-count 1},
{:pinyin "xin1 nian2", :hanyu "新年", :usage-count 1},
{:pinyin "xin1 qing2", :hanyu "心情", :usage-count 1},
{:pinyin "xin1 shui3", :hanyu "薪水", :usage-count 1},
{:pinyin "xin1 wen2", :hanyu "新闻", :usage-count 1},
{:pinyin "Xin1 xiang1", :hanyu "新乡", :short-english "Xinxiang city", :known true, :usage-count 4},
{:pinyin "xin1 yuan4", :hanyu "心愿", :usage-count 1},
{:pinyin "Xin1 zheng4", :hanyu "新郑", :usage-count 1},
{:pinyin "xin4", :hanyu "信", :usage-count 1},
{:pinyin "xin4 hao4", :hanyu "信号", :usage-count 1},
{:pinyin "xin4 xi1", :hanyu "信息", :usage-count 1},
{:hanyu "信用卡", :pinyin "xin4 yong4 ka3", :usage-count 1},
{:pinyin "xing1", :hanyu "星", :usage-count 1},
{:pinyin "xing1 qi1", :hanyu "星期", :usage-count 1},
{:pinyin "Xing1 qi1 liu4", :hanyu "星期六", :usage-count 1},
{:pinyin "xing2", :hanyu "型", :usage-count 1},
{:pinyin "xing2", :hanyu "行", :usage-count 3},
{:pinyin "xing2 shi4", :hanyu "形式", :usage-count 1},
{:pinyin "xing4 ge2", :hanyu "性格", :usage-count 1},
{:pinyin "xing4 jiao1", :hanyu "性交", :usage-count 1},
{:pinyin "xiu1 fu4", :hanyu "修复", :usage-count 1},
{:pinyin "xiu1 gai3", :hanyu "修改", :usage-count 1},
{:known true, :short-english "rest", :hanyu "休息", :pinyin "xiu1 xi5", :usage-count 1},
{:pinyin "xu1 ni3", :hanyu "虚拟", :usage-count 1},
{:pinyin "xu1 yao4", :hanyu "需要", :usage-count 3},
{:pinyin "xue2", :hanyu "学", :usage-count 5},
{:pinyin "xue2 fei4", :hanyu "学费", :usage-count 1},
{:pinyin "xue2 xi2", :hanyu "学习", :usage-count 5},
{:pinyin "xue2 xiao4", :hanyu "学校", :usage-count 3},
{:pinyin "xue2 yuan4", :hanyu "学院", :usage-count 1},
{:pinyin "xue3", :hanyu "雪", :usage-count 1},
{:pinyin "Xue3", :hanyu "雪", :usage-count 1},
{:pinyin "xun2 zhao3", :hanyu "寻找", :usage-count 1},
{:pinyin "xun4 su4", :hanyu "迅速", :usage-count 1},
{:pinyin "ya1 li4", :hanyu "压力", :usage-count 1},
{:pinyin "yan1 hua1", :hanyu "烟花", :usage-count 1},
{:pinyin "yan2", :hanyu "言", :usage-count 1},
{:pinyin "yan2 ge2", :hanyu "严格", :usage-count 1},
{:pinyin "yan2 jiu1", :hanyu "研究", :usage-count 1},
{:pinyin "yan2 se4", :hanyu "颜色", :usage-count 1},
{:pinyin "yan2 zhong4", :hanyu "严重", :short-english "serious", :known false, :usage-count 1},
{:pinyin "yan3 jing4", :hanyu "眼镜", :usage-count 1},
{:pinyin "yan3 jing5", :hanyu "眼睛", :usage-count 1},
{:pinyin "yang3 mu4", :hanyu "仰慕", :usage-count 1},
{:pinyin "yang4", :hanyu "样", :usage-count 1},
{:pinyin "yao2 yuan3", :hanyu "遥远", :usage-count 1},
{:known false, :short-english "medicine", :pinyin "yao4", :hanyu "药", :usage-count 2},
{:pinyin "yao4", :hanyu "要", :short-english "want", :known true, :usage-count 30},
{:pinyin "yao4 shi5", :hanyu "钥匙", :usage-count 1},
{:pinyin "ye3", :hanyu "也", :short-english "also", :known true, :usage-count 7},
{:pinyin "ye3 xu3", :hanyu "也许", :usage-count 2},
{:pinyin "ye4", :hanyu "夜", :usage-count 1},
{:pinyin "ye4 zi5", :hanyu "叶子", :usage-count 1},
{:pinyin "yi1", :hanyu "一", :known true, :usage-count 6},
{:pinyin "yi1 ban1", :hanyu "一般", :usage-count 1},
{:pinyin "yi1 ci4", :hanyu "一次", :usage-count 1},
{:pinyin "yi1 dian3", :hanyu "一点", :known true, :usage-count 2},
{:pinyin "yi1 dian3 dian3", :hanyu "一点点", :known true, :usage-count 1},
{:pinyin "yi1 ding4", :hanyu "一定", :usage-count 1},
{:pinyin "yi1 fu5", :hanyu "衣服", :usage-count 1},
{:pinyin "yi1 ge4 ren2", :hanyu "一个人", :known true, :usage-count 1},
{:pinyin "yi1 gui4", :hanyu "衣柜", :usage-count 1},
{:pinyin "yi1 hui4 r5", :hanyu "一会儿", :usage-count 1},
{:pinyin "yi1 qi3", :hanyu "一起", :known true, :usage-count 8},
{:pinyin "yi1 qie4", :hanyu "一切", :usage-count 1},
{:pinyin "yi1 ran2", :hanyu "依然", :usage-count 1},
{:pinyin "yi1 sheng1", :hanyu "医生", :usage-count 2},
{:pinyin "yi1 shi2 zhu4 xing2", :hanyu "衣食住行", :usage-count 1},
{:known false, :short-english "give it a go", :hanyu "一下", :pinyin "yi1 xia4", :usage-count 1},
{:pinyin "yi1 xie1", :hanyu "一些", :short-english "some", :known true, :usage-count 1},
{:pinyin "yi1 yang4", :hanyu "一样", :usage-count 1},
{:hanyu "医院", :pinyin "yi1 yuan4", :usage-count 1},
{:known false, :short-english "straight", :hanyu "一直", :pinyin "yi1 zhi2", :usage-count 1},
{:pinyin "yi2 han4", :hanyu "遗憾", :short-english "regret", :known true, :usage-count 2},
{:pinyin "yi2 ma1", :hanyu "姨妈", :usage-count 1},
{:pinyin "yi3 hou4", :hanyu "以后", :usage-count 1},
{:pinyin "yi3 jing1", :hanyu "已经", :usage-count 2},
{:pinyin "yi3 qian2", :hanyu "以前", :usage-count 2},
{:pinyin "yi3 wai4", :hanyu "以外", :usage-count 1},
{:pinyin "yi4", :hanyu "谊", :usage-count 1},
{:pinyin "yi4 shu4", :hanyu "艺术", :usage-count 1},
{:pinyin "yi4 si5", :hanyu "意思", :usage-count 1},
{:pinyin "yin1", :hanyu "音", :usage-count 1},
{:pinyin "yin1 wei4", :hanyu "因为", :known true, :usage-count 4},
{:pinyin "yin1 yue4", :hanyu "音乐", :usage-count 3},
{:pinyin "yin2 hang2", :hanyu "银行", :usage-count 1},
{:pinyin "yin3 xing2", :hanyu "隐形", :usage-count 1},
{:pinyin "yin3 xing2 yan3 jing4", :hanyu "隐形眼镜", :usage-count 1},
{:pinyin "ying1 gai1", :hanyu "应该", :known true, :usage-count 19},
{:pinyin "Ying1 guo2", :hanyu "英国", :short-english "United Kingdom", :usage-count 1},
{:pinyin "Ying1 yu3", :hanyu "英语", :usage-count 1},
{:pinyin "ying3 xiang3", :hanyu "影响", :usage-count 1},
{:pinyin "ying4 li4", :hanyu "应力", :usage-count 1},
{:pinyin "yong3 yuan3", :hanyu "永远", :usage-count 1},
{:pinyin "yong4", :hanyu "用", :usage-count 6},
{:pinyin "you1 xiu4", :hanyu "优秀", :usage-count 1},
{:pinyin "you2", :hanyu "邮", :usage-count 1},
{:pinyin "you2 jian4", :hanyu "邮件", :usage-count 1},
{:pinyin "you2 ju2", :hanyu "邮局", :usage-count 1},
{:pinyin "you2 piao4", :hanyu "邮票", :usage-count 1},
{:pinyin "you2 xi4", :hanyu "游戏", :usage-count 1},
{:pinyin "you2 xiang1", :hanyu "邮箱", :usage-count 1},
{:pinyin "you2 yong3", :hanyu "游泳", :usage-count 2},
{:pinyin "you2 yu2", :hanyu "由于", :usage-count 1},
{:pinyin "you3", :hanyu "有", :short-english "to have", :known true, :usage-count 12},
{:pinyin "you3 qu4", :hanyu "有趣", :usage-count 1},
{:pinyin "you3 ren2", :hanyu "有人", :usage-count 1},
{:pinyin "you3 shan4", :hanyu "友善", :usage-count 1},
{:pinyin "you3 shi2", :hanyu "有时", :usage-count 1},
{:pinyin "you3 shi4", :hanyu "有事", :usage-count 1},
{:pinyin "you3 yi4", :hanyu "友谊", :usage-count 1},
{:pinyin "you3 yi4 si5", :hanyu "有意思", :usage-count 1},
{:pinyin "you4", :hanyu "又", :usage-count 1},
{:pinyin "you4", :hanyu "右", :usage-count 1},
{:pinyin "yu2", :hanyu "鱼", :usage-count 1},
{:pinyin "Yu2", :hanyu "鱼", :usage-count 1},
{:pinyin "yu2 kuai4", :hanyu "愉快", :usage-count 1},
{:pinyin "yu3", :hanyu "与", :usage-count 1},
{:pinyin "yu3", :hanyu "语", :usage-count 3},
{:pinyin "yu3", :hanyu "雨", :usage-count 1},
{:pinyin "yu3 mao2 qiu2", :hanyu "羽毛球", :usage-count 1},
{:pinyin "yu3 wen2", :hanyu "语文", :usage-count 1},
{:pinyin "yu3 yan2", :hanyu "语言", :usage-count 1},
{:pinyin "yu4", :hanyu "喻", :usage-count 1},
{:pinyin "yu4", :hanyu "浴", :usage-count 1},
{:pinyin "yu4", :hanyu "豫", :usage-count 1},
{:pinyin "Yu4", :hanyu "喻", :usage-count 1},
{:pinyin "Yu4", :hanyu "豫", :usage-count 1},
{:pinyin "yu4 dao4", :hanyu "遇到", :usage-count 1},
{:pinyin "yu4 ji4", :hanyu "预计", :usage-count 1},
{:pinyin "yu4 jian4", :hanyu "遇见", :usage-count 1},
{:pinyin "yu4 men4", :hanyu "郁闷", :usage-count 1},
{:pinyin "yuan2", :hanyu "元", :short-english "unit of money", :known true, :usage-count 2},
{:pinyin "Yuan2", :hanyu "元", :usage-count 1},
{:pinyin "yuan2 lai2", :hanyu "原来", :short-english "actually", :known false, :usage-count 2},
{:pinyin "yuan3", :hanyu "远", :usage-count 1},
{:pinyin "yuan4", :hanyu "愿", :usage-count 1},
{:pinyin "yue1", :hanyu "约", :usage-count 1},
{:pinyin "yue4", :hanyu "月", :short-english "moon", :known true, :usage-count 2},
{:pinyin "yue4 bing3", :hanyu "月饼", :usage-count 1},
{:pinyin "yue4 du2", :hanyu "阅读", :usage-count 1},
{:pinyin "Yun2 nan2", :hanyu "云南", :usage-count 1},
{:pinyin "yun4 dong4", :hanyu "运动", :usage-count 1},
{:pinyin "zai4", :hanyu "再", :usage-count 1},
{:pinyin "zai4", :hanyu "在", :short-english "at", :known true, :usage-count 53},
{:pinyin "zai4 ci4", :hanyu "再次", :usage-count 1},
{:pinyin "zai4 jian4", :hanyu "再见", :usage-count 1},
{:pinyin "zai4 xia4", :hanyu "在下", :usage-count 1},
{:pinyin "zang1", :hanyu "脏", :usage-count 1},
{:pinyin "zang1 hua4", :hanyu "脏话", :usage-count 1},
{:pinyin "zao3", :hanyu "早", :usage-count 1},
{:pinyin "zao3 fan4", :hanyu "早饭", :usage-count 1},
{:pinyin "zao3 shang5", :hanyu "早上", :usage-count 1},
{:pinyin "zao3 shang5 hao3", :hanyu "早上好", :usage-count 1},
{:pinyin "zao4 cheng2", :hanyu "造成", :usage-count 1},
{:pinyin "zen3", :hanyu "怎", :usage-count 1},
{:pinyin "zen3 de5", :hanyu "怎的", :usage-count 1},
{:pinyin "zen3 me5", :hanyu "怎么", :known true, :usage-count 3},
{:pinyin "zen3 me5 yang4", :hanyu "怎么样", :usage-count 12},
{:pinyin "zeng1 jia1", :hanyu "增加", :usage-count 1},
{:pinyin "zhan4", :hanyu "站", :usage-count 1},
{:pinyin "zhang1", :hanyu "张", :usage-count 2},
{:pinyin "Zhang1", :hanyu "张", :usage-count 1},
{:pinyin "zhang3 da4", :hanyu "长大", :usage-count 1},
{:known false, :short-english "account", :hanyu "帐户", :pinyin "zhang4 hu4", :usage-count 3},
{:pinyin "zhao3", :hanyu "找", :usage-count 1},
{:pinyin "zhao3 dao4", :hanyu "找到", :usage-count 2},
{:pinyin "zhao4", :hanyu "照", :usage-count 1},
{:pinyin "zhao4 pian4", :hanyu "照片", :usage-count 2},
{:pinyin "zhao4 xiang4", :hanyu "照相", :usage-count 2},
{:known true, :short-english "this", :pinyin "zhe4", :hanyu "这", :usage-count 3},
{:pinyin "zhe4 ge5", :hanyu "这个", :known true, :usage-count 5},
{:pinyin "zhe4 li3", :hanyu "这里", :known true, :usage-count 2},
{:pinyin "zhe4 me5", :hanyu "这么", :usage-count 2},
{:pinyin "zhe4 xie1", :hanyu "这些", :usage-count 2},
{:pinyin "zhe4 yang4", :hanyu "这样", :short-english "this kind of", :known true, :usage-count 4},
{:pinyin "zhen1", :hanyu "真", :usage-count 5},
{:pinyin "zheng1", :hanyu "挣", :usage-count 1},
{:pinyin "zheng1 chao3", :hanyu "争吵", :usage-count 1},
{:pinyin "zheng1 fu2", :hanyu "征服", :usage-count 1},
{:pinyin "zheng4 chang2", :hanyu "正常", :usage-count 1},
{:pinyin "zheng4 fu3", :hanyu "政府", :usage-count 1},
{:pinyin "Zheng4 zhou1", :hanyu "郑州", :short-english "Zhengzhou city", :usage-count 1},
{:pinyin "zhi1 dao4", :hanyu "知道", :usage-count 4},
{:pinyin "zhi1 fu4", :hanyu "支付", :usage-count 1},
{:pinyin "zhi1 qian2", :hanyu "之前", :usage-count 1},
{:pinyin "zhi2", :hanyu "直", :usage-count 1},
{:pinyin "Zhi2", :hanyu "直", :usage-count 1},
{:pinyin "zhi2 jie1", :hanyu "直接", :usage-count 1},
{:pinyin "zhi2 ye4", :hanyu "职业", :usage-count 1},
{:pinyin "zhi3", :hanyu "只", :usage-count 1},
{:pinyin "zhi3 you3", :hanyu "只有", :usage-count 1},
{:pinyin "zhi4 liang4", :hanyu "质量", :usage-count 1},
{:known false, :short-english "treatment", :hanyu "治疗", :pinyin "zhi4 liao2", :usage-count 1},
{:pinyin "zhi4 shao3", :hanyu "至少", :usage-count 1},
{:pinyin "zhi4 zuo4", :hanyu "制作", :usage-count 1},
{:pinyin "zhong1", :hanyu "中", :usage-count 1},
{:pinyin "zhong1", :hanyu "钟", :usage-count 1},
{:pinyin "Zhong1", :hanyu "中", :usage-count 1},
{:pinyin "Zhong1", :hanyu "钟", :usage-count 1},
{:pinyin "zhong1 cheng2", :hanyu "忠诚", :usage-count 1},
{:pinyin "Zhong1 guo2", :hanyu "中国", :known true, :usage-count 10},
{:pinyin "Zhong1 guo2 ren2", :hanyu "中国人", :short-english "Chinese person", :known true, :usage-count 2},
{:pinyin "zhong1 jian1", :hanyu "中间", :usage-count 1},
{:pinyin "Zhong1 qiu1 jie2", :hanyu "中秋节", :usage-count 1},
{:pinyin "Zhong1 wen2", :hanyu "中文", :known true, :usage-count 4},
{:pinyin "zhong1 wu3", :hanyu "中午", :usage-count 1},
{:pinyin "zhong1 xin1", :hanyu "中心", :usage-count 1},
{:pinyin "zhong4 shi4", :hanyu "重视", :usage-count 1},
{:pinyin "zhou1", :hanyu "周", :usage-count 1},
{:pinyin "Zhou1", :hanyu "周", :usage-count 1},
{:pinyin "zhou1 er4", :hanyu "周二", :usage-count 1},
{:pinyin "zhou1 mo4", :hanyu "周末", :short-english "weekend", :known true, :usage-count 3},
{:pinyin "zhou1 wu3", :hanyu "周五", :usage-count 2},
{:pinyin "zhou1 yi1", :hanyu "周一", :usage-count 1},
{:pinyin "zhu1 rou4", :hanyu "猪肉", :usage-count 1},
{:pinyin "zhu3 yi4", :hanyu "主义", :usage-count 1},
{:known true, :short-english "to live", :pinyin "zhu4", :hanyu "住", :usage-count 5},
{:pinyin "zhu4", :hanyu "祝", :usage-count 1},
{:pinyin "zhuan1 yong4", :hanyu "专用", :usage-count 1},
{:pinyin "zhuan4", :hanyu "赚", :usage-count 1},
{:pinyin "zhuan4 pan2", :hanyu "转盘", :usage-count 1},
{:pinyin "zhun3 bei4", :hanyu "准备", :usage-count 1},
{:pinyin "zi1 wei4", :hanyu "滋味", :usage-count 1},
{:pinyin "zi4 fu2", :hanyu "字符", :usage-count 1},
{:pinyin "zi4 ji3", :hanyu "自己", :usage-count 2},
{:pinyin "zi4 ran2", :hanyu "自然", :usage-count 1},
{:pinyin "zi4 xing2 che1", :hanyu "自行车", :usage-count 1},
{:pinyin "zi4 you2", :hanyu "自由", :usage-count 1},
{:pinyin "zi4 ze2", :hanyu "自责", :usage-count 1},
{:pinyin "zi4 zun1 xin1", :hanyu "自尊心", :usage-count 1},
{:pinyin "zong3", :hanyu "总", :usage-count 1},
{:pinyin "zong3 shi4", :hanyu "总是", :usage-count 1},
{:pinyin "zou3", :hanyu "走", :usage-count 2},
{:pinyin "zou3 jin4", :hanyu "走进", :usage-count 1},
{:pinyin "zu1", :hanyu "租", :usage-count 1},
{:pinyin "zu2 gou4", :hanyu "足够", :usage-count 1},
{:pinyin "zui3", :hanyu "嘴", :usage-count 1},
{:pinyin "zui4", :hanyu "最", :usage-count 1},
{:pinyin "zui4 hou4", :hanyu "最后", :usage-count 1},
{:pinyin "zui4 jin4", :hanyu "最近", :usage-count 1},
{:pinyin "zun1 zhong4", :hanyu "尊重", :usage-count 1},
{:pinyin "zuo2 tian1", :hanyu "昨天", :usage-count 1},
{:pinyin "zuo4", :hanyu "做", :usage-count 5},
{:pinyin "zuo4", :hanyu "坐", :usage-count 3},
{:pinyin "Zuo4", :hanyu "坐", :usage-count 1},
{:pinyin "zuo4 dao4", :hanyu "做到", :usage-count 1},
{:pinyin "zuo4 pin3", :hanyu "作品", :usage-count 1},
{:pinyin "zuo4 ye4", :hanyu "作业", :usage-count 1},
]
